Repository elastic/logstash, pull requests merged in 2018-07, with the labels that each got.

#9750 backport a JRuby 9.1.16.0 stdlib resolv.rb patch in installed 9.1.13.0
  logstash-core/lib/logstash/patches.rb
  logstash-core/lib/logstash/patches/resolv.rb
Labels: bug

#9831 [DOCS] Removes alternative docker pull example
  docs/static/docker.asciidoc
Labels: 6.3.2, docs, v6.4.0, v7.0.0-alpha1

#9828 [DOCS] Clarify methods for stopping Logstash
  docs/static/shutdown.asciidoc
Labels: 6.3.2, docs, v6.4.0, v7.0.0-alpha1

#9543 FieldReference: strict mode
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/src/main/java/org/logstash/FieldReference.java
  logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
  logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
Labels: P2, backport needed, crashes

#9591 FieldReference: add opt-in strict-mode for 6.x
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/src/main/java/org/logstash/FieldReference.java
  logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
  logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
Labels: bug, crashes

#9852 docs index file renamed to docs/index.asciidoc
  rakelib/version.rake
Labels: bug, docs, docs infra
