Repository elastic/logstash, pull requests merged in 2018-12, with the labels that each got.

#10220 Fix x-pack integration tests to work with new ES hits format
  x-pack/qa/integration/monitoring/monitoring_is_disabled_spec.rb
  x-pack/qa/integration/support/shared_examples.rb
Labels: test failure, v7.0.0-beta1

#10221 Add Gemfile.jruby-2.3.lock.release file 6.6.0
  Gemfile.jruby-2.3.lock.release
  Gemfile.template
Labels: v6.6.0

#10228 Add placeholder for alpha2 release notes
  docs/static/releasenotes.asciidoc
Labels: docs
