Repository elastic/logstash, pull requests merged in 2018-06, with the labels that each got.

#9674 [DOCS] Update config steps for open X-Pack
  docs/static/docker.asciidoc
Labels: v6.3.0

#9698 Backport new PQ implementation to 5.6
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueRWBenchmark.java
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueWriteBenchmark.java
  logstash-core/build.gradle
  logstash-core/gemspec_jars.rb
  logstash-core/lib/logstash-core_jars.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/queue_factory.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/util/wrapped_acked_queue.rb
  logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
  logstash-core/spec/logstash/pipeline_pq_file_spec.rb
  logstash-core/spec/logstash/queue_factory_spec.rb
  logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
  logstash-core/src/main/java/JrubyAckedQueueExtService.java
  logstash-core/src/main/java/org/logstash/FileLockFactory.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Batch.java
  logstash-core/src/main/java/org/logstash/ackedqueue/HeadPage.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
  logstash-core/src/main/java/org/logstash/ackedqueue/PageFactory.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueRuntimeException.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
  logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
  logstash-core/src/main/java/org/logstash/ackedqueue/TailPage.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedBatchExtLibrary.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JrubyAckedQueueMemoryExtLibrary.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/AbstractByteBufferPageIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/ByteBufferCleaner.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/ByteBufferPageIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/CheckpointIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/CheckpointIOFactory.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/FileCheckpointIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/LongVector.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/MemoryCheckpointIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIO.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/PageIOFactory.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/wip/MemoryPageIOStream.java
  logstash-core/src/main/java/org/logstash/common/FsUtil.java
  logstash-core/src/main/java/org/logstash/execution/MemoryReadBatch.java
  logstash-core/src/main/java/org/logstash/execution/QueueBatch.java
  logstash-core/src/test/java/org/logstash/FileLockFactoryMain.java
  logstash-core/src/test/java/org/logstash/FileLockFactoryTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/HeadPageTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/QueueTestHelpers.java
  logstash-core/src/test/java/org/logstash/ackedqueue/TestQueue.java
  logstash-core/src/test/java/org/logstash/ackedqueue/TestSettings.java
  logstash-core/src/test/java/org/logstash/ackedqueue/io/ByteBufferPageIOTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/io/FileCheckpointIOTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/io/FileMmapIOTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/io/MemoryCheckpointTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/io/wip/MemoryPageIOStreamTest.java
  logstash-core/src/test/java/org/logstash/stress/Concurrent.java
  spec/spec_helper.rb
Labels: bug

#9759 Encourage central management UI users to add the `monitoring_user` role as well
  docs/static/management/centralized-pipelines.asciidoc
Labels: docs, management, needs review, v6.3.1, v7.0.0-alpha1
