Repository elastic/logstash, pull requests merged in 2018-09, with the labels that each got.

#9962 Fix formatting for Kafka release note for 6.4
  docs/static/releasenotes.asciidoc
Labels: docs

#9985 move queue opening bits from constructor to open_queue method
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: blocker, bug, v7.0.0-alpha1

#9986 move queue opening bits from constructor to open_queue method
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: blocker, bug, v6.4.1

#9987 move queue opening bits from constructor to open_queue method
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: bug, v6.5.0

#9998 changelog for 6.4.1
  docs/static/releasenotes.asciidoc
Labels: v6.4.1

#9994 bump doc to 6.4.1
  docs/index.asciidoc
Labels: v6.4.1

#10012 Backport: Make cgroups more robust and provide the override similar to ES (#9999)
  logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
  logstash-core/spec/logstash/instrument/periodic_poller/cgroup_spec.rb
Labels: v6.4.2

#10011 Backport: Make cgroups more robust and provide the override similar to ES (#9999)
  logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
  logstash-core/spec/logstash/instrument/periodic_poller/cgroup_spec.rb
Labels: v6.5.0

#10010 Backport: Make cgroups more robust and provide the override similar to ES (#9999)
  logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
  logstash-core/spec/logstash/instrument/periodic_poller/cgroup_spec.rb
Labels: v5.6.13

#10018 [6.x backport of #10009] run Agent specs using both memory and persisted queue
  logstash-core/spec/logstash/agent_spec.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: backport, tests, v6.5.0

#9980 [DOCS] Synchronize location of Breaking Changes
  docs/index.asciidoc
Labels: docs, v6.5.0, v7.0.0-alpha1
