Repository elastic/logstash, pull requests merged in 2019-01, with the labels that each got.

#10240 Remove witness classes
  logstash-core/src/main/java/org/logstash/instrument/witness/MetricSerializer.java
  logstash-core/src/main/java/org/logstash/instrument/witness/SerializableWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/Witness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/configuration/ConfigWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/DeadLetterQueueWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/ErrorWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/EventsWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PipelineWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PipelinesWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PluginWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PluginsWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/QueueWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/ReloadWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/process/ProcessWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/schedule/ScheduledWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/schedule/WitnessScheduler.java
  logstash-core/src/test/java/org/logstash/instrument/witness/WitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/configuration/ConfigWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/DeadLetterQueueWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/ErrorWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/EventsWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PipelineWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PipelinesWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PluginWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PluginsWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/QueueWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/ReloadWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/process/ProcessWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/schedule/WitnessSchedulerTest.java
Labels: code cleanup, v7.0.0-beta1

#10242 Remove unused Witness classes
  logstash-core/src/main/java/org/logstash/instrument/witness/MetricSerializer.java
  logstash-core/src/main/java/org/logstash/instrument/witness/SerializableWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/Witness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/configuration/ConfigWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/DeadLetterQueueWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/ErrorWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/EventsWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PipelineWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PipelinesWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PluginWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/PluginsWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/QueueWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/pipeline/ReloadWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/process/ProcessWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/schedule/ScheduledWitness.java
  logstash-core/src/main/java/org/logstash/instrument/witness/schedule/WitnessScheduler.java
  logstash-core/src/test/java/org/logstash/instrument/witness/WitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/configuration/ConfigWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/DeadLetterQueueWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/ErrorWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/EventsWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PipelineWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PipelinesWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PluginWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/PluginsWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/QueueWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/pipeline/ReloadWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/process/ProcessWitnessTest.java
  logstash-core/src/test/java/org/logstash/instrument/witness/schedule/WitnessSchedulerTest.java
Labels: code cleanup, v6.7.0

#10235 Update pipeline.conf
  docs/static/filebeat_modules/system/pipeline.conf
Labels: developer docs, docs

#10244 Resolve javadoc warnings not seen on 1.8.0_181
  logstash-core/src/main/java/co/elastic/logstash/api/PluginHelper.java
  logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ClasspathHelper.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Configuration.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ConfigurationBuilder.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/FilterBuilder.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ReflectionUtils.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Store.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Utils.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Vfs.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
  logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
Labels: code cleanup, v7.0.0-beta1

#10245 Resolve javadoc warnings
  logstash-core/src/main/java/co/elastic/logstash/api/PluginHelper.java
  logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Page.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ClasspathHelper.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Configuration.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ConfigurationBuilder.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/FilterBuilder.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/ReflectionUtils.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Store.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Utils.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/Vfs.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
  logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
Labels: code cleanup, v6.7.0

#10246 Add option for PQ checkpoint retry
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/pipeline_settings.rb
  logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
  logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
  logstash-core/spec/logstash/queue_factory_spec.rb
  logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
  logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/io/FileCheckpointIO.java
Labels: persistent queues, v6.6.0

#10255 Ignore some unit tests that are failing on some Windows platforms
  logstash-core/src/test/java/org/logstash/plugins/codecs/LineTest.java
  logstash-core/src/test/java/org/logstash/plugins/inputs/StdinTest.java
  logstash-core/src/test/java/org/logstash/plugins/outputs/StdoutTest.java
Labels: v6.6.0

#10269 properly set thread name in thread context
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
Labels: bug

#10270 [6.x clean backport of #10269] properly set thread name in thread context
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
Labels: backport, v6.7.0

#10273 [6.4 clean backport of #10269] properly set thread name in thread context
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
Labels: backport, v6.4.4

#10271 [6.5 clean backport of #10269] properly set thread name in thread context
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
Labels: backport, v6.5.5

#10272 [6.6 clean backport of #10269] properly set thread name in thread context
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
Labels: backport, v6.6.0

#10281 Bump http filter to 1.0.0
  Gemfile.jruby-2.3.lock.release
Labels: v6.6.0

#10334 [6.6 clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug (#10113)
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
Labels: backport, v6.6.0

#10335 [6.x clean backport of #10113] synchronize ruby pipeline initialization to fix concurrency bug (#10113)
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
Labels: backport, v6.7.0

#10338 [6.5 clean backport of #10331] correctly handle pipeline actions
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
Labels: backport, v6.5.5

#10336 [6.x clean backport of #10331] correctly handle pipeline actions
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
Labels: backport, v6.7.0

#10340 Update java dependencies
  build.gradle
  logstash-core/build.gradle
  versions.yml
Labels: v7.0.0-beta1

#10358 remove pipeline output workers setting
  config/pipelines.yml
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/pipeline_settings.rb
Labels: breaking change, code cleanup, v7.0.0-beta1

#10337 [6.6 clean backport of #10331] correctly handle pipeline actions
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
Labels: backport, backport needed, v6.6.1

#10346 fix agent silent exit upon pipelines reloading
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
  logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
  logstash-core/lib/logstash/instrument/periodic_pollers.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/lib/logstash/pipeline_action/base.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/lib/logstash/state_resolver.rb
  logstash-core/spec/logstash/agent/converge_spec.rb
  logstash-core/spec/logstash/agent_spec.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
  logstash-core/spec/logstash/pipeline_action/stop_spec.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/spec/support/matchers.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
  x-pack/lib/monitoring/inputs/metrics.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/support/helpers.rb
Labels: bug, v7.0.0-beta1

#10355 [6.x clean backport of #10346] fix agent silent exit upon pipelines reloading
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
  logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
  logstash-core/lib/logstash/instrument/periodic_pollers.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/lib/logstash/pipeline_action/base.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/lib/logstash/state_resolver.rb
  logstash-core/spec/logstash/agent/converge_spec.rb
  logstash-core/spec/logstash/agent_spec.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
  logstash-core/spec/logstash/pipeline_action/stop_spec.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/spec/support/matchers.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
  x-pack/lib/monitoring/inputs/metrics.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/support/helpers.rb
Labels: backport, v6.7.0

#10370 [6.6 clean backport of #10346] fix agent silent exit upon pipelines reloading
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
  logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
  logstash-core/lib/logstash/instrument/periodic_pollers.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/lib/logstash/pipeline_action/base.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/lib/logstash/state_resolver.rb
  logstash-core/spec/logstash/agent/converge_spec.rb
  logstash-core/spec/logstash/agent_spec.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
  logstash-core/spec/logstash/pipeline_action/stop_spec.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/spec/support/matchers.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
  x-pack/lib/monitoring/inputs/metrics.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/support/helpers.rb
Labels: backport, v6.6.1
