Repository elastic/logstash, pull requests merged in 2019-12, with the labels that each got.

#11363 bump version to 7.5.1
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: v7.5.1

#11360 [DOCS] Fixes occurrences of xpack-ref attribute
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: docs, v6.3.3, v6.4.4, v6.5.5, v6.6.1, v6.7.2

#11366 [DOCS] Replaces occurrences of xpack-ref
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: docs, v6.8.6, v7.0.2, v7.1.2, v7.2.2, v7.3.3, v7.4.3, v7.5.1, v7.6.0, v8.0.0

#11379 [7.x][DOCS] Replaces occurrences of xpack-ref (#11366)
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11372 [6.8][DOCS] Replaces occurrences of xpack-ref (#11366)
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11378 [7.5][DOCS] Replaces occurrences of xpack-ref
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/monitoring-internal.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11377 [7.4][DOCS] Replaces occurrences of xpack-ref
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/monitoring-internal.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11376 [7.3][DOCS] Replaces occurrences of xpack-ref
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/monitoring-internal.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11375 [7.2][DOCS] Replaces occurrences of xpack-ref
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11374 [7.1][DOCS] Replaces occurrences of xpack-ref
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11373 [7.0][DOCS] Replaces occurrences of xpack-ref
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/security/logstash.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11371 [6.6][DOCS] Fixes occurrences of xpack-ref attribute (#11360)
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11370 [6.5][DOCS] Fixes occurrences of xpack-ref attribute (#11360)
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11369 [6.4][DOCS] Fixes occurrences of xpack-ref attribute (#11360)
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11368 [6.3][DOCS] Fixes occurrences of xpack-ref attribute (#11360)
  docs/static/deploying.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/intro.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#11400 [gradle] add rootProject.name
  settings.gradle
Labels: build

#11409 [DOCS] Added older release notice.
  docs/static/page_header.html
Labels: docs, v6.8.6

#11410 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport needed, docs, v1.5.7, v2.0.1, v2.1.2, v2.2.4, v2.3.3, v2.4.2, v5.0.3, v5.1.2, v5.2.3, v5.3.2, v5.4.2, v5.5.4, v5.6.13, v5.7.0, v6.0.2, v6.1.4, v6.2.4

#11411 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v6.1.4

#11412 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v6.0.2

#11413 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.6.13

#11414 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.5.4

#11415 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.4.2

#11416 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.3.2

#11417 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.2.3

#11418 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.1.2

#11419 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v5.0.3

#11420 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v2.4.2

#11421 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v2.3.3

#11422 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v2.2.4

#11423 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v2.1.2

#11424 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v2.0.1

#11425 [DOCS] Add EOL notice.
  docs/static/page_header.html
Labels: backport, v1.5.7

#11432 update grok filter to 4.2.0 (for LS 7.5.1)
  Gemfile.jruby-2.5.lock.release
Labels: v7.5.1

#11446 [Doc] Release Notes 6.8.6
  docs/static/releasenotes.asciidoc
Labels: docs

#11448 [Doc] Release notes 7.5.1
  docs/static/releasenotes.asciidoc
Labels: docs
