Repository elastic/logstash, pull requests merged in 2019-02, with the labels that each got.

#10367 [6.5 clean backport of #10346] fix agent silent exit upon pipelines reloading
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb
  logstash-core/lib/logstash/instrument/periodic_poller/pq.rb
  logstash-core/lib/logstash/instrument/periodic_pollers.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/lib/logstash/pipeline_action/base.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
  logstash-core/lib/logstash/pipeline_action/stop.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/lib/logstash/state_resolver.rb
  logstash-core/spec/logstash/agent/converge_spec.rb
  logstash-core/spec/logstash/agent_spec.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/pipeline_action/reload_spec.rb
  logstash-core/spec/logstash/pipeline_action/stop_spec.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/spec/support/matchers.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/plugins/HooksRegistryExt.java
  x-pack/lib/monitoring/inputs/metrics.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/support/helpers.rb
Labels: backport, v6.5.5

#10232 Java plugin API (beta)
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/legacy_ruby_event_spec.rb
  logstash-core/src/main/java/co/elastic/logstash/api/Codec.java
  logstash-core/src/main/java/co/elastic/logstash/api/Configuration.java
  logstash-core/src/main/java/co/elastic/logstash/api/Context.java
  logstash-core/src/main/java/co/elastic/logstash/api/Event.java
  logstash-core/src/main/java/co/elastic/logstash/api/EventFactory.java
  logstash-core/src/main/java/co/elastic/logstash/api/Filter.java
  logstash-core/src/main/java/co/elastic/logstash/api/FilterMatchListener.java
  logstash-core/src/main/java/co/elastic/logstash/api/Input.java
  logstash-core/src/main/java/co/elastic/logstash/api/LogstashPlugin.java
  logstash-core/src/main/java/co/elastic/logstash/api/Output.java
  logstash-core/src/main/java/co/elastic/logstash/api/Plugin.java
  logstash-core/src/main/java/co/elastic/logstash/api/PluginConfigSpec.java
  logstash-core/src/main/java/co/elastic/logstash/api/PluginHelper.java
  logstash-core/src/main/java/co/elastic/logstash/api/v0/Codec.java
  logstash-core/src/main/java/co/elastic/logstash/api/v0/Filter.java
  logstash-core/src/main/java/co/elastic/logstash/api/v0/Input.java
  logstash-core/src/main/java/co/elastic/logstash/api/v0/Output.java
  logstash-core/src/main/java/org/logstash/Event.java
  logstash-core/src/main/java/org/logstash/RubyUtil.java
  logstash-core/src/main/java/org/logstash/StringInterpolation.java
  logstash-core/src/main/java/org/logstash/Timestamp.java
  logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/CommonActions.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaInputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaOutputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/PluginFactory.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/RubyIntegration.java
  logstash-core/src/main/java/org/logstash/execution/InputsController.java
  logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
  logstash-core/src/main/java/org/logstash/plugins/ConfigurationImpl.java
  logstash-core/src/main/java/org/logstash/plugins/ContextImpl.java
  logstash-core/src/main/java/org/logstash/plugins/PluginFactoryExt.java
  logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
  logstash-core/src/main/java/org/logstash/plugins/PluginUtil.java
  logstash-core/src/main/java/org/logstash/plugins/codecs/Line.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/filters/Uuid.java
  logstash-core/src/main/java/org/logstash/plugins/inputs/Stdin.java
  logstash-core/src/main/java/org/logstash/plugins/outputs/Stdout.java
  logstash-core/src/test/java/org/logstash/TimestampTest.java
  logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
  logstash-core/src/test/java/org/logstash/config/ir/compiler/CommonActionsTest.java
  logstash-core/src/test/java/org/logstash/plugins/ConfigurationImplTest.java
  logstash-core/src/test/java/org/logstash/plugins/PluginUtilValidateConfigTest.java
  logstash-core/src/test/java/org/logstash/plugins/TestContext.java
  logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java
  logstash-core/src/test/java/org/logstash/plugins/TestingPlugin.java
  logstash-core/src/test/java/org/logstash/plugins/codecs/LineTest.java
  logstash-core/src/test/java/org/logstash/plugins/filters/UuidTest.java
  logstash-core/src/test/java/org/logstash/plugins/inputs/StdinTest.java
  logstash-core/src/test/java/org/logstash/plugins/outputs/StdoutTest.java
Labels: Java API, v6.7.0, v7.0.0-beta1, work in progress

#10171 Cleanup dependencies
  Gemfile.template
  logstash-core/logstash-core.gemspec
Labels: code cleanup

#10380 rename config option .url and .ca to .hosts and .certificate_authorit
  config/logstash.yml
  docs/static/docker.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/monitoring-output.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings.asciidoc
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/qa/integration/management/multiple_pipelines_spec.rb
  x-pack/qa/integration/management/read_configuration_spec.rb
  x-pack/qa/integration/monitoring/multiple_host_defined_spec.rb
  x-pack/qa/integration/monitoring/persisted_queue_is_enabled_spec.rb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/config_management/extension_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/license_checker/license_info_spec.rb
  x-pack/spec/license_checker/license_manager_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/monitoring/internal_pipeline_source_spec.rb
Labels: enhancement, v7.0.0-beta1

#10391 [6.x backport of #10380] rename config option .url and .ca to .hosts and .certificate_authority
  config/logstash.yml
  docs/static/docker.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/monitoring/configuring-logstash.asciidoc
  docs/static/monitoring/monitoring-output.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings.asciidoc
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/qa/integration/management/multiple_pipelines_spec.rb
  x-pack/qa/integration/management/read_configuration_spec.rb
  x-pack/qa/integration/monitoring/multiple_host_defined_spec.rb
  x-pack/qa/integration/monitoring/persisted_queue_is_enabled_spec.rb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/config_management/extension_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/license_checker/license_info_spec.rb
  x-pack/spec/license_checker/license_manager_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/monitoring/internal_pipeline_source_spec.rb
Labels: backport, v6.7.0

#10390 support old config options and add deprecation warnings
  logstash-core/lib/logstash/runner.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/monitoring/monitoring.rb
Labels: enhancement, v6.7.0

#10403 Update :branch: property in 7.x index.asciidoc
  docs/index.asciidoc
Labels: docs

#10429 [Doc] Reorder files in index to expose topics
  docs/index.asciidoc
Labels: docs

#10437 [Docs] Move field-ref include below xpack content
  docs/index.asciidoc
Labels: docs, work in progress

#10438 Improve docs about using Filebeat modules with Logstash
  docs/static/fb-ls-kafka-example.asciidoc
  docs/static/filebeat-modules.asciidoc
Labels: backport needed, docs, needs review

#10431 remove exclusive lock for Ruby pipeline initialization
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
Labels: v8.0.0

#10462 [7.0 clean backport of #10431] remove exclusive lock for Ruby pipeline initialization
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
Labels: v7.0.0-rc1

#10461 [7.x clean backport of #10431] remove exclusive lock for Ruby pipeline initialization
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipeline_action/create.rb
  logstash-core/lib/logstash/pipeline_action/reload.rb
Labels: v7.1.0

#10469 add release notes template for 5.6.15
  docs/static/releasenotes.asciidoc
Labels: work in progress
