Repository elastic/logstash, pull requests merged in 2020-06, with the labels that each got.

#11864 add support for api_key in xpack monitoring and management
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings-legacy.asciidoc
  x-pack/lib/config_management/elasticsearch_source.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/internal_pipeline_source.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/lib/template.cfg.erb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/monitoring/internal_pipeline_source_spec.rb
Labels: enhancement, v8.0.0

#11953 [7.x clean backport of #11864] add support for api_key authentication in xpack management and monitoring
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings-legacy.asciidoc
  x-pack/lib/config_management/elasticsearch_source.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/internal_pipeline_source.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/lib/template.cfg.erb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/monitoring/inputs/metrics_spec.rb
  x-pack/spec/monitoring/internal_pipeline_source_spec.rb
Labels: backport, enhancement, v7.9.0

#11879 Fix: avoid gsub (frame dependent) usage from Java
  logstash-core/src/main/java/org/logstash/log/DeprecationLoggerExt.java
  logstash-core/src/main/java/org/logstash/log/LoggableExt.java
  logstash-core/src/main/java/org/logstash/log/SlowLoggerExt.java
Labels: backport, v7.7.1

#11974 Doc:Add section to security docs for API key information
  docs/static/security/api-keys.asciidoc
  docs/static/security/logstash.asciidoc
Labels: docs

#11989 Expose again the pipelines queue.data and queue.capacity subdocument
  logstash-core/lib/logstash/api/commands/stats.rb
Labels: v7.8.0

#12014 Doc:Add 7.7.1 release notes to 7.8 branch
  docs/static/releasenotes.asciidoc
Labels: docs

#12009 fix Settings equality test which broke the PipelineConfig equality
  logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
  logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java
Labels: bug

#12013 Doc:Add link to JVM section of support matrix
  docs/static/jvm.asciidoc
Labels: docs

#12025 [DOCS] Fixes Stack Overview links
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: docs, v7.7.1, v7.8.0, v7.9.0, v8.0.0

#12027 [7.8][DOCS] Fixes Stack Overview links (#12025)
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#12028 [7.7][DOCS] Fixes Stack Overview links (#12025)
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#12026 [7.x][DOCS] Fixes Stack Overview links (#12025)
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#12030 [7.5][DOCS] Fixes Stack Overview links (#12025)
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#12029 [7.6][DOCS] Fixes Stack Overview links (#12025)
  docs/gs-index.asciidoc
  docs/static/docker.asciidoc
  docs/static/getting-started-with-logstash.asciidoc
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
  docs/static/setup/setting-up-xpack.asciidoc
Labels: backport

#12033 [Doc]Release notes for 7.8
  docs/static/releasenotes.asciidoc
Labels: docs, work in progress

#12038 dynamically get the plugin id instead of hardcoding it in the generated classes
  logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
  logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
  logstash-core/src/test/java/org/logstash/config/ir/IRHelpers.java
  logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline1.conf
  logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline2.conf
Labels: performance regression

#11783 support Env+Keystore substitutions in password-type plugin options (7.x backport)
  logstash-core/lib/logstash/util/substitution_variables.rb
  logstash-core/spec/logstash/config/mixin_spec.rb
Labels: v7.8.0

#11990 Doc:Add info on using api keys for access
  docs/static/security/api-keys.asciidoc
Labels: docs

#12046 Doc:Add deprecation notice to legacy collection
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
Labels: docs
