Repository elastic/logstash, pull requests merged in 2020-12, with the labels that each got.

#12494 REE: gauge reload interval
  logstash-core/lib/logstash/pipeline.rb
Labels: bug

#12513 Fix error due to missing variable when listing gradle tasks
  build.gradle
Labels: bug

#12459 plugin: adds `:validate => :field_reference`
  docs/static/configuration.asciidoc
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/spec/logstash/config/mixin_spec.rb
  logstash-core/src/main/java/org/logstash/FieldReference.java
Labels: enhancement

#12521 plugin: adds `:validate => :field_reference` (7.x backport)
  docs/static/configuration.asciidoc
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/spec/logstash/config/mixin_spec.rb
  logstash-core/src/main/java/org/logstash/FieldReference.java
Labels: backport, enhancement, v7.11.0

#12523 Silence missing javadocs in JDK 15
  build.gradle
Labels: developer docs, java 15 support

#12524 Fix/move ingest converter tool from js to java
  tools/ingest-converter/build.gradle
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestAppend.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestConvert.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestConverter.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestDate.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestGeoIp.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestGrok.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestGsub.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestJson.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestLowercase.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestPipeline.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestRename.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/IngestSet.java
  tools/ingest-converter/src/main/java/org/logstash/ingest/JsUtil.java
  tools/ingest-converter/src/main/resources/ingest-append.js
  tools/ingest-converter/src/main/resources/ingest-convert.js
  tools/ingest-converter/src/main/resources/ingest-date.js
  tools/ingest-converter/src/main/resources/ingest-geoip.js
  tools/ingest-converter/src/main/resources/ingest-grok.js
  tools/ingest-converter/src/main/resources/ingest-gsub.js
  tools/ingest-converter/src/main/resources/ingest-json.js
  tools/ingest-converter/src/main/resources/ingest-lowercase.js
  tools/ingest-converter/src/main/resources/ingest-pipeline.js
  tools/ingest-converter/src/main/resources/ingest-rename.js
  tools/ingest-converter/src/main/resources/ingest-set.js
  tools/ingest-converter/src/main/resources/ingest-shared.js
Labels: java 15 support
