Repository elastic/logstash, pull requests merged in 2020-10, with the labels that each got.

#12302 Docker Build: Add ability to detect/set build architecture
  docker/Makefile
  docker/templates/Dockerfile.j2
  qa/docker/shared_examples/image_metadata.rb
  qa/docker/spec/spec_helper.rb
Labels: enhancement

#12308 ECS Compatibility - backport 7x
  docker/data/logstash/env2yaml/env2yaml.go
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/codecs/base.rb
  logstash-core/lib/logstash/config/config_ast.rb
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/inputs/base.rb
  logstash-core/lib/logstash/outputs/base.rb
  logstash-core/lib/logstash/pipeline.rb
  logstash-core/lib/logstash/plugin.rb
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/config/mixin_spec.rb
  logstash-core/spec/logstash/execution_context_factory_spec.rb
  logstash-core/spec/logstash/execution_context_spec.rb
  logstash-core/spec/logstash/inputs/base_spec.rb
  logstash-core/spec/logstash/outputs/base_spec.rb
  logstash-core/spec/logstash/plugin_spec.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/RubyUtil.java
  logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/OutputStrategyExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/PluginFactory.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/RubyIntegration.java
  logstash-core/src/main/java/org/logstash/execution/Engine.java
  logstash-core/src/main/java/org/logstash/execution/ExecutionContextExt.java
  logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
  logstash-core/src/main/java/org/logstash/plugins/factory/ContextualizerExt.java
  logstash-core/src/main/java/org/logstash/plugins/factory/ExecutionContextFactoryExt.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
  logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
  logstash-core/src/test/java/org/logstash/config/ir/compiler/PluginFactoryTest.java
  logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java
  logstash-core/src/test/java/org/logstash/plugins/factory/PluginFactoryExtTest.java
Labels: 7.10.0, backport, enhancement

#12314 Remove redundant shouldRunAfter
  build.gradle
Labels: build

#12304 Write DLQ entries to temp file first
  config/logstash.yml
  config/pipelines.yml
  docker/data/logstash/env2yaml/env2yaml.go
  docs/static/dead-letter-queues.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/main/java/org/logstash/common/io/RecordIOReader.java
  logstash-core/src/main/java/org/logstash/common/io/RecordIOWriter.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/test/java/org/logstash/common/DeadLetterQueueFactoryTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
  logstash-core/src/test/java/org/logstash/common/io/RecordIOReaderTest.java
  qa/integration/build.gradle
  qa/integration/specs/dlq_spec.rb
  qa/integration/specs/spec_helper.rb
Labels: bug

#12335 Handle Windows delete pending files
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
Labels: bug

#12340 Doc: Clarify use of queue max bytes setting
  docs/static/management/centralized-pipelines.asciidoc
Labels: docs

#12341 Doc: Clarify use of queue max bytes setting
  docs/static/management/centralized-pipelines.asciidoc
Labels: docs

#12307 stop inputs upon a worker error before terminating the pipeline
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: bug, v8.0.0

#12336 [7.9 clean backport of #12307] stop inputs upon a worker error before terminating the pipeline
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: v7.9.3

#12339 [7.10 clean backport of #12307] stop inputs upon a worker error before terminating the pipeline
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: v7.10.0

#12342 [7.x clean backport of #12307] stop inputs upon a worker error before terminating the pipeline
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: v7.11.0

#12338 [7.10 backport] Handle Windows delete pending files
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
Labels: v7.10.0

#12350 [doc] Add note to Logstash repo install
  docs/static/getting-started-with-logstash.asciidoc
Labels: docs

#12386 [7x backport] Update jrjackson and databind versions
  versions.yml
Labels: v7.11.0

#12388 document system indices api privilege
  docs/static/settings/configuration-management-settings.asciidoc
Labels: docs

#12391 document system indices api privilege
  docs/static/security/logstash.asciidoc
Labels: docs

#12392 [7.10 backport] document system indices api privilege
  docs/static/security/logstash.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
Labels: backport, v7.10.0

#12393 [7x backport] document system indices api privilege
  docs/static/security/logstash.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
Labels: backport

#12400 [7x backport][Doc]Move logstash-to-cloud info for increased visibility
  docs/index.asciidoc
  docs/static/ls-to-cloud.asciidoc
  docs/static/modules.asciidoc
Labels: backport, docs, v7.11.0

#12401 [Backport][Doc]Relocate logstash-to-cloud topic for increased visibility
  docs/index.asciidoc
  docs/static/ls-to-cloud.asciidoc
  docs/static/modules.asciidoc
Labels: backport, docs, v7.10.0
