Repository elastic/logstash, pull requests merged in 2021-02, with the labels that each got.

#12626 use correct headers api for redirects in plugin manager http client
  lib/pluginmanager/utils/http_client.rb
  spec/unit/plugin_manager/utils/http_client_spec.rb
Labels: plugin manager, test failure

#12573 Create SECURITY.md
  SECURITY.md
Labels: developer docs

#12628 Backport PR #12626 to 7.x: use correct headers api for redirects in plugin manager http client
  lib/pluginmanager/utils/http_client.rb
  spec/unit/plugin_manager/utils/http_client_spec.rb
Labels: backport, v7.12.0

#12616 [7.x] enable agent to stop pipeline by pipeline_id (#12582)
  logstash-core/lib/logstash/agent.rb
  logstash-core/spec/logstash/agent_spec.rb
Labels: backport, v7.12.0

#12629 Backport PR #12626 to 7.11: use correct headers api for redirects in plugin manager http client
  lib/pluginmanager/utils/http_client.rb
  spec/unit/plugin_manager/utils/http_client_spec.rb
Labels: backport, v7.11.0

#12639 [7.x] remove CMS from jvm options in java 14 (#12638)
  config/jvm.options
  docs/static/jvm.asciidoc
Labels: 7.11.0, backport

#12640 [7.x] Fix showing deprecation warning of command line flags (#12592)
  logstash-core/lib/logstash/deprecation_message.rb
  logstash-core/lib/logstash/patches/clamp.rb
  logstash-core/lib/logstash/runner.rb
Labels: v7.11.0

#12586 Improve integrationTests task checking local ES fingerprint before full download
  build.gradle
Labels: build, enhancement

#12648 Doc: Add kafka confluent support to release notes
  docs/static/releasenotes.asciidoc
Labels: 7.11.0, docs

#12647 Forward port of release notes to 7.x (#12596)
  docs/static/releasenotes.asciidoc
Labels: docs

#12652 bump version to 7.11.1
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: v7.11.1

#12653 bump version to 6.8.15
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: v6.8.15

#12444 Separate "not terminated" state in "loading" and "running"
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/support/matchers.rb
Labels: bug

#12667 [backport]Separate "not terminated" pipeline state into "running" and "loading".
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/support/matchers.rb
Labels: backport, v7.12.0

#12670 Backport PR to 7.x of #12571
  logstash-core/lib/logstash/agent.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
  x-pack/spec/monitoring/schemas/monitoring_document_schema.json
Labels: backport, v7.12.0

#12660 bump lock file for 7.11.1
  Gemfile.jruby-2.5.lock.release
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/racc-NOTICE.txt
Labels: v7.11.2

#12680 Make integration test fail if 'offline' tool can't be compiled
  qa/integration/specs/cli/install_spec.rb
Labels: backport, v7.12.0

#12675 Geoip database service
  logstash-core/logstash-core.gemspec
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/down-NOTICE.txt
  x-pack/build.gradle
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/normal_resp.json
  x-pack/spec/filters/geoip/fixtures/sample.gz
  x-pack/spec/filters/geoip/test_helper.rb
Labels: v7.13.0

#12691 Doc: Forwardport Release notes for 7.11.1 to 7.x
  docs/static/releasenotes.asciidoc
Labels: backport, docs

#12693 update jdk to 11.0.10+9
  versions.yml
Labels: Java 11 Support

#12692 cleanup bundler exclusions during jruby unpacking
  rubyUtils.gradle
Labels: bundler, code cleanup
