Repository elastic/logstash, pull requests merged in 2021-08, with the labels that each got.

#13117 Bump 6.8.19
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: status:approved

#13116 Bump 7.14.1
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#13111 Release notes for 6.8.18
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13089 Release notes for 7.14.0
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13098 Release notes draft for 8.0.0-alpha1
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13124 Backport Docs: fix java filter unit test link
  docs/static/java-filter.asciidoc
Labels: docs, backport, status:approved

#13123 Backport Docs: fix java filter unit test link
  docs/static/java-filter.asciidoc
Labels: docs, backport, status:approved

#13126 Added faraday-* and ruby2_keywords notices to licences list
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/faraday-em_http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-em_synchrony-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-excon-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-httpclient-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-net_http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-net_http_persistent-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-patron-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-rack-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/ruby2_keywords-NOTICE.txt
Labels: status:approved

#13128 [backport 7.x] Added faraday-* and ruby2_keywords notices to licences list (#13126)
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/faraday-em_http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-em_synchrony-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-excon-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-httpclient-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-net_http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-net_http_persistent-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-patron-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/faraday-rack-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/ruby2_keywords-NOTICE.txt
Labels: backport, status:approved, v7.15.0

#13130 Doc: Add breaking changes to breaking changes page
  docs/static/breaking-changes.asciidoc
Labels: docs, status:approved

#13133 Doc: Forwardport release notes for 7.14.0 to 7.x branch
  docs/static/releasenotes.asciidoc
Labels: docs, status:needs-review

#13129 Update Snakeyaml version to 1.29
  build.gradle
  logstash-core/benchmarks/build.gradle
  logstash-core/build.gradle
  rubyUtils.gradle
  tools/benchmark-cli/build.gradle
  tools/dependencies-report/build.gradle
  tools/ingest-converter/build.gradle
Labels: status:approved

#13125 Deps: bump lock for 7.15.0
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#13134 [backport 7.x] Update Snakeyaml version to 1.29 (#13129)
  build.gradle
  logstash-core/benchmarks/build.gradle
  logstash-core/build.gradle
  rubyUtils.gradle
  tools/benchmark-cli/build.gradle
  tools/dependencies-report/build.gradle
  tools/ingest-converter/build.gradle
Labels: backport, status:needs-review

#13135 [backport 7.15] Update Snakeyaml version to 1.29 (#13129)
  build.gradle
  logstash-core/benchmarks/build.gradle
  logstash-core/build.gradle
  rubyUtils.gradle
  tools/benchmark-cli/build.gradle
  tools/dependencies-report/build.gradle
  tools/ingest-converter/build.gradle
Labels: backport, status:needs-review

#13132 Doc: Add aarch64 support to release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#13137 Doc: Forwardport aarch64 support note (#13132) to 7.x release notes
  docs/static/releasenotes.asciidoc
Labels: docs, backport, status:needs-review

#13131 Doc: Move shared region tags for breaking changes to 8.0.0 content
  docs/static/breaking-changes.asciidoc
Labels: docs, status:approved

#13015 Bundler: freeze lockfile on run, and "normalize" platform on plugin changes
  ci/acceptance_tests.sh
  docs/static/running-logstash-command-line.asciidoc
  lib/bootstrap/bundler.rb
  lib/bootstrap/environment.rb
  lib/pluginmanager/bundler/logstash_injector.rb
  lib/pluginmanager/install.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/src/main/java/org/logstash/Logstash.java
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
  qa/acceptance/spec/shared_examples/installed.rb
  qa/acceptance/spec/shared_examples/installed_with_jdk.rb
  qa/acceptance/spec/shared_examples/running.rb
  qa/acceptance/spec/shared_examples/updated.rb
  qa/acceptance/spec/spec_helper.rb
  qa/rspec/commands.rb
  qa/rspec/commands/system_helpers.rb
  qa/rspec/commands/ubuntu.rb
  qa/rspec/commands/ubuntu/ubuntu-1604.rb
  qa/vagrant/command.rb
  qa/vagrant/helpers.rb
  rubyUtils.gradle
Labels: status:approved

#13144 Backport PR #13005 to 7.x: update fpm to allow pkg creation on jdk11+…
  Gemfile.template
  logstash-core/logstash-core.gemspec
  qa/integration/patch/childprocess-modern-java.rb
  qa/integration/services/logstash_service.rb
  rakelib/artifacts.rake
  rakelib/childprocess_patch.rb
Labels: backport, status:needs-review, v7.16.0

#13145 Backport PR #13005 to 7.15 update fpm to allow pkg creation on jdk11+…
  Gemfile.jruby-2.5.lock.release
  Gemfile.template
  logstash-core/logstash-core.gemspec
  qa/integration/patch/childprocess-modern-java.rb
  qa/integration/services/logstash_service.rb
  rakelib/artifacts.rake
  rakelib/childprocess_patch.rb
Labels: backport, status:needs-review, v7.15.0

#13141 Backport PR #13015 to 7.15: Bundler: freeze lockfile on run, and "nor…
  Gemfile.jruby-2.5.lock.release
  build.gradle
  ci/acceptance_tests.sh
  docs/static/running-logstash-command-line.asciidoc
  lib/bootstrap/bundler.rb
  lib/bootstrap/environment.rb
  lib/pluginmanager/bundler/logstash_injector.rb
  lib/pluginmanager/install.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/src/main/java/org/logstash/Logstash.java
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
  qa/acceptance/spec/shared_examples/installed.rb
  qa/acceptance/spec/shared_examples/installed_with_jdk.rb
  qa/acceptance/spec/shared_examples/running.rb
  qa/acceptance/spec/shared_examples/updated.rb
  qa/acceptance/spec/spec_helper.rb
  qa/rspec/commands.rb
  qa/rspec/commands/system_helpers.rb
  qa/rspec/commands/ubuntu.rb
  qa/rspec/commands/ubuntu/ubuntu-1604.rb
  qa/vagrant/command.rb
  qa/vagrant/helpers.rb
  rubyUtils.gradle
Labels: backport, status:approved, v7.15.0

#13140 Backport PR #13015 to 7.x: Bundler: freeze lockfile on run, and "norm…
  build.gradle
  ci/acceptance_tests.sh
  docs/static/running-logstash-command-line.asciidoc
  lib/bootstrap/bundler.rb
  lib/bootstrap/environment.rb
  lib/pluginmanager/bundler/logstash_injector.rb
  lib/pluginmanager/install.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/src/main/java/org/logstash/Logstash.java
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
  qa/acceptance/spec/shared_examples/installed.rb
  qa/acceptance/spec/shared_examples/installed_with_jdk.rb
  qa/acceptance/spec/shared_examples/running.rb
  qa/acceptance/spec/shared_examples/updated.rb
  qa/acceptance/spec/spec_helper.rb
  qa/rspec/commands.rb
  qa/rspec/commands/system_helpers.rb
  qa/rspec/commands/ubuntu.rb
  qa/rspec/commands/ubuntu/ubuntu-1604.rb
  qa/vagrant/command.rb
  qa/vagrant/helpers.rb
  rubyUtils.gradle
Labels: backport, status:approved, v7.16.0

#13146 Remove dependency:bundler task
  rakelib/dependency.rake
  rakelib/vendor.rake
Labels: status:needs-review

#13148 Backport PR #13146 to 7.15: Remove dependency:bundler task
  rakelib/dependency.rake
  rakelib/vendor.rake
Labels: backport, v7.15.0

#13149 Update releases list
  ci/logstash_releases.json
  qa/integration/services/elasticsearch_setup.sh
Labels: status:approved

#13160 Doc: Forwardport Aarch64 support to 7.14.0 release notes to 7.15
  docs/static/releasenotes.asciidoc
Labels: docs, backport, status:needs-review

#13161 Doc: Add placeholder for 7.15.0 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#13036 Refactor: avoid global mutex on ecs_compatibility
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
Labels: status:approved

#13163 Backport to 7.x: Refactor: avoid global mutex on ecs_compatibility (#13036)
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
Labels: backport

#13162 Bump plugins for 7.14.1 release
  Gemfile.jruby-2.5.lock.release
Labels: status:approved, release, v7.14.1

#13113 fix geoip `database` path got overwritten
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: status:approved, geoip, v7.13.5

#13164 Test: better logging reconfiguration asserts
  qa/integration/specs/monitoring_api_spec.rb
Labels: status:needs-review

#13169 [7.x] Test: improve monitoring api logging asserts (#13164)
  qa/integration/specs/monitoring_api_spec.rb
Labels: backport, status:approved

#13170 [7.15] Test: improve monitoring api logging asserts (#13164)
  qa/integration/specs/monitoring_api_spec.rb
Labels: backport, status:approved

#13178 add the missing logstash config supported by env2yaml for docker
  docker/data/logstash/env2yaml/env2yaml.go
Labels: status:approved

#13180 [7.x] add the missing logstash config supported by env2yaml for docker (#13178)
  docker/data/logstash/env2yaml/env2yaml.go
Labels: backport, v7.16.0

#13185 Update bundled JDK to 11.0.12+7
  versions.yml
Labels: Java 11 Support

#13186 [backport 7.x]Update bundled JDK to 11.0.12+7 #13185
  versions.yml
Labels: backport
