Repository elastic/logstash, pull requests merged in 2021-12, with the labels that each got.

#13454 Backport PR #13447 to 7.16: Fix: patch Puma around a JRuby ARM64 bug
  logstash-core/lib/logstash/patches/puma.rb
Labels: backport, status:approved, v7.16.1

#13468 bump jruby to 9.2.20.1
  rubyUtils.gradle
  versions.yml
Labels: JRuby 9K, status:needs-review

#13471 Use $BUILD_JAVA_HOME to control JVMs used with acceptance tests
  ci/acceptance_tests.sh
  ci/docker_acceptance_tests.sh
Labels: status:needs-review

#13436 Release notes for 7.16.0
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13476 Release: bump version to 7.16.1
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#13474 Backport of #13471 to 8.0: Use $BUILD_JAVA_HOME to control JVMs used …
  ci/acceptance_tests.sh
  ci/docker_acceptance_tests.sh
Labels: backport, v8.0.0, status:approved

#13481 Fix: delegating from deprecated setting
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
Labels: bug, status:approved, v7.16.1

#13484 Backport PR #13481 to 7.16: Fix: delegating from deprecated setting
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
Labels: backport, v7.16.1

#13486 Backport PR #13481 to 8.0: Fix: delegating from deprecated setting
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
Labels: backport, v8.0.0, status:needs-review

#13483 Deps: bump lock file for 7.16.1
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#13442 Update logstash docker to use ubuntu 20.04 base image
  docker/templates/Dockerfile.j2
  qa/docker/shared_examples/container.rb
  qa/docker/spec/full/container_spec.rb
  qa/docker/spec/oss/container_spec.rb
Labels: status:approved

#13489 bump gradle to 7.3.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build, status:work-in-progress

#13494 bump log4j version to 2.15.0
  logstash-core/build.gradle
Labels: status:work-in-progress

#13496 Backport #13494 to 7.16. bump log4j version to 2.15.0
  logstash-core/build.gradle
Labels: backport, status:approved, v7.16.1

#13500 Update log4j dependencies
  NOTICE.TXT
  logstash-core/build.gradle
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-api-2.15.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-core-2.15.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-slf4j-impl-2.15.0-NOTICE.txt
Labels: status:changes-requested, v6.8.21

#13495 Backport #13494 to 8.0. bump log4j version to 2.15.0
  logstash-core/build.gradle
Labels: backport, v8.0.0, status:approved

#13490 Backport #13442 to 8.0. Update logstash docker to use ubuntu 20.04 ba…
  docker/templates/Dockerfile.j2
  qa/docker/shared_examples/container.rb
  qa/docker/spec/full/container_spec.rb
  qa/docker/spec/oss/container_spec.rb
Labels: backport, v8.0.0, status:approved

#13507 bump version to 6.8.22
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: v6.8.22

#13502 Release notes for 6.8.21
  docs/static/releasenotes.asciidoc
Labels: docs, status:approved, release, v6.8.21

#13503 Release notes for 7.16.1
  docs/static/releasenotes.asciidoc
Labels: docs, status:approved, release, v7.16.1

#13508 bump to version 7.16.2
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved, v7.16.2

#13513 Doc: Add filter known issue to 7.16.1 release notes
  docs/static/releasenotes.asciidoc
Labels: docs, status:approved

#13519 Doc: Add filter known issue to 7.15.2 release notes
  docs/static/releasenotes.asciidoc
Labels: docs, status:work-in-progress

#13518 Bump log4j version to 2.16.0 per CVE-2021-45046
  logstash-core/build.gradle
Labels: status:needs-triage

#13509 update readme wrt 6.8.22
  README.md
Labels: status:approved, v6.8.22

#13482 CI: update releases after 7.16.0 & 7.16.1
  ci/logstash_releases.json
Labels: status:approved

#13521 Backport PR #13518 to 7.16: Bump log4j version to 2.16.0 per CVE-2021-45046
  logstash-core/build.gradle
Labels: backport, status:approved, v7.16.2

#13520 Backport PR #13518 to 8.0: Bump log4j version to 2.16.0 per CVE-2021-45046
  logstash-core/build.gradle
Labels: backport, v8.0.0, status:approved

#13527 Chore: bump version to 7.17.0 (snapshot)
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#13529 Backport #13442 to 7.17. Update logstash docker to use ubuntu 20.04 b…
  docker/templates/Dockerfile.j2
  qa/docker/shared_examples/container.rb
  qa/docker/spec/full/container_spec.rb
  qa/docker/spec/oss/container_spec.rb
Labels: backport, status:needs-review, v7.17.0

#13537 Doc: remove PQ on input for Output Isolator
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, status:needs-review

#13535 Doc: Add anchor to bundled jdk info
  docs/static/jvm.asciidoc
Labels: docs

#13538 Doc: remove PQ on input for Output Isolator 8.0
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13539 Doc: remove PQ on input for Output Isolator 7.17
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13540 Doc: remove PQ on input for Output Isolator 7.16
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13541 Doc: Add anchor to bundled jdk info 8.0
  docs/static/jvm.asciidoc
Labels: docs, backport

#13542 Doc: Add anchor to bundled jdk info 7.17
  docs/static/jvm.asciidoc
Labels: docs, backport

#13543 Doc: Add anchor to bundled jdk info 7.16
  docs/static/jvm.asciidoc
Labels: docs, backport

#13544 Bump log4j dependency to 2.17.0
  logstash-core/build.gradle
Labels: status:needs-review

#13546 Backport PR #13544 to 8.0: Bump log4j dependency to 2.17.0
  logstash-core/build.gradle
Labels: backport, v8.0.0, status:needs-review

#13547 Backport PR #13544 to 7.17: Bump log4j dependency to 2.17.0
  logstash-core/build.gradle
Labels: backport, status:needs-review, v7.17.0

#13548 Backport PR #13544 to 7.16: Bump log4j dependency to 2.17.0
  logstash-core/build.gradle
Labels: backport, status:needs-review, v7.16.2

#13545 bump Log4j dependency to 2.17.0 on 6.8
  NOTICE.TXT
  logstash-core/build.gradle
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-api-2.17.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-core-2.17.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-slf4j-impl-2.17.0-NOTICE.txt
Labels: status:approved

#13550 update lock file for 7.17.0
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#13549 update lock file for 7.16.2
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#13551 Release notes draft for 7.16.2
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13553 bump lock file for 6.8.22
  Gemfile.jruby-2.5.lock.release
Labels: status:changes-requested

#13555 Release notes for 6.8.22
  docs/static/releasenotes.asciidoc
Labels: v6.8.22

#13557 update lock file for 8.0.0
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#13564 Bump log4j dependency to 2.17.1
  logstash-core/build.gradle
Labels: status:needs-review

#13565 [8.0] Bump log4j dependency to 2.17.1 (#13564)
  logstash-core/build.gradle
Labels: backport, status:approved

#13566 [7.17] Bump log4j dependency to 2.17.1 (#13564)
  logstash-core/build.gradle
Labels: backport, status:approved

#13567 [7.16] Bump log4j dependency to 2.17.1 (#13564)
  logstash-core/build.gradle
Labels: backport, status:approved

#13568 [6.8] Bump log4j dependency to 2.17.1
  NOTICE.TXT
  logstash-core/build.gradle
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-api-2.17.1-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-core-2.17.1-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/org.apache.logging.log4j!log4j-slf4j-impl-2.17.1-NOTICE.txt
Labels: status:approved
