Repository elastic/logstash, pull requests merged in 2021-03, with the labels that each got.

#12700 Backport PR #12693 to 7.x: update jdk to 11.0.10+9
  versions.yml
Labels: backport, v7.13.0

#12701 Backport PR #12693 to 7.12: update jdk to 11.0.10+9
  versions.yml
Labels: backport, v7.12.0

#12702 Backport PR #12692 to 7.x: cleanup bundler exclusions during jruby unpacking
  rubyUtils.gradle
Labels: backport, v7.13.0

#12710 [backport 7.x] Removed OpenJDK15 in CI matrix testing #12649
  .ci/matrix-runtime-javas.yml
Labels: backport, v7.13.0

#12712 Temporarly silenced an x-pack monitoring test, waiting to be fixed the root cause
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: test failure

#12716 [backport #12444 7.11] Separate "not terminated" pipeline state into "running" and "loading".
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/pipelines_registry.rb
  logstash-core/spec/logstash/pipelines_registry_spec.rb
  logstash-core/spec/support/matchers.rb
Labels: backport, v7.11.2

#12699 update jruby to 9.2.16.0
  logstash-core/spec/logstash/plugin_spec.rb
  logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
  rubyUtils.gradle
  versions.yml
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
Labels: JRuby 9K

#12718 [backport #12712 7.x]Temporarly silenced an x-pack monitoring test
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: backport, test failure, v7.13.0

#12721 Backport PR #12699 to 7.x: update jruby to 9.2.16.0
  logstash-core/spec/logstash/plugin_spec.rb
  logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
  rubyUtils.gradle
  versions.yml
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
Labels: backport, v7.13.0

#12723 Backport PR #12720 to 7.x: Deps: update slf4j to latest 1.7.30
  logstash-core/build.gradle
Labels: backport, v7.13.0

#12729 Backport PR #12728 to 7.x: [Build] Fix version script when VERSION_QU…
  docker/bin/elastic-version
Labels: backport, v7.13.0

#12719 Docs: Implement docs-root for shared files
  docs/index.asciidoc
Labels: docs

#12714 Doc: Add unix command for running basic pipeline
  docs/static/getting-started-with-logstash.asciidoc
Labels: docs

#12731 Doc: Replace relative paths with docs-root attributes for 7.x
  docs/index.asciidoc
Labels: backport, docs

#12733 Doc: Replace relative paths with docs-root attributes for 7.11
  docs/index.asciidoc
Labels: backport, docs

#12727 change domain and endpoint of GeoIP database service
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/normal_resp.json
  x-pack/spec/filters/geoip/test_helper.rb
Labels: v7.13.0

#12738 Backport PR #12736 to 7.x: Fix Benchmarking tool
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LsMetricsMonitor.java
  tools/benchmark-cli/src/test/java/org/logstash/benchmark/cli/LsMetricsMonitorTest.java
  tools/benchmark-cli/src/test/resources/org/logstash/benchmark/cli/metrics.json
Labels: backport, v7.13.0

#12717 [backport #12571 7.11]Fix Logstash pipelines management in case of slow loading pipelines
  logstash-core/lib/logstash/agent.rb
  x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
  x-pack/spec/monitoring/schemas/monitoring_document_schema.json
Labels: backport, v7.11.3

#12724 Deps: update log4j2 to latest and ship log4j 1.2 bridge
  logstash-core/build.gradle
Labels: logging improvements

#12744 Backport PR #12724 to 7.x: Deps: update log4j2 to latest and ship log4j 1.2 bridge
  logstash-core/build.gradle
Labels: backport, v7.13.0

#12730 Update logstash.asciidoc
  docs/static/security/logstash.asciidoc
Labels: docs

#12750 Backport PR #12749 to 7.x: internal-monitoring: use configured ssl verification mode
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Labels: backport, v7.13.0

#12751 Backport PR #12749 to 7.12: internal-monitoring: use configured ssl verification mode
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Labels: backport, v7.12.0

#12755 Doc: Change protocol to https for 7.11
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12753 Doc: Change protocol to https for 7.x
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12754 Doc: Change protocol to https for 7.12
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12752 Backport PR #12749 to 6.8: internal-monitoring: use configured ssl verification mode
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Labels: backport, v6.8.15

#12662 Internal: Add release notes section to pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#12762 Doc:Add placeholder and coming tag for 7.12.0 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#12766 Remove 'coming' tag from 6.8.15 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#12767 Doc: Remove stray tag in release notes header
  docs/static/releasenotes.asciidoc
Labels: docs

#12768 Doc: Rework security update in 7.12.0 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#12769 Doc: Rework security update in 6.8.15 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#12742 Forwardport release notes for 7.11.2 to 7.x branch
  docs/static/releasenotes.asciidoc
Labels: backport, docs

#12763 Build: avoid leaking memory from generate_plugins_version
  rakelib/plugins_docs_dependencies.rake
Labels: build

#12770 Forwardport release notes for 7.12.0 to 7.x branch
  docs/static/releasenotes.asciidoc
Labels: backport, docs

#12772 Backport PR #12763 to 7.x: Build: avoid leaking memory from generate_plugins_version
  rakelib/plugins_docs_dependencies.rake
Labels: backport, v7.13.0

#12773 Backport PR #12763 to 7.12: Build: avoid leaking memory from generate_plugins_version
  rakelib/plugins_docs_dependencies.rake
Labels: backport, v7.12.1

#12777 [7.x] Geoip database service (#12675) | GeoIP clean up database after new download (#12689) | fix broken test case of term of service (#12715) | change domain and endpoint of GeoIP database service (#12727) | GeoIP database add license file
  logstash-core/logstash-core.gemspec
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/down-NOTICE.txt
  x-pack/build.gradle
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/normal_resp.json
  x-pack/spec/filters/geoip/fixtures/sample.tgz
  x-pack/spec/filters/geoip/test_helper.rb
Labels: v7.13.0

#12778 Revert commit for further testing
  docs/static/keystore.asciidoc
Labels: docs

#12782 Set correct permissions for /usr/share/logstash on pkg installs
  pkg/centos/after-install.sh
  pkg/debian/after-install.sh
  pkg/ubuntu/after-install.sh
Labels: bug, easyreview

#12788 Backport PR #12782 to 7.x: Set correct permissions for /usr/share/logstash on pkg installs
  pkg/centos/after-install.sh
  pkg/debian/after-install.sh
  pkg/ubuntu/after-install.sh
Labels: backport, v7.13.0

#12789 Backport PR #12782 to 7.12: Set correct permissions for /usr/share/logstash on pkg installs
  pkg/centos/after-install.sh
  pkg/debian/after-install.sh
  pkg/ubuntu/after-install.sh
Labels: backport, v7.12.1
