Repository elastic/logstash, pull requests merged in 2021-05, with the labels that each got.

#12847 Change :logstash-integration-tests:integrationTests to depends on copyES
  build.gradle
Labels: build, status:approved

#12868 [backport 7.x] Change Gradle's :logstash-integration-tests:integrationTests task to depends on copyES (#12847)
  build.gradle
Labels: backport, status:approved, v7.14.0

#12863 change download path for geoip plugin
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: status:approved

#12870 [7.13] revert geoip plugin to 6.0.5
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#9702 Support for UTF-16 and other multi-byte-character logfiles
  logstash-core/lib/logstash/config/string_escape.rb
  logstash-core/spec/logstash/config/string_escape_spec.rb
Labels: easyreview, revisit, status:changes-requested

#12872 Fix ES HOW integration tests on `master`
  qa/integration/fixtures/es_output_how_spec.yml
Labels: status:needs-review

#12871 fix DLQ integration tests
  qa/integration/fixtures/dlq_spec.yml
  qa/integration/services/elasticsearch_setup.sh
  qa/integration/specs/dlq_spec.rb
Labels: status:approved

#12874 [Backport 7.x]Update elasticsearch gem dependency requirements (#11258)
  logstash-core/logstash-core.gemspec
Labels: status:approved

#12876 [7.13] change download path for geoip plugin (#12863)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: backport, status:needs-review, v7.13.0

#12875 [7.x] change download path for geoip plugin (#12863)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: backport, status:needs-review

#12881 Update bundled JDK to 11.0.11+9
  versions.yml
Labels: Java 11 Support, status:needs-review

#12879 Doc: Update contributing steps and guidelines
  docs/index.asciidoc
  docs/static/contrib-acceptance.asciidoc
  docs/static/contribute-core.asciidoc
  docs/static/contributing-java-plugin.asciidoc
  docs/static/contributing-patch.asciidoc
  docs/static/contributing-to-logstash.asciidoc
  docs/static/doc-for-plugin.asciidoc
  docs/static/include/pluginbody.asciidoc
  docs/static/listing-a-plugin.asciidoc
  docs/static/plugin-generator.asciidoc
  docs/static/plugin-manager.asciidoc
  docs/static/submitting-a-plugin.asciidoc
Labels: docs, status:approved

#12885 [7.13] update ES output plugin to latest
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#12890 [7.13] Geoip use cc indefinitely (#12888)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
Labels: backport, status:approved, v7.13.0

#12889 [7.x] Geoip use cc indefinitely (#12888)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
Labels: backport, status:approved, v7.13.0

#12893 Comment out config examples pending rework (backport to 7.13)
  docs/static/fb-ls-kafka-example.asciidoc
  docs/static/filebeat-modules.asciidoc
Labels: backport, docs, status:needs-review

#12896 Doc: Update contributing steps and guidelines (backport to 7.13)
  docs/index.asciidoc
  docs/static/contrib-acceptance.asciidoc
  docs/static/contribute-core.asciidoc
  docs/static/contributing-java-plugin.asciidoc
  docs/static/contributing-patch.asciidoc
  docs/static/contributing-to-logstash.asciidoc
  docs/static/doc-for-plugin.asciidoc
  docs/static/include/pluginbody.asciidoc
  docs/static/listing-a-plugin.asciidoc
  docs/static/plugin-generator.asciidoc
  docs/static/plugin-manager.asciidoc
  docs/static/submitting-a-plugin.asciidoc
Labels: backport, docs

#12897 Doc: Update contributing steps and guidelines (backport to 7.12)
  docs/index.asciidoc
  docs/static/contrib-acceptance.asciidoc
  docs/static/contribute-core.asciidoc
  docs/static/contributing-java-plugin.asciidoc
  docs/static/contributing-patch.asciidoc
  docs/static/contributing-to-logstash.asciidoc
  docs/static/doc-for-plugin.asciidoc
  docs/static/include/pluginbody.asciidoc
  docs/static/listing-a-plugin.asciidoc
  docs/static/plugin-generator.asciidoc
  docs/static/plugin-manager.asciidoc
  docs/static/submitting-a-plugin.asciidoc
Labels: backport, docs

#12891 [Build] On aarch64 docker build, install `noarch` version of bind-license first
  docker/templates/Dockerfile.j2
Labels: status:approved

#12901 [Backport 7.13][Build] On aarch64 docker build, install `noarch` vers…
  docker/templates/Dockerfile.j2
Labels: status:approved

#12902 fix ubi8 docker image creation by skipping yum clean metadata
  docker/templates/Dockerfile.j2
Labels: status:approved

#12904 Backport PR #12902 to 7.13: fix ubi8 docker image creation by skipping yum clean metadata
  docker/templates/Dockerfile.j2
Labels: backport, v7.13.0

#12905 Geoip disable database manager
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
Labels: status:approved

#12882 [backport 7.x]Update bundled JDK to 11.0.11+9 (#12881)
  versions.yml
Labels: backport, status:approved, v7.14.0

#12908 [Backport 7.12][Build] 12891 12902 7.12
  docker/templates/Dockerfile.j2
Labels: backport, v7.12.2

#12907 [7.13] Geoip disable database manager (#12905)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
Labels: backport, status:approved, v7.13.0

#12906 [7.x] Geoip disable database manager (#12905)
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
Labels: backport, status:approved, v7.13.0

#12911 pin geoip 7.1.2
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#12918 Pin JDK8 version in Docker to avoid KeyStore creation race condition
  docker/templates/Dockerfile.j2
Labels: blocker, bug, docker, status:changes-requested

#12922 Created release notes for v6.8.16
  docs/static/releasenotes.asciidoc
Labels: status:work-in-progress

#12924 Forward Port PR #12825 to 7.13:Update release notes for 7.12.1
  docs/static/releasenotes.asciidoc
Labels: 7.13.0, backport

#12843 Update release notes for 7.13.0
  docs/static/releasenotes.asciidoc
Labels: status:work-in-progress

#12926 Release: bump version to 6.8.17
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: status:needs-review

#12927 Release: bump version to 7.13.1
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#12925 Add logstash-integration-elastic_enterprise_search to plugins-metadata.json
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/elastic-workplace-search-NOTICE.txt
Labels: status:approved

#12883 [backport 7.13]Update bundled JDK to 11.0.11+9 (#12881)
  versions.yml
Labels: backport, status:approved, v7.13.1

#12932 Forwardport release notes for 7.13.0 to 7.x branch
  docs/static/releasenotes.asciidoc
Labels: docs, status:needs-review

#12936 Doc: Expand definition and fix typo for CLA
  docs/static/doc-for-plugin.asciidoc
Labels: docs, status:approved

#12938 Doc: Expand definition and fix typo
  docs/static/doc-for-plugin.asciidoc
Labels: backport, docs

#12935 Backport PR #12925 to 7.13: Add logstash-integration-elastic_enterpris…
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/elastic-workplace-search-NOTICE.txt
Labels: backport, status:approved, v7.13.1

#12934 Backport PR #12925 to 7.x: Add logstash-integration-elastic_enterpris…
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/elastic-workplace-search-NOTICE.txt
Labels: backport, status:approved, v7.14.0

#12941 turn off data streams in internal monitoring collection
  x-pack/lib/template.cfg.erb
Labels: monitoring, status:approved, test failure

#12942 bump lock file for 7.13.1
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#12943 Revert "Backport PR #12925 to 7.13: Add logstash-integration-elastic_…
  rakelib/plugins-metadata.json
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/elastic-workplace-search-NOTICE.txt
Labels: status:needs-review

#12949 Internal: Update messaging in release notes script
  tools/release/generate_release_notes.rb
Labels: docs, status:approved

#12950 Internal: Update messaging in release notes script
  tools/release/generate_release_notes.rb
Labels: backport, docs

#12951 Internal: Update messaging in release notes script
  tools/release/generate_release_notes.rb
Labels: backport, docs
