Repository elastic/logstash, pull requests merged in 2021-06, with the labels that each got.

#12945 Use the JVM specified in the CI matrix environment also to run spawned proccesses
  qa/integration/specs/cli/keystore_spec.rb
Labels: status:needs-review

#12953 [backport 7.x] #12945 Use the JVM specified in the CI matrix environment also to run spawned proccesses
  qa/integration/specs/cli/keystore_spec.rb
Labels: backport, status:approved

#12944 Add a template on how to create an issue when requesting to list a plugin in docs
  docs/static/listing-a-plugin.asciidoc
Labels: docs, enhancement, status:approved

#12946 Release notes for 7.13.1
  docs/static/releasenotes.asciidoc
Labels: status:approved

#12954 [backport 7.13] #12945 Use the JVM specified in the CI matrix environment also to run spawned proccesses
  qa/integration/specs/cli/keystore_spec.rb
Labels: backport, status:approved

#12957 Forward port release notes for 7.13.1
  docs/static/releasenotes.asciidoc
Labels: status:approved

#12841 Avoid hard-coded plugin alias definitions
  .gitignore
  build.gradle
  lib/pluginmanager/util.rb
  logstash-core/build.gradle
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml
  logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
  logstash-core/src/test/resources/org/logstash/plugins/AliasRegistry.yml
  spec/unit/plugin_manager/util_spec.rb
Labels: status:approved

#12952 Refactoring of JavaKeyStore.getKeyStorePassword method to simplify ifs conditions
  logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
Labels: status:approved

#12961 [backport 7.x]Refactoring of JavaKeyStore.getKeyStorePassword method to simplify if conditions (#12952)
  logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
Labels: backport, status:approved

#12962 Fix dependency on plugin_alias.yml during `rake artifacts:all`
  rakelib/test.rake
Labels: status:approved

#12963 [backport 7.x] Fix dependency on plugin_alias.yml during `rake artifacts:all` (#12962)
  rakelib/test.rake
Labels: backport, status:approved

#12857 bump devutils dependency to 2.x
  Gemfile.template
  logstash-core/spec/logstash/filters/base_spec.rb
  logstash-core/spec/support/helpers.rb
  x-pack/qa/integration/management/multiple_pipelines_spec.rb
Labels: code cleanup, status:approved, tests-infra

#12791 Deps: update JRuby to 9.2.18.0
  lib/bootstrap/bundler.rb
  rubyUtils.gradle
  versions.yml
Labels: JRuby 9K

#12976 Doc: Remove unused tagged regions
  docs/static/monitoring/monitoring-mb.asciidoc
Labels: docs

#12974 Test: handle a RGs warning from packing output
  qa/integration/specs/cli/prepare_offline_pack_spec.rb
Labels: status:approved

#12971 Backport PR #12791 to 7.x: Deps: update JRuby to 9.2.18.0
  lib/bootstrap/bundler.rb
  rubyUtils.gradle
  versions.yml
Labels: backport, status:approved, v7.14.0

#12975 Fix acceptance test when run artifact:deb
  rakelib/compile.rake
Labels: status:approved

#12977 Deps: update lock file for 7.13.2
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#12978 Update lock file for 7.13.2
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#12979 Doc: Remove unused tagged regions
  docs/static/monitoring/monitoring-mb.asciidoc
Labels: backport, docs

#12981 Release notes draft for 7.13.2
  docs/static/releasenotes.asciidoc
Labels: docs, status:approved, v7.13.2

#12982 Forwardport 7.13.2 release notes draft to 7.x
  docs/static/releasenotes.asciidoc
Labels: backport, docs, status:approved

#12964 Explicitate the type of log format in appender's names else it breaks…
  .gitignore
  config/log4j2.properties
  logstash-core/benchmarks/src/main/resources/log4j2-with-script.properties
  logstash-core/benchmarks/src/main/resources/log4j2-without-script.properties
  logstash-core/src/test/resources/log4j2-log-pipeline-test.properties
  qa/integration/build.gradle
  qa/integration/fixtures/persistent_queues/log4j2.properties
  qa/integration/specs/pipeline_log_spec.rb
Labels: status:approved

#12986 Update logstash_release.json after 7.3.12
  ci/logstash_releases.json
Labels: status:needs-review

#12967 Added test to cover the installation of aliased plugins
  build.gradle
  spec/unit/plugin_manager/install_spec.rb
Labels: status:approved

#12899 Doc: Add tip for checking for existing field
  docs/static/best-practice.asciidoc
Labels: docs, status:approved

#12987 Doc: Add tip for checking for existing field (backport to 7.x)
  docs/static/best-practice.asciidoc
Labels: backport, docs

#12988 Doc: Add tip for checking for existing field (backport to 7.13)
  docs/static/best-practice.asciidoc
Labels: backport, docs

#12965 Fix/log4j routing to avoid create spurious file
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingAppender.java
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingFilter.java
  qa/integration/build.gradle
  qa/integration/specs/pipeline_log_spec.rb
Labels: status:approved

#12990 [7.x] Deps: update JRuby to 9.2.19.0 (#12989)
  rubyUtils.gradle
  versions.yml
Labels: backport, status:approved

#12991 Fix Reflections stack traces when process yml files in classpath and …
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
Labels: status:approved

#12960 [backport 7.x] Avoid hard-coded plugin alias definitions (#12841)
  .gitignore
  build.gradle
  lib/pluginmanager/util.rb
  logstash-core/build.gradle
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml
  logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
  logstash-core/src/test/resources/org/logstash/plugins/AliasRegistry.yml
  spec/unit/plugin_manager/util_spec.rb
Labels: backport, status:approved

#12862 fix database manager with multiple pipelines
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/normal_resp.json
  x-pack/spec/filters/geoip/test_helper.rb
Labels: status:approved

#12995 [7.x] fix database manager with multiple pipelines (#12862)
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/normal_resp.json
  x-pack/spec/filters/geoip/test_helper.rb
Labels: backport, status:approved, v7.14.0

#12996 [backport 7.x] Fix acceptance test when run artifact:all (#12975)
  rakelib/compile.rake
Labels: backport, status:needs-review, v7.14.0

#12997 [backport 7.x] Explicitate the type of log format in appender's names (#12964)
  .gitignore
  config/log4j2.properties
  logstash-core/benchmarks/src/main/resources/log4j2-with-script.properties
  logstash-core/benchmarks/src/main/resources/log4j2-without-script.properties
  logstash-core/src/test/resources/log4j2-log-pipeline-test.properties
  qa/integration/build.gradle
  qa/integration/fixtures/persistent_queues/log4j2.properties
  qa/integration/specs/pipeline_log_spec.rb
Labels: backport, status:needs-review, v7.14.0

#12994 Update jinja2 dependency
  docker/requirements.txt
Labels: status:approved

#12998 [backport 7.x] Added test to cover the installation of aliased plugins (#12967)
  build.gradle
  spec/unit/plugin_manager/install_spec.rb
Labels: backport, status:needs-review, v7.14.0

#12861 Allow per-pipeline config of ECS Compatibility mode via Central Management
  logstash-core/lib/logstash/settings.rb
  x-pack/lib/config_management/elasticsearch_source.rb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
Labels: status:approved

#12999 [backport 7.x] Fix/log4j routing to avoid create spurious file (#12965)
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingAppender.java
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingFilter.java
  qa/integration/build.gradle
  qa/integration/specs/pipeline_log_spec.rb
Labels: backport, status:approved, v7.14.0

#13003 [backport 7.x] Fix Reflections stack traces when process yml files in ... (#12991)
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
Labels: backport, status:approved, v7.14.0

#13000 Use the OS separator to invoke gradlew from Rake script
  rakelib/compile.rake
Labels: bug, status:approved

#12948 Fix logstash.bat not setting exit code
  bin/logstash.bat
Labels: bug, easyreview, status:approved

#13006 [backport 7.x]Use the OS separator to invoke gradlew from Rake script (#13000)
  rakelib/compile.rake
Labels: backport, status:approved, v7.14.0

#12993 Add unit test to grant that production aliases correspond to a published RubyGem
  build.gradle
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
Labels: enhancement, status:approved

#13007 Fix logstash.bat not setting exit code (#12948)
  bin/logstash.bat
Labels: backport, status:approved, v7.14.0

#13005 update clamp fpm and childprocess
  Gemfile.template
  logstash-core/logstash-core.gemspec
  qa/integration/patch/childprocess-modern-java.rb
  qa/integration/services/logstash_service.rb
  rakelib/artifacts.rake
  rakelib/childprocess_patch.rb
Labels: packaging, status:approved

#13008 Fix UBI source URL
  logstash-core/lib/logstash/dependency_report.rb
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/test/resources/expectedOutput.txt
  tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv
  tools/dependencies-report/src/test/resources/licenseMapping-good.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missing.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv
  tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv
  tools/dependencies-report/src/test/resources/rubyDependencies.csv
Labels: enhancement, status:approved

#13002 ispec: fix cross-spec leak from fatal error integration specs
  qa/integration/specs/fatal_error_spec.rb
Labels: status:approved, tests

#13013 Backport PR #13002 to 7.x: ispec: fix cross-spec leak from fatal error integration specs
  qa/integration/specs/fatal_error_spec.rb
Labels: backport, status:approved, v7.14.0

#12830 ecs: on-by-default plus docs
  config/logstash.yml
  docs/index.asciidoc
  docs/static/ecs-compatibility.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
  logstash-core/spec/conditionals_spec.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/plugin_spec.rb
  qa/integration/fixtures/es_output_how_spec.yml
Labels: breaking change, docs, status:approved

#13011 Backport PR #13008 to 7.x: Fix UBI source URL
  logstash-core/lib/logstash/dependency_report.rb
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/test/resources/expectedOutput.txt
  tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv
  tools/dependencies-report/src/test/resources/licenseMapping-good.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missing.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv
  tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv
  tools/dependencies-report/src/test/resources/rubyDependencies.csv
Labels: backport, status:approved, v7.14.0

#13012 Backport PR #13008 to 7.13: Fix UBI source URL
  logstash-core/lib/logstash/dependency_report.rb
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/test/resources/expectedOutput.txt
  tools/dependencies-report/src/test/resources/licenseMapping-conflicting.csv
  tools/dependencies-report/src/test/resources/licenseMapping-good.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missing.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingNotices.csv
  tools/dependencies-report/src/test/resources/licenseMapping-missingUrls.csv
  tools/dependencies-report/src/test/resources/licenseMapping-unacceptable.csv
  tools/dependencies-report/src/test/resources/rubyDependencies.csv
Labels: backport, status:approved, v7.13.3

#13016 Backport PR #12830 to 7.x: ecs-compatibility docs
  config/logstash.yml
  docs/index.asciidoc
  docs/static/ecs-compatibility.asciidoc
Labels: backport, status:approved, v7.14.0

#13004 Add geoip database metrics to /node/stats API
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/api/commands/stats.rb
  logstash-core/lib/logstash/api/modules/node_stats.rb
  rakelib/plugins-metadata.json
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/qa/integration/monitoring/geoip_metric_spec.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: status:approved

#13020 [7.x] Add geoip database metrics to /node/stats API (#13004)
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/api/commands/stats.rb
  logstash-core/lib/logstash/api/modules/node_stats.rb
  rakelib/plugins-metadata.json
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/qa/integration/monitoring/geoip_metric_spec.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
Labels: backport, status:approved, v7.14.0

#13019 Doc: Add geoip database API to node stats
  docs/static/monitoring/monitoring-apis.asciidoc
Labels: docs, status:approved

#13024 Doc: Add geoip database API to node stats
  docs/static/monitoring/monitoring-apis.asciidoc
Labels: backport, docs

#13009 [backport 7.x]Add unit test to grant that production aliases correspond to a published gems (#12993)
  build.gradle
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
Labels: backport, status:approved, v7.14.0

#13027 bump lock file for 7.13.3
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#13026 bump lock file for 6.8.17
  Gemfile.jruby-2.5.lock.release
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/aws-eventstream-1.1.1-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/aws-sdk-2.11.632-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/aws-sdk-core-2.11.632-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/aws-sdk-resources-2.11.632-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/aws-sigv4-1.2.3-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/bindata-2.4.10-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/concurrent-ruby-1.1.9-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/dalli-2.7.11-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/dotenv-2.7.6-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/ffi-1.15.3-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/http-cookie-1.0.4-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/jar-dependencies-0.4.1-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/jruby-openssl-0.10.7-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/manticore-0.7.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/march_hare-4.3.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/msgpack-1.4.2-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/multi_json-1.15.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/nokogiri-1.11.7-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/pleaserun-0.0.32-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/racc-1.5.2-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/racc-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/sequel-5.45.0-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/tzinfo-2.0.4-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/tzinfo-data-1.2021.1-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/xml-simple-1.1.8-NOTICE.txt
Labels: status:approved

#13037 Emergency revert to make bump `7.15.0`
  build.gradle
Labels: status:needs-review

#13035 bump version to 7.15.0
  versions.yml
Labels: status:approved

#13034 add 7.14.0 lockfile based on 7.13 branch
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review
