Repository elastic/logstash, pull requests merged in 2021-07, with the labels that each got.

#13044 Test: resolve integration failure due ECS mode
  x-pack/qa/integration/monitoring/geoip_metric_spec.rb
Labels: status:approved

#13045 Revert #12847
  build.gradle
Labels: status:approved

#13052 Fix LS benchmarking tool to work with releases >= 7.10.0
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LogstashInstallation.java
Labels: status:approved

#13053 [backport 7.x] Fix LS benchmarking tool to work with releases >= 7.10.0 (#13052)
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/LogstashInstallation.java
Labels: backport, v7.15.0

#13048 Docs: keep elastic_app_search output meta-data
  rakelib/plugins-metadata.json
Labels: status:approved

#13054 [7.x] Docs: keep elastic_app_search output meta-data (#13048)
  rakelib/plugins-metadata.json
Labels: backport, status:needs-review

#13055 [7.14] Docs: keep elastic_app_search output meta-data (#13048)
  rakelib/plugins-metadata.json
Labels: backport, status:approved

#13032 Release notes for 6.8.17
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13031 Release notes for 7.13.3
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13039 bump version to 7.13.4
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#13040 bump version to 6.8.18
  Gemfile.jruby-2.5.lock.release
  README.md
  versions.yml
Labels: status:needs-review

#13057 Forwardport 7.13.3 release notes to 7.x
  docs/static/releasenotes.asciidoc
Labels: backport, docs

#13041 Update releases list with 6.8.17 and 7.13.3
  ci/logstash_releases.json
Labels: status:approved

#13062 Doc: Include Windows and Unix commands to run basic pipeline
  docs/static/getting-started-with-logstash.asciidoc
Labels: backport, docs

#13063 Doc: Include Windows and Unix commands to run basic pipeline
  docs/static/getting-started-with-logstash.asciidoc
Labels: backport, docs

#13064 Doc: Include Windows and Unix commands to run basic pipeline
  docs/static/getting-started-with-logstash.asciidoc
Labels: backport, docs

#13042 Move retrieval of Stack version from Gradle's configuration to execution
  build.gradle
Labels: status:approved

#13071 [Test] Fix Unix acceptance tests
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
  qa/config/platforms.json
  qa/vagrant/command.rb
Labels: status:approved, test failure, tests

#13074 Backport PR #13071 to 7.x: [Test] Fix Unix acceptance tests
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
  qa/config/platforms.json
  qa/vagrant/command.rb
Labels: backport, status:needs-review, v7.15.0

#13075 Backport PR #13071 to 7.14: [Test] Fix Unix acceptance tests
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
  qa/config/platforms.json
  qa/vagrant/command.rb
Labels: backport, status:needs-review, v7.14.0

#13076 GeoIP remove multiple databases copy in multiple instances
  x-pack/lib/filters/geoip/database_manager.rb
Labels: status:needs-review

#13073 Doc: Add kafka schema registry setting to troubleshooting
  docs/static/troubleshoot/ts-kafka.asciidoc
Labels: docs, status:needs-review

#13077 Doc: Add kafka schema registry setting to troubleshooting to 7.x
  docs/static/troubleshoot/ts-kafka.asciidoc
Labels: backport, docs

#13078 bump patch level dependencies for 7.14.0
  Gemfile.jruby-2.5.lock.release
Labels: release, status:approved, v7.14.0

#13081 bump plugins for 7.14 release
  Gemfile.jruby-2.5.lock.release
Labels: release, status:needs-review, v7.14.0

#13061 Release notes for 7.13.4
  docs/static/releasenotes.asciidoc
Labels: status:changes-requested

#13086 Forward port of 7.13.4 release notes to 7.x
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13085 Forward port of release notes for 7.13.3 and 7.13.4 to 7.14
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13080 ecs_compatibility: revert breaking change; keep `disabled` as default for 8.0
  config/logstash.yml
  docs/static/ecs-compatibility.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/plugin_spec.rb
Labels: discuss, status:approved, v8.0.0

#12421 doc: add pipeline.ecs_compatibility docs
  docs/static/settings-file.asciidoc
Labels: backport needed, docs, status:approved

#12779 Doc:Fix typo and adjust keystore text
  docs/static/keystore.asciidoc
Labels: docs, status:approved

#13091 Backport PR #12421 to 7.x: doc: add pipeline.ecs_compatibility docs
  docs/static/settings-file.asciidoc
Labels: backport, v7.15.0

#13092 Backport PR #12421 to 7.14: doc: add pipeline.ecs_compatibility docs
  docs/static/settings-file.asciidoc
Labels: backport, v7.14.0

#13088 Update releases list with 7.13.4
  ci/logstash_releases.json
Labels: status:needs-review

#13067 [backport 7.13]Move retrieval of Stack version from Gradle's configuration to execution (#13042)
  build.gradle
Labels: backport, status:work-in-progress

#13095 Doc: Fix typo and adjust keystore text 7.x
  docs/static/keystore.asciidoc
Labels: backport, docs

#13096 Doc: Fix typo and adjust keystore text 7.14
  docs/static/keystore.asciidoc
Labels: backport, docs

#12959 Doc: Enhance and expand DLQ docs
  docs/static/dead-letter-queues.asciidoc
  docs/static/persistent-queues.asciidoc
  docs/static/resiliency.asciidoc
Labels: docs, status:approved

#13099 Doc: Enhance and expand DLQ docs 7.x
  docs/static/dead-letter-queues.asciidoc
  docs/static/persistent-queues.asciidoc
  docs/static/resiliency.asciidoc
Labels: backport, docs

#13100 Doc: Enhance and expand DLQ docs 7.14
  docs/static/dead-letter-queues.asciidoc
  docs/static/persistent-queues.asciidoc
  docs/static/resiliency.asciidoc
Labels: backport, docs

#13110 Doc: Add placeholder for release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#12912 valid variable expansion for the batch files
  bin/benchmark.bat
  bin/ingest-convert.bat
Labels: status:approved
