Repository elastic/logstash, pull requests merged in 2021-04, with the labels that each got.

#12784 Fix: logstash-keystore failing with an error
  logstash-core/lib/logstash/elasticsearch_client.rb
  logstash-core/lib/logstash/modules/kibana_client.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  qa/integration/fixtures/keystore_spec.yml
  qa/integration/fixtures/logstash.keystore
  qa/integration/specs/cli/keystore_spec.rb
Labels: status:needs-review, v7.12.1

#12786 plugin manager uninstall plugin regardless of working directory
  lib/pluginmanager/bundler/logstash_uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
  qa/vagrant/command.rb
Labels: bug, status:changes-requested

#12803 Backport PR #12784 (#12805) to 7.x: Fix: logstash-keystore failing with an error
  logstash-core/lib/logstash/elasticsearch_client.rb
  logstash-core/lib/logstash/modules/kibana_client.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  qa/integration/fixtures/keystore_spec.yml
  qa/integration/fixtures/logstash.keystore
  qa/integration/specs/cli/keystore_spec.rb
Labels: backport, status:needs-review, v7.13.0

#12804 Backport PR #12784 (#12805) to 7.12: Fix: logstash-keystore failing with an error
  logstash-core/lib/logstash/elasticsearch_client.rb
  logstash-core/lib/logstash/modules/kibana_client.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  qa/integration/fixtures/keystore_spec.yml
  qa/integration/fixtures/logstash.keystore
  qa/integration/specs/cli/keystore_spec.rb
Labels: backport, status:needs-review, v7.12.1

#12808 [7.x] Allow plugin manager uninstall plugin regardless of working directory (#12786)
  lib/pluginmanager/bundler/logstash_uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
Labels: backport, v7.13.0

#12809 [7.12] Allow plugin manager uninstall plugin regardless of working directory (#12786)
  lib/pluginmanager/bundler/logstash_uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
Labels: backport, v7.12.1

#12811 Fix Date class clash when used in pipelines with Date filter and GeoIP and pin open-ssl to 0.10.5
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/database_manager.rb
Labels: bug, crashes, status:needs-review

#12812 [backport 7.x] Fix Date class clash when used in pipelines with Date filter and GeoIP and pin open-ssl to 0.10.5 (#12811)
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/database_manager.rb
Labels: backport, status:approved

#12799 Removed static part from PluginRegistry to avoid static initializer
  logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
Labels: enhancement, status:approved

#12672 [doc] Add example to cross-plugin-concepts
  docs/static/cross-plugin-concepts.asciidoc
Labels: docs, easyreview, status:changes-requested

#12810 updated distributor pattern section
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, status:approved

#12801 Docs: note on quoted field references
  docs/static/field-reference.asciidoc
Labels: docs, status:approved

#12817 Backport PR #12801 to 7.x: Docs: note on quoted field references
  docs/static/field-reference.asciidoc
Labels: backport, v7.13.0

#12823 Backport PR #12685 to 7.12: Fix Elasticsearch/DLQ integration test flakiness
  qa/integration/services/elasticsearch_service.rb
  qa/integration/specs/dlq_spec.rb
  qa/integration/specs/es_output_how_spec.rb
  qa/integration/specs/spec_helper.rb
Labels: backport, v7.12.1

#12814 Add new issue templates based on Elasticsearch's
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/test-failure.md
Labels: status:approved

#12824 GeoIP database copy all files from .tgz alongside database
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/sample.tgz
Labels: status:approved

#12826 [7.x] GeoIP database copy all files from .tgz alongside database (#12824)
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/filters/geoip/fixtures/sample.tgz
Labels: backport, status:approved, v7.13.0

#12813 Backport PR #12810 to 7.x: updated distributor pattern section
  docs/static/pipeline-pipeline-config.asciidoc
Labels: backport, status:approved, v7.13.0

#12796 Load a plugin by alias name.
  logstash-core/lib/logstash/plugins/registry.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/plugins/registry_spec.rb
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
Labels: status:needs-review

#12821 Adapted install/uninstall/list PluginManager's command to respect the alised plugins
  lib/pluginmanager/install.rb
  lib/pluginmanager/list.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  lib/pluginmanager/util.rb
Labels: status:needs-review

#12835 [Backport 7.x] plugin alias handling in logstash-core
  logstash-core/lib/logstash/plugins/registry.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/plugins/registry_spec.rb
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/PluginLookup.java
  logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
Labels: 7.13.0, backport

#12836 [Backport 7.x] Plugin Manager adaptation to handle alias plugins
  lib/pluginmanager/install.rb
  lib/pluginmanager/list.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  lib/pluginmanager/util.rb
Labels: 7.13.0, backport

#12825 Update release notes for 7.12.1
  docs/static/releasenotes.asciidoc
Labels: release, status:approved

#12851 Remove json ~>1 pinning
  Gemfile.template
Labels: code cleanup, status:approved

#12775 Doc: Keystore must be accessible to logstash user
  docs/static/keystore.asciidoc
Labels: docs, status:approved

#12864 Doc: Keystore must be accessible to logstash user
  docs/static/keystore.asciidoc
Labels: backport, docs, status:needs-review

#12865 Doc: Keystore must be accessible to logstash user
  docs/static/keystore.asciidoc
Labels: backport, docs, status:needs-review

#12866 Doc: Keystore must be accessible to logstash user
  docs/static/keystore.asciidoc
Labels: backport, docs
