Repository elastic/logstash, pull requests merged in 2021-10, with the labels that each got.

#13260 update golang image
  docker/data/golang/Dockerfile
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: status:needs-review

#13083 Doc: Add shared attribute for messaging ecs default info
  docs/include/attributes-ls.asciidoc
  docs/include/attributes-lsplugins.asciidoc
  docs/index.asciidoc
Labels: docs, status:approved

#13263 [7.15] update golang image to 1.17.1(#13260) (#13260)
  docker/data/golang/Dockerfile
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: backport, status:approved

#13262 [7.x] update golang image to 1.17.1(#13260) (#13260)
  docker/data/golang/Dockerfile
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: backport, status:approved

#13265 Doc: Add shared attribute for messaging ecs default info 7.x
  docs/include/attributes-ls.asciidoc
  docs/include/attributes-lsplugins.asciidoc
  docs/index.asciidoc
Labels: docs, backport

#13266 Doc: Add shared attribute for messaging ecs default info 7.15
  docs/include/attributes-ls.asciidoc
  docs/include/attributes-lsplugins.asciidoc
  docs/index.asciidoc
Labels: docs, backport

#13267 Doc: Add shared attribute for messaging ecs default info 7.14
  docs/include/attributes-ls.asciidoc
  docs/include/attributes-lsplugins.asciidoc
  docs/index.asciidoc
Labels: docs, backport

#13218 unlock ecs_compatibility_support version in plugin update
  lib/bootstrap/bundler.rb
  lib/pluginmanager/install.rb
  spec/unit/bootstrap/bundler_spec.rb
  spec/unit/plugin_manager/install_spec.rb
  spec/unit/plugin_manager/util_spec.rb
Labels: status:approved

#13264 update golang image
  docker/data/golang/Dockerfile
Labels: status:needs-review

#13268 [7.x] unlock ecs_compatibility_support version in plugin update (#13218)
  lib/bootstrap/bundler.rb
  lib/pluginmanager/install.rb
  spec/unit/bootstrap/bundler_spec.rb
  spec/unit/plugin_manager/install_spec.rb
  spec/unit/plugin_manager/util_spec.rb
Labels: backport, status:approved, v7.15.1

#13269 [7.15] unlock ecs_compatibility_support version in plugin update (#13218)
  lib/bootstrap/bundler.rb
  lib/pluginmanager/install.rb
  spec/unit/bootstrap/bundler_spec.rb
  spec/unit/plugin_manager/install_spec.rb
  spec/unit/plugin_manager/util_spec.rb
Labels: backport, status:approved, v7.16.0

#13270 Fix plugin manager test that fail to fetch dependency
  spec/unit/plugin_manager/util_spec.rb
Labels: status:needs-review

#13271 [7.x] Fix plugin manager test that fail to fetch dependency (#13270)
  spec/unit/plugin_manager/util_spec.rb
Labels: backport, status:approved

#13272 [7.15] Fix plugin manager test that fail to fetch dependency (#13270)
  spec/unit/plugin_manager/util_spec.rb
Labels: backport, status:approved

#13246 Doc: Add topic and expand info for in-memory queue
  docs/index.asciidoc
  docs/static/mem-queue.asciidoc
  docs/static/resiliency.asciidoc
Labels: docs, work in progress, status:approved

#13276 Doc: Add topic and expand info for in-memory queue
  docs/index.asciidoc
  docs/static/mem-queue.asciidoc
  docs/static/resiliency.asciidoc
Labels: docs, backport

#13273 replace Faraday with Manticore to get rid of jruby-openssl verification error
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: status:approved

#13280 [7.15] Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: backport, status:approved, v7.15.1

#13279 [7.x] Replace Faraday to Manticore to get rid of jruby-openssl verification error of Let's Encrypt cross-signed DST Root CA X3 (#13273)
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: backport, status:approved, v7.16.0

#13259 Doc: Remove outdated info and folder
  docs/index.asciidoc
  docs/static/setup/images/LogstashFlow.jpg
  docs/static/setup/setting-up-xpack.asciidoc
Labels: docs, status:approved
