Repository elastic/logstash, pull requests merged in 2021-01, with the labels that each got.

#12543 Doc: Add info on contributor program
  CONTRIBUTING.md
Labels: docs

#12545 Doc: Add info on contributor program
  CONTRIBUTING.md
Labels: backport, docs

#12546 Doc: Add info on contributor program
  CONTRIBUTING.md
Labels: backport, docs

#12547 Doc: Add info on contributor program
  CONTRIBUTING.md
Labels: backport, docs

#12554 pq: eliminate corruption by forcing version byte to be persisted
  logstash-core/src/main/java/org/logstash/ackedqueue/io/MmapPageIOV2.java
Labels: bug, persistent queues

#12559 Fix: make sure LS exits when running into fatal errors
  logstash-core/src/main/java/org/logstash/Logstash.java
  qa/integration/fixtures/fatal_error_spec.yml
  qa/integration/specs/fatal_error_spec.rb
Labels: backport

#12512 Feature/use custom routing log appender
  config/log4j2.properties
  logstash-core/benchmarks/src/main/resources/log4j2-with-script.properties
  logstash-core/lib/logstash/runner.rb
  logstash-core/src/main/java/org/logstash/Logstash.java
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingAppender.java
  logstash-core/src/main/java/org/logstash/log/PipelineRoutingFilter.java
  logstash-core/src/test/java/org/logstash/log/LogstashConfigurationFactoryTest.java
  logstash-core/src/test/java/org/logstash/log/PipelineRoutingAppenderTest.java
  logstash-core/src/test/java/org/logstash/log/PipelineRoutingFilterTest.java
  logstash-core/src/test/resources/log4j-pipeline-routing.xml
  logstash-core/src/test/resources/log4j2-log-pipeline-test.properties
  qa/integration/fixtures/persistent_queues/log4j2.properties
Labels: breaking change, enhancement, java 15 support

#12530 Removed CMS GC flags to run tests successfully on JDK15
  bin/logstash
  bin/logstash.bat
  bin/logstash.lib.sh
  config/jvm.options
  docs/static/config-details.asciidoc
  logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java
  logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Labels: enhancement, java 15 support

#12585 [windows] fix launch when folder contains spaces
  bin/logstash.bat
Labels: bug, windows

#12600 Backport PR #12585 to 7.11: [windows] fix launch when folder contains spaces
  bin/logstash.bat
Labels: backport, v7.11.0

#12599 Backport PR #12585 to 7.x: [windows] fix launch when folder contains spaces
  bin/logstash.bat
Labels: backport, v7.12.0

#12609 Backport PR #12603 to 7.11: bump jrjackson to 0.4.14 and jackson-databind to 2.9.10.8
  versions.yml
Labels: backport, v7.11.0

#12608 Backport PR #12603 to 7.x: bump jrjackson to 0.4.14 and jackson-databind to 2.9.10.8
  versions.yml
Labels: backport, v7.12.0

#12537 Update CI to run on OpenJDK15
  .ci/matrix-runtime-javas.yml
Labels: enhancement, java 15 support

#12613 Doc: Clarify minimum privileges for logstash_writer role
  docs/static/security/logstash.asciidoc
Labels: docs

#12582 enable converging state with predefined pipeline actions
  logstash-core/lib/logstash/agent.rb
  logstash-core/spec/logstash/agent_spec.rb
Labels: v7.12.0

#12615 replace with_clean_env with with_unbundled_env
  qa/integration/services/logstash_service.rb
  qa/vagrant/command.rb
  tools/logstash-docgen/lib/logstash/docgen/github_generator.rb
  tools/paquet/spec/integration/paquet_spec.rb
Labels: bundler, code cleanup

#12617 fix url for kafka and bump to 2.7.0
  qa/integration/services/kafka_setup.sh
Labels: test failure

#12618 Backport PR #12615 to 7.x: replace with_clean_env with with_unbundled_env
  qa/integration/services/logstash_service.rb
  qa/vagrant/command.rb
  tools/logstash-docgen/lib/logstash/docgen/github_generator.rb
  tools/paquet/spec/integration/paquet_spec.rb
Labels: backport, v7.12.0

#12623 [Doc] Clarify minimum privileges for logstash_writer role 7.x
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12624 [Doc] Clarify minimum privileges for logstash_writer role 7.11
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12625 [Doc] Clarify minimum privileges for logstash_writer role 7.10
  docs/static/security/logstash.asciidoc
Labels: backport, docs

#12620 Backport PR #12617 to 7.11: fix url for kafka and bump to 2.7.0
  qa/integration/services/kafka_setup.sh
Labels: backport, v7.11.0

#12619 Backport PR #12617 to 7.x: fix url for kafka and bump to 2.7.0
  qa/integration/services/kafka_setup.sh
Labels: backport, v7.12.0
