Repository elastic/logstash, pull requests merged in 2021-11, with the labels that each got.

#13368 Doc: Update central management subscription info
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
Labels: docs, status:approved

#13377 Doc: Add release notes placeholder
  docs/static/releasenotes.asciidoc
Labels: docs

#13379 Doc: Update central management license info 8.0
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
Labels: docs, backport

#13375 Doc: Update central management license info 7.15
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
Labels: docs, backport

#13374 Doc: Update central management license info 7.16
  docs/static/management/centralized-pipelines.asciidoc
  docs/static/management/configuring-centralized-pipelines.asciidoc
Labels: docs, backport, status:needs-review

#13369 Add java version parameterization to Logstash builds
  .ci/java-versions.properties
Labels: status:approved

#13387 Deps: update JRuby to 9.2.20.0
  rubyUtils.gradle
  versions.yml
Labels: JRuby 9K, status:approved, v8.1.0

#13389 Bump lockfile for 7.15.2
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#13383 Backport PR #13369 to 8.0. Add java version parameterization to Logst…
  .ci/java-versions.properties
Labels: backport, v8.0.0, status:approved

#13385 Backport PR #13369 to 7.15. Add java version parameterization to Logs…
  .ci/java-versions.properties
Labels: backport, status:needs-review, v7.15.2

#13386 Backport PR #13369 to 7.16: Add java version parameterization to Logs…
  .ci/java-versions.properties
Labels: backport, status:needs-review, v7.16.0

#13384 Backport PR #13369 to 6.8. Add java version parameterization to Logst…
  .ci/java-versions.properties
Labels: backport, status:needs-review, v6.8.21

#13301 rename references of master branch to main branch
  devtools/backport
  devtools/create_pr
  lib/pluginmanager/templates/codec-plugin/README.md
  lib/pluginmanager/templates/filter-plugin/README.md
  lib/pluginmanager/templates/input-plugin/README.md
  lib/pluginmanager/templates/output-plugin/README.md
  logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
  logstash-core/benchmarks/build.gradle
  logstash-core/build.gradle
  logstash-core/lib/logstash-core/version.rb
  logstash-core/lib/logstash/version.rb
  tools/benchmark-cli/README.md
  tools/benchmark-cli/build.gradle
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/ui/UserInput.java
  tools/benchmark-cli/src/test/java/org/logstash/benchmark/cli/MainTest.java
  tools/dependencies-report/README.md
  tools/dependencies-report/build.gradle
  tools/ingest-converter/build.gradle
  tools/logstash-docgen/README.md
  tools/logstash-docgen/lib/logstash/docgen/github_generator.rb
  tools/logstash-docgen/lib/logstash/docgen/parser.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: status:approved

#13302 [DOC] replace references to master branch with main
  docs/static/configuration.asciidoc
  docs/static/contrib-acceptance.asciidoc
  docs/static/contribute-core.asciidoc
  docs/static/contributing-to-logstash.asciidoc
  docs/static/doc-for-plugin.asciidoc
  docs/static/include/pluginbody.asciidoc
  docs/static/java-codec.asciidoc
  docs/static/java-filter.asciidoc
  docs/static/java-input.asciidoc
  docs/static/java-output.asciidoc
  docs/static/maintainer-guide.asciidoc
  docs/static/reserved-fields.asciidoc
  docs/static/submitting-a-plugin.asciidoc
Labels: status:needs-review

#13373 Release notes for 8.0.0-beta1
  docs/static/releasenotes.asciidoc
Labels: status:approved, v8.0.0-beta1

#13390 Release notes for 7.15.2
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#13400 Build: lock fpm to 1.13.x to avoid dep packaging issues using 1.14.0
  Gemfile.template
Labels: status:needs-review

#13402 Relax fpm version constraint after bug fix fpm#1856
  Gemfile.template
Labels: packaging

#13380 Fixes a usage of deprecated 'http.enabled' to the new 'api.enabled'
  x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: status:approved

#13156 Refactor: report Java thread name in thread info
  logstash-core/lib/logstash/util.rb
  logstash-core/src/main/java/org/logstash/util/UtilExt.java
Labels: status:approved

#13403 Refactor: avoid futile attempt to gc a string quickly
  logstash-core/src/main/java/org/logstash/secret/store/SecretStoreFactory.java
Labels: status:approved

#13407 [backport 8.0]Fixes a usage of deprecated 'http.enabled' #13380
  x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: backport, status:needs-review

#13408 [backport 7.16]Fixes a usage of deprecated 'http.enabled' to the new 'api.enabled' (#13380)
  x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: backport, status:needs-review, v7.16.0

#13376 Doc: Add breaking changes
  docs/static/breaking-changes.asciidoc
Labels: docs, status:approved

#13414 Doc: Add breaking changes 8.0
  docs/static/breaking-changes.asciidoc
Labels: docs, backport

#13413 propagate master/main branch rename for geoip filter (7.16)
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: test failure, build, status:needs-review

#13412 Master to main references 8.0
  x-pack/spec/filters/geoip/download_manager_spec.rb
Labels: test failure, build, status:needs-review

#13411 Backport PR#12626 to 6.8: use correct headers api for redirects in pl…
  lib/pluginmanager/utils/http_client.rb
  spec/unit/plugin_manager/utils/http_client_spec.rb
Labels: backport, status:needs-review, v6.8.21

#13391 ECS on by default for Logstash 8, again
  config/logstash.yml
  docs/static/breaking-changes.asciidoc
  docs/static/ecs-compatibility.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/plugin_spec.rb
Labels: enhancement, breaking change, status:approved

#13416 Backport PR #13391 to 8.0: ECS on by default for Logstash 8, again
  config/logstash.yml
  docs/static/breaking-changes.asciidoc
  docs/static/ecs-compatibility.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/plugin_spec.rb
Labels: backport, v8.0.0, status:needs-review

#13319 Doc: Expand PQ content for pipeline-pipeline
  docs/static/persistent-queues.asciidoc
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs

#13421 Doc: Expand PQ content for pipeline-pipeline 8.0
  docs/static/persistent-queues.asciidoc
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13422 Doc: Expand PQ content for pipeline-pipeline 7.16
  docs/static/persistent-queues.asciidoc
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13423 Doc: Expand PQ content for pipeline-pipeline 7.15
  docs/static/persistent-queues.asciidoc
  docs/static/pipeline-pipeline-config.asciidoc
Labels: docs, backport

#13427 Doc: Update attribute for ECS messaging wrt default (LSR)
  docs/include/attributes-lsplugins.asciidoc
Labels: docs, status:needs-review

#13434 Forward Port: Release notes for 7.15.1 (#13295)
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13437 Update bundled JDK to 11.0.13+8
  versions.yml
Labels: Java 11 Support, status:approved

#13418 Update logstash-releases.json
  ci/logstash_releases.json
Labels: status:approved

#13439 Backport PR #13437 to 8.0: Update bundled JDK to 11.0.13+8
  versions.yml
Labels: backport, v8.0.0, status:needs-review

#13440 Backport PR #13437 to 7.16: Update bundled JDK to 11.0.13+8
  versions.yml
Labels: backport, status:needs-review, v7.16.0

#13014 Docker integration tests stability improvements
  docker/Makefile
  qa/docker/fixtures/multiple_pipelines/pipelines/basic2.cfg
  qa/docker/patches/excon/unix_socket.rb
  qa/docker/shared_examples/container.rb
  qa/docker/shared_examples/container_config.rb
  qa/docker/shared_examples/container_options.rb
  qa/docker/spec/spec_helper.rb
  qa/docker/spec/ubi8/container_spec.rb
Labels: build, docker, status:approved

#13446 Backport PR#13014 to 7.16: Docker integration tests stability improve…
  docker/Makefile
  qa/docker/fixtures/multiple_pipelines/pipelines/basic2.cfg
  qa/docker/patches/excon/unix_socket.rb
  qa/docker/shared_examples/container.rb
  qa/docker/shared_examples/container_config.rb
  qa/docker/shared_examples/container_options.rb
  qa/docker/spec/spec_helper.rb
  qa/docker/spec/ubi8/container_spec.rb
Labels: backport, status:needs-review, v7.16.0

#13450 Deps: bump lock file for 8.0.0
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#13447 Fix: patch Puma around a JRuby ARM64 bug
  logstash-core/lib/logstash/patches/puma.rb
Labels: status:needs-review

#13431 artifacts: exclude unused rubyzip test files from distributions
  rakelib/artifacts.rake
Labels: build, easyreview, status:approved

#13445 Backport PR#13014 to 8.0: Docker integration tests stability improvem…
  docker/Makefile
  qa/docker/fixtures/multiple_pipelines/pipelines/basic2.cfg
  qa/docker/patches/excon/unix_socket.rb
  qa/docker/shared_examples/container.rb
  qa/docker/shared_examples/container_config.rb
  qa/docker/shared_examples/container_options.rb
  qa/docker/spec/spec_helper.rb
  qa/docker/spec/ubi8/container_spec.rb
Labels: backport, v8.0.0, status:approved

#13453 Backport PR #13447 to 8.0: Fix: patch Puma around a JRuby ARM64 bug
  logstash-core/lib/logstash/patches/puma.rb
Labels: backport, v8.0.0, status:approved

#13456 Add template for creating documentation issues
  .github/ISSUE_TEMPLATE/doc-request.md
Labels: status:approved

#13462 Doc: Fix link in attribute
  docs/include/attributes-lsplugins.asciidoc
Labels: docs
