Repository elastic/logstash, pull requests merged in 2022-07, with the labels that each got.

#14324 Added metric to count removed events when age retention kicks in
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Labels: DLQ, status:approved

#14333 Bugfix for DLQ when writer is pushing data and reader consuming.
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Labels: bug, DLQ, status:approved

#14342 [Docs] Fixes a typo in the docs
  docs/static/plugin-manager.asciidoc
Labels: docs, status:approved, v8.4.0

#12276 Docs: Fix 404s
  docs/static/include/pluginbody.asciidoc
  docs/static/java-codec.asciidoc
  docs/static/java-input.asciidoc
  docs/static/java-output.asciidoc
  docs/static/private-gem-repo.asciidoc
Labels: docs, status:needs-triage

#14343 Fix broken link to image
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
Labels: docs

#14347 [DOC] update link from master to main
  docs/static/advanced-pipeline.asciidoc
  docs/static/java-codec.asciidoc
  docs/static/java-input.asciidoc
  docs/static/java-output.asciidoc
Labels: status:needs-review

#14348 Update dependencies
  Gemfile.template
  versions.yml
Labels: backport needed, status:approved, v8.4.0

#14336 Expose DLQ deleted events count on reader side
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueUtils.java
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/main/java/org/logstash/common/io/SegmentListener.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Labels: DLQ, status:approved

#13523 Create wrapper class to bridge the calls to Ruby codec and present it self as a Java codec
  logstash-core/src/main/java/org/logstash/config/ir/compiler/RubyIntegration.java
  logstash-core/src/main/java/org/logstash/plugins/ConfigurationImpl.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
  logstash-core/src/main/java/org/logstash/plugins/factory/RubyCodecDelegator.java
  logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java
  logstash-core/src/test/java/org/logstash/plugins/TestPluginFactory.java
  qa/integration/fixtures/mixed_codec_spec.yml
  qa/integration/services/logstash_service.rb
  qa/integration/specs/mixed_codec_spec.rb
Labels: enhancement, status:needs-review

#13343 Update bundled JDK to jdk 17
  .ci/java-versions.properties
  versions.yml
Labels: status:approved

#13874 ArcSight Module Broken (Invalid Type), Fixed
  logstash-core/lib/logstash/modules/logstash_config.rb
  logstash-core/spec/logstash/modules/logstash_config_spec.rb
  x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb
  x-pack/spec/modules/arcsight/arcsight_module_config_spec.rb
Labels: ArcSight module, status:needs-review

#14357 Update .ruby-version to match jruby version of 9.3.6.0
  .ruby-version
Labels: status:approved

#14358 Fix `test_port_ruby` on build nodes with outdated system java
  qa/integration/services/helpers.sh
Labels: status:approved

#14359 Reduce the amount of memory required by gradle for integration tests
  ci/integration_tests.sh
Labels: status:approved

#14331 jruby-9.3 test fix for windows CI
  logstash-core/lib/logstash/plugins/ca_trusted_fingerprint_support.rb
  logstash-core/spec/logstash/plugins/ca_trusted_fingerprint_support_spec.rb
Labels: status:needs-review

#14360 Clean up java plugin threadsafe/concurrency check
  logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
Labels: status:needs-review

#14364 Add config.field_reference.escape_style to env2yaml
  docker/data/logstash/env2yaml/env2yaml.go
Labels: status:approved

#14352 Doc: Remove version plugin conditionals from Logstash Ref plugin headers
  docs/include/plugin_header-integration.asciidoc
  docs/include/plugin_header.asciidoc
Labels: docs, status:approved

#14032 Doc: Migrate terminology to emphasize pipeline for better seo
  docs/index.asciidoc
  docs/static/env-vars.asciidoc
  docs/static/event-data.asciidoc
  docs/static/ls-to-cloud.asciidoc
  docs/static/pipeline-config-exps.asciidoc
  docs/static/pipeline-configuration.asciidoc
Labels: docs, status:approved

#14373 Revert "Update .ruby-version to match jruby version of 9.3.6.0 (#14357)"
  .ruby-version
Labels: status:approved

#14374 Fix mismatched Java versions in integration tests
  qa/integration/services/helpers.sh
  qa/integration/services/logstash_service.rb
Labels: status:approved

#13425 Create M1 artifacts
  rakelib/artifacts.rake
Labels: status:work-in-progress

#14011 [doc] Update example ES output configs to reflect DS being default
  docs/static/filebeat-modules.asciidoc
Labels: docs, status:approved

#14377 update some java dependencies
  logstash-core/build.gradle
Labels: status:needs-review

#14378 upgrade to gradle 7.5
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: status:work-in-progress

#14382 Bump version to 8.5.0
  versions.yml
Labels: status:needs-review

#14341 Document the cleaning of consumed events feature
  docs/static/dead-letter-queues.asciidoc
Labels: docs, DLQ, status:approved

#14340 Describe DLQ's age retention policy
  docs/static/dead-letter-queues.asciidoc
Labels: docs, DLQ, status:approved

#14395 pin bundler 2.3.18 to avoid bug in .19 (for 8.4 branch)
  build.gradle
Labels: status:work-in-progress

#14394 pin bundler 2.3.18 to avoid bug in .19
  build.gradle
Labels: status:approved

#14392 Introduce 8.4.0 gemlock file.
  Gemfile.jruby-2.6.lock.release
Labels: status:needs-review, release

#14391 Make version bump github action work with future JRuby versions
  .github/workflows/version_bumps.yml
Labels: status:approved
