Repository elastic/logstash, pull requests merged in 2022-11, with the labels that each got.

#14633 specs: assert presence of logging without risking NoMethodError
  qa/integration/specs/monitoring_api_spec.rb
Labels: status:approved

#14684 Update settings-file.asciidoc
  docs/static/settings-file.asciidoc
Labels: status:approved

#14713 Fix pipelines yaml loading
  logstash-core/lib/logstash/config/source/multi_local.rb
  logstash-core/locales/en.yml
  qa/integration/specs/multiple_pipeline_spec.rb
Labels: bug, multiple pipelines, status:approved, i18n

#14718 Add known issue to 8.5.0
  docs/static/releasenotes.asciidoc
Labels: docs, status:needs-review

#14729 7.17 - Update bundled JDK to 11.0.17+8
  versions.yml
Labels: status:approved

#14728 8.5 - Update bundled JDK to 17.0.5+8
  versions.yml
Labels: status:approved

#14737 [doc] Logstash Kubernetes - Securing Logstash
  docsk8s/setting-up/ls-k8s-secure.asciidoc
Labels: status:approved

#14696 [doc] Logstash Kubernetes - Stack Monitoring docs
  docsk8s/administering/ls-k8s-stack-monitoring-cloud.asciidoc
  docsk8s/administering/ls-k8s-stack-monitoring-external.asciidoc
  docsk8s/administering/ls-k8s-stack-monitoring.asciidoc
  docsk8s/images/sm-kibana.png
  docsk8s/index.asciidoc
Labels: status:approved

#14714 [doc] Logstash Kubernetes - Persistent Storage Docs
  docsk8s/setting-up/ls-k8s-persistent-storage.asciidoc
  docsk8s/troubleshooting/ls-k8s-troubleshooting-methods.asciidoc
Labels: status:approved

#14727 Avoid the wrapping of LogstashMessageFactory with log4j's MessageFactory adapter
  logstash-core/src/main/java/org/logstash/log/LogstashMessageFactory.java
Labels: bug, status:approved

#14738 [Doc] Document the usage of LS_JAVA_OPTS environment variable
  docs/static/config-details.asciidoc
Labels: docs, status:approved

#14752 Backport PR#14605 to 7.17: Fix DLQ fails to start due to read 1 byte …
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Labels: status:approved

#14756 Copy exisisting gems lock from 8.5
  Gemfile.jruby-2.6.lock.release
Labels: status:needs-review

#14755 Bump to 8.7.0
  versions.yml
Labels: status:work-in-progress

#14655 Logstash Getting started with Kubernetes Guide
  docsk8s/index.asciidoc
  docsk8s/quick-start/ls-k8s-configuration-files.asciidoc
  docsk8s/quick-start/ls-k8s-external-resource.asciidoc
  docsk8s/quick-start/ls-k8s-quick-start.asciidoc
  docsk8s/quick-start/sample-configuration-files.asciidoc
Labels: status:needs-review, v8.6.0

#14763 Forward port releasenotes from `8.5.0` and `8.5.1`
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#14754 Use `aarch64` artifact arch for integration tests on Mac M1 (darwin) OS.
  build.gradle
Labels: developer support, status:approved, ci

#14760 fix: calculated inflight_count from in-flight batches
  logstash-core/spec/logstash/pipeline_reporter_spec.rb
  logstash-core/spec/support/mocks_classes.rb
  logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java
Labels: bug, status:approved

#14775 Forward port 8.5.2 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#14694 bump jruby to 9.3.9.0
  rubyUtils.gradle
  versions.yml
Labels: JRuby 9K, status:approved, v8.6.0

#14780 [DRA] Avoid to loose err code on docker save
  ci/dra_common.sh
Labels: bug, status:approved, DRA

#14786 Avoid to create and upload AARCH64 Docker images for UBI8
  ci/dra_common.sh
  ci/dra_docker.sh
Labels: status:needs-review

#14792 Doc: Add placeholder and coming tag for 8.6.0 release notes
  docs/static/releasenotes.asciidoc
Labels: status:needs-review, v8.6.0
