Repository elastic/logstash, pull requests merged in 2022-03, with the labels that each got.

#13822 Remove CI JDK matrix definition file
  .ci/matrix-runtime-javas.yml
Labels: status:needs-review

#13820 Build: avoid doing a redundant bundle install
  build.gradle
  rakelib/vendor.rake
Labels: status:needs-review

#13831 CI: update 8.x resolution after 8.0.1 release
  ci/logstash_releases.json
Labels: status:needs-review

#13244 i18n: alias logstash.runner.configuration.* under logstash.agent.configuration
  logstash-core/locales/en.yml
Labels: status:approved

#13424 api: avoid 5xx when stats/events not yet populated
  logstash-core/lib/logstash/api/commands/node.rb
  logstash-core/lib/logstash/api/commands/stats.rb
Labels: bug, int-shortlist, status:approved, HTTP API

#13686 tools: allow version bump to use local lockfile as baseline
  tools/release/bump_plugin_versions.rb
Labels: automation, status:approved

#13827 Doc: Correct name for java_home env variable in Windows section
  docs/static/running-logstash-windows.asciidoc
Labels: docs, status:approved

#13847 Doc: Correct name for java_home env variable for Windows [8.1]
  docs/static/running-logstash-windows.asciidoc
Labels: docs, backport

#13848 Doc: Correct name for java_home env variable for Winddows [8.0]
  docs/static/running-logstash-windows.asciidoc
Labels: docs, backport

#13345 pipeline-info: increase safety of transforming stats
  logstash-core/lib/logstash/config/pipelines_info.rb
Labels: bug, status:approved

#13715 artifacts: omit openssl_pkcs8_pure specs from built artifacts
  rakelib/artifacts.rake
Labels: build, status:approved

#13840 Backport PR #13410 to 8.1: geoip-db: support `http_proxy` environment variable
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/support/helpers.rb
Labels: backport, status:approved, v8.1.0

#13841 Backport PR #13410 to 7.17: geoip-db: support `http_proxy` environment variable
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/support/helpers.rb
Labels: backport, status:approved, v7.17.2

#13854 [8.1] expose shutdown request state of pipeline (#13811)
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/outputs/base.rb
  logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
Labels: backport, status:approved

#13084 Doc: Improve formatting and readability for pipeline ordering
  config/logstash.yml
  config/pipelines.yml
  docs/static/settings-file.asciidoc
Labels: docs, status:changes-requested

#13852 Backport PR #13715 to 7.17: artifacts: omit openssl_pkcs8_pure specs from built artifacts
  docs/static/releasenotes.asciidoc
  rakelib/artifacts.rake
Labels: backport, status:approved, v7.17.2

#13851 Backport PR #13715 to 8.1: artifacts: omit openssl_pkcs8_pure specs from built artifacts
  rakelib/artifacts.rake
Labels: backport, status:needs-review, v8.1.0

#13839 Fix Logstash cli tools to use the selected JDK under Windows
  bin/benchmark.bat
  bin/ingest-convert.bat
  bin/logstash.bat
  bin/pqcheck.bat
  bin/pqrepair.bat
  bin/setup.bat
Labels: bug, windows, status:approved

#13828 Release notes for 8.1.0
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13744 [Backport PR#13728 to 8.1] [Test] Fix acceptance tests to deal with J…
  logstash-core/src/main/java/org/logstash/util/JavaVersionChecker.java
  qa/acceptance/spec/lib/artifact_operation_spec.rb
  qa/acceptance/spec/lib/cli_operation_spec.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
  qa/acceptance/spec/shared_examples/installed_with_jdk.rb
  qa/acceptance/spec/shared_examples/updated.rb
  qa/acceptance/spec/spec_helper.rb
  qa/rspec/commands.rb
  qa/rspec/commands/base.rb
  qa/rspec/commands/redhat.rb
  qa/rspec/commands/system_helpers.rb
  qa/rspec/matchers/be_running.rb
Labels: backport, status:approved, v8.1.0

#13862 speed up artifact file listing
  rakelib/artifacts.rake
Labels: status:approved

#13807 Update pr backporter workflow
  .github/workflows/pr_backporter.yml
Labels: developer support, automation, status:needs-review

#13864 Backport PR #13862 to 8.1: speed up artifact file listing
  rakelib/artifacts.rake
Labels: backport, v8.1.0

#13865 Backport PR #13862 to 7.17: speed up artifact file listing
  rakelib/artifacts.rake
Labels: backport, v7.17.2

#13850 Backport PR #13345 to 7.17: pipeline-info: increase safety of transforming stats
  logstash-core/lib/logstash/config/pipelines_info.rb
Labels: backport, status:needs-review, v7.17.2

#13845 Backport PR #13424 to 7.17: api: avoid 5xx when stats/events not yet populated
  logstash-core/lib/logstash/api/commands/node.rb
  logstash-core/lib/logstash/api/commands/stats.rb
Labels: backport, status:needs-review, v7.17.2

#13843 Backport PR #13244 to 7.17: i18n: alias logstash.runner.configuration.* under logstash.agent.configuration
  logstash-core/locales/en.yml
Labels: backport, status:needs-review, v7.17.2

#13866 Pin jruby-openssl in logstash-core to 0.12.1
  logstash-core/logstash-core.gemspec
Labels: status:needs-review

#13829 Bump version to next 8.1.1
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#13870 Backport PR #13687 to 7.17: bump jdk to 11.0.14.1+1
  versions.yml
Labels: backport, status:needs-review, v7.17.2

#13869 Backport PR #13687 to 8.1: bump jdk to 11.0.14.1+1
  versions.yml
Labels: backport, status:needs-review, v8.1.0

#13867 Add plugin uninstall release note
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13830 Update CI versions after 8.1.0
  ci/logstash_releases.json
Labels: status:approved

#13803 Backport PR #13794 to 8.1: Feat: conservative plugin (dependency) updates by default
  lib/bootstrap/bundler.rb
  lib/pluginmanager/install.rb
  lib/pluginmanager/update.rb
  spec/unit/plugin_manager/update_spec.rb
Labels: backport, status:needs-review, v8.1.1

#13860 [Backport 8.1]Fix Logstash cli tools to use the selected JDK under Windows (#13839)
  bin/benchmark.bat
  bin/ingest-convert.bat
  bin/logstash.bat
  bin/pqcheck.bat
  bin/pqrepair.bat
  bin/setup.bat
Labels: backport, status:approved, v8.1.1

#13871 Doc: Clarify monitoring settings
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
Labels: docs

#13833 [Doc] update queue.max_bytes and queue.page_capacity
  docs/static/persistent-queues.asciidoc
Labels: status:needs-review

#12415 Remove bin/system-install (pleaserun) usage
  pkg/centos/after-install.sh
  pkg/centos/before-install.sh
  pkg/debian/after-install.sh
  pkg/debian/before-install.sh
  pkg/service_templates/systemd/lib/systemd/system/logstash.service
  pkg/service_templates/sysv/etc/default/logstash
  pkg/service_templates/sysv/etc/init.d/logstash
  pkg/ubuntu/after-install.sh
  pkg/ubuntu/before-install.sh
  rakelib/artifacts.rake
Labels: packaging, revisit, status:approved

#13891 Updates license checker after inclusion of libs `et-orbi`, `fugit` and `raabro`.
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/et-orbi-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/fugit-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/raabro-NOTICE.txt
Labels: status:needs-review

#13889 Deps: unpin jruby-openssl in logstash-core
  logstash-core/logstash-core.gemspec
Labels: status:needs-review

#13894 [Backport #13881 8.1]Quotes java executable path in case it contains spaces
  bin/benchmark.bat
  bin/ingest-convert.bat
  bin/logstash.bat
  bin/pqcheck.bat
  bin/pqrepair.bat
  bin/setup.bat
Labels: backport, status:needs-review, v8.1.1

#13893 [Backport #13881 7.17]Quotes java executable path in case it contains spaces
  bin/benchmark.bat
  bin/ingest-convert.bat
  bin/logstash.bat
  bin/pqcheck.bat
  bin/pqrepair.bat
  bin/setup.bat
Labels: backport, status:needs-review, v7.17.2

#13897 Backport PR#13891 to 8.1. Updates license checker after inclusion of …
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/et-orbi-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/fugit-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/raabro-NOTICE.txt
Labels: backport, status:needs-review, v8.1.1

#13896 Update Gemfile.lock for 8.1.1
  Gemfile.jruby-2.5.lock.release
Labels: status:needs-review

#13900 Update Jackson databind in ingest-converter tool
  tools/ingest-converter/build.gradle
Labels: status:approved

#13903 Deps: unpin jruby-openssl in logstash-core
  logstash-core/logstash-core.gemspec
Labels: status:approved

#13880 Print bundled jdk's version in launch scripts when `LS_JAVA_HOME` is provided
  bin/logstash.lib.sh
  bin/setup.bat
  build.gradle
  buildSrc/src/main/groovy/org/logstash/gradle/tooling/ExtractBundledJdkVersion.groovy
  buildSrc/src/main/groovy/org/logstash/gradle/tooling/ToolingUtils.groovy
  buildSrc/src/test/groovy/org/logstash/gradle/tooling/ExtractBundledJdkVersionTest.groovy
  rakelib/artifacts.rake
Labels: status:approved

#13898 Enable content write permission for pr backporter workflow
  .github/workflows/pr_backporter.yml
Labels: automation, status:needs-review

#13904 fix default argument handling in rake artifact task
  rakelib/artifacts.rake
Labels: bug, packaging, status:approved

#13842 Backport PR #13244 to 8.1: i18n: alias logstash.runner.configuration.* under logstash.agent.configuration
  logstash-core/locales/en.yml
Labels: backport, status:approved, v8.1.1

#13899 Fixes centos-7+ package
  pkg/centos/after-install.sh
  pkg/service_templates/sysv/etc/init.d/logstash
Labels: status:approved

#13689 Update failing policy in Central Management fetcher and license checker if hit ES down node
  x-pack/lib/config_management/elasticsearch_source.rb
  x-pack/lib/helpers/loggable_try.rb
  x-pack/lib/license_checker/license_reader.rb
  x-pack/qa/integration/management/read_configuration_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
Labels: status:approved

#13902 add backoff to checkpoint write
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/io/FileCheckpointIO.java
  logstash-core/src/main/java/org/logstash/util/CheckedSupplier.java
  logstash-core/src/main/java/org/logstash/util/ExponentialBackoff.java
  logstash-core/src/test/java/org/logstash/util/ExponentialBackoffTest.java
Labels: status:approved

#13877 PQ size check for multiple pipelines
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb
  logstash-core/lib/logstash/persisted_queue_config_validator.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/spec/logstash/bootstrap_check/persisted_queue_config_spec.rb
  logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb
Labels: status:approved

#13825 [Java17] Add `--add-export` settings to restore JDK17 compatibility
  build.gradle
  config/jvm.options
  logstash-core/src/main/java/org/logstash/launchers/JvmOptionsParser.java
  logstash-core/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Labels: status:needs-review

#13926 Doc: Logstash-to-Logstash communication
  docs/index.asciidoc
  docs/static/ls-ls-config.asciidoc
  docs/static/ls-ls-http.asciidoc
  docs/static/ls-ls-lumberjack.asciidoc
Labels: docs, status:approved

#13938 CI: disable testing against 8.1.1 for 8.x
  ci/logstash_releases.json
Labels: status:approved

#13942 Improve safety of stats retrieval from queue
  logstash-core/lib/logstash/api/commands/stats.rb
Labels: status:approved

#13892 [Test] Adds explicit unexpected JVM messages test, and simplifies regex in offline_spec
  qa/integration/specs/cli/prepare_offline_pack_spec.rb
  qa/integration/specs/command_line_spec.rb
Labels: status:approved

#13946 Updates the LogstashService launcher to use the JDK specified
  qa/integration/services/logstash_service.rb
Labels: status:needs-review

#12198 [DOC] precedence between environment variables and yml in docker
  docs/static/docker.asciidoc
Labels: docs, docker, status:changes-requested

#13922 Removal of sys-v init.d scripts
  qa/config/platforms.json
  rakelib/artifacts.rake
Labels: status:approved

#13953 [doc] Remove references to sysv and upstart scripts when running logstash as a service.
  docs/static/running-logstash.asciidoc
  docs/static/shutdown.asciidoc
Labels: docs, status:approved

#13932 Release notes for 7.17.2
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13940 Release notes for 8.1.2
  docs/static/releasenotes.asciidoc
Labels: status:approved

#13965 Bump Logstash version to 7.17.3
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved, v7.17.3

#13966 Adjust versions.yml to reflect new 7.17.2 and 8.1.2 releases
  ci/logstash_releases.json
Labels: status:approved
