Repository elastic/logstash, pull requests merged in 2022-06, with the labels that each got.

#14197 Remove startup.options and system-install docs
  docs/static/setting-up-logstash.asciidoc
Labels: docs, status:approved

#14193 Doc: Add pipeline improvements to release notes
  docs/static/releasenotes.asciidoc
Labels: docs, status:approved

#14159 Fix deprecation logging of password policy.
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/webserver.rb
Labels: status:approved

#14117 Add licence mapping for netty
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/netty-NOTICE.txt
Labels: status:needs-review

#14206 Added necessary require, removed instance variable usage of plugin_name
  lib/pluginmanager/templates/codec-plugin/lib/logstash/codecs/example.rb.erb
  lib/pluginmanager/templates/filter-plugin/lib/logstash/filters/example.rb.erb
  lib/pluginmanager/templates/input-plugin/lib/logstash/inputs/example.rb.erb
  lib/pluginmanager/templates/input-plugin/spec/inputs/example_spec.rb.erb
Labels: plugin issue, status:approved

#14207 Refactor: use Java API for RubyString#split
  logstash-core/spec/logstash/util/buftok_spec.rb
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
Labels: status:approved, refactoring, v8.4.0

#14175 Refactor: avoid loading polyglot
  Gemfile.template
  logstash-core/lib/logstash/compiler/lscl.rb
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.rb
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop
  logstash-core/lib/logstash/compiler/treetop_monkeypatches.rb
  logstash-core/lib/logstash/config/config_ast.rb
  logstash-core/lib/logstash/config/grammar.rb
  logstash-core/lib/logstash/config/grammar.treetop
  logstash-core/lib/logstash/patches/polyglot.rb
  x-pack/qa/integration/spec_helper.rb
Labels: status:approved

#14208 Refactor: drop java.util.Collection#inspect extension
  logstash-core/spec/logstash/java_integration_spec.rb
  logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
Labels: status:approved, refactoring

#14224 Backport PR #14098 to 8.2. Switch adoptopenjdk url to adoptium
  build.gradle
  versions.yml
Labels: backport, status:needs-review, v8.2.3

#14192 Avoid to throw an exception from a finally block
  logstash-core/src/main/java/org/logstash/FileLockFactory.java
Labels: enhancement, code cleanup, status:needs-review

#14236 Add Github Action workflow for release notes generation
  .github/workflows/gen_release_notes.yml
  tools/release/generate_release_notes.rb
Labels: build, status:approved, release

#14229 14203 fix generated plugin dependencies
  .ruby-version
  lib/pluginmanager/generate.rb
  lib/pluginmanager/templates/codec-plugin/.ruby-version
  lib/pluginmanager/templates/codec-plugin/Gemfile
  lib/pluginmanager/templates/codec-plugin/Gemfile.erb
  lib/pluginmanager/templates/codec-plugin/logstash-codec-example.gemspec.erb
  lib/pluginmanager/templates/filter-plugin/.ruby-version
  lib/pluginmanager/templates/filter-plugin/Gemfile
  lib/pluginmanager/templates/filter-plugin/Gemfile.erb
  lib/pluginmanager/templates/filter-plugin/logstash-filter-example.gemspec.erb
  lib/pluginmanager/templates/input-plugin/.ruby-version
  lib/pluginmanager/templates/input-plugin/Gemfile
  lib/pluginmanager/templates/input-plugin/Gemfile.erb
  lib/pluginmanager/templates/input-plugin/logstash-input-example.gemspec.erb
  lib/pluginmanager/templates/output-plugin/.ruby-version
  lib/pluginmanager/templates/output-plugin/Gemfile
  lib/pluginmanager/templates/output-plugin/Gemfile.erb
  lib/pluginmanager/templates/output-plugin/logstash-output-example.gemspec.erb
Labels: bug, status:approved

#14247 Deps: update manticore due JRuby 9.3 issue
  Gemfile.jruby-2.5.lock.release
Labels: status:approved

#14188 Delete consumed DLQ segments and exposes API to acknowledge read events.
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
  logstash-core/src/main/java/org/logstash/common/io/SegmentListener.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Labels: enhancement, DLQ, status:approved

#14252 bump to 8.2.4
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved, release, v8.2.4

#14253 Update releases file to account for 8.2.3
  ci/logstash_releases.json
Labels: status:approved

#14240 Mark all not serializable fields as transient
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/common/AbstractDeadLetterQueueWriterExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/FilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaInputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaOutputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/OutputDelegatorExt.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/OutputStrategyExt.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/execution/ConvergeResultExt.java
  logstash-core/src/main/java/org/logstash/execution/EventDispatcherExt.java
  logstash-core/src/main/java/org/logstash/execution/ExecutionContextExt.java
  logstash-core/src/main/java/org/logstash/execution/JavaBasePipelineExt.java
  logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
  logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
  logstash-core/src/main/java/org/logstash/ext/JRubyWrappedWriteClientExt.java
  logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
  logstash-core/src/main/java/org/logstash/ext/JrubyMemoryReadClientExt.java
  logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java
  logstash-core/src/main/java/org/logstash/ext/JrubyTimestampExtLibrary.java
  logstash-core/src/main/java/org/logstash/ext/JrubyWrappedSynchronousQueueExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/MetricExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/NullMetricExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/SnapshotExt.java
  logstash-core/src/main/java/org/logstash/log/DeprecationLoggerExt.java
  logstash-core/src/main/java/org/logstash/log/LoggerExt.java
  logstash-core/src/main/java/org/logstash/log/SlowLoggerExt.java
  logstash-core/src/main/java/org/logstash/log/StructuredMessage.java
  logstash-core/src/main/java/org/logstash/plugins/factory/ExecutionContextFactoryExt.java
  logstash-core/src/main/java/org/logstash/plugins/factory/PluginFactoryExt.java
  logstash-core/src/main/java/org/logstash/secret/store/backend/JavaKeyStore.java
  tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
Labels: status:approved, java 18 support

#14261 Added description into logstash.yml for sotrage_policy, missed in #13923
  config/logstash.yml
Labels: docs, status:approved

#14266 Pipeline->pipeline workaround for jruby-9.3.4.0 bug
  logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb
  qa/integration/specs/multiple_pipeline_spec.rb
Labels: status:approved

#14212 File system mismatch when each pipeline uses separate file system.
  config/logstash.yml
  docs/static/persistent-queues.asciidoc
  logstash-core/lib/logstash/persisted_queue_config_validator.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
Labels: bug, status:approved

#14272 Print the pipeline id of the queue that's draining
  logstash-core/src/main/java/org/logstash/execution/ShutdownWatcherExt.java
  logstash-core/src/test/resources/shutdown_watcher_ext_pipeline_template.rb
Labels: status:needs-review

#14269 Deps: plugin updates due JRuby issues/warnings
  Gemfile.jruby-2.5.lock.release
Labels: status:approved, v8.3.0

#14274 Fix/dlq avoid to delete not segment files
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
Labels: bug, DLQ, status:approved

#14239 improve resiliency of make venv with retrying pip install
  docker/Makefile
  docker/data/golang/Dockerfile
Labels: build, status:approved

#14279 Rollback jruby version to `9.2.20.1`
  Dockerfile
  Gemfile.jruby-2.5.lock.release
  Gemfile.template
  bin/logstash.lib.sh
  build.gradle
  lib/bootstrap/bundler.rb
  lib/pluginmanager/gem_installer.rb
  lib/pluginmanager/util.rb
  logstash-core/lib/logstash/api/app_helpers.rb
  logstash-core/lib/logstash/compiler/lscl.rb
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.rb
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop
  logstash-core/lib/logstash/compiler/treetop_monkeypatches.rb
  logstash-core/lib/logstash/config/config_ast.rb
  logstash-core/lib/logstash/config/grammar.rb
  logstash-core/lib/logstash/config/grammar.treetop
  logstash-core/lib/logstash/config/lir_serializer.rb
  logstash-core/lib/logstash/patches/polyglot.rb
  logstash-core/lib/logstash/plugins/registry.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/util/cloud_setting_auth.rb
  logstash-core/lib/logstash/util/cloud_setting_id.rb
  logstash-core/lib/logstash/util/modules_setting_array.rb
  logstash-core/lib/logstash/util/time_value.rb
  logstash-core/spec/logstash/util_spec.rb
  logstash-core/spec/support/helpers.rb
  logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java
  logstash-core/src/test/java/org/logstash/config/ir/RubyEnvTestCase.java
  qa/integration/rspec.rb
  qa/integration/specs/command_line_spec.rb
  rakelib/artifacts.rake
  rakelib/compile.rake
  rubyUtils.gradle
  tools/release/bump_plugin_versions.rb
  versions.yml
Labels: status:needs-review

#14260 Deps: un-pin (and avoid) rufus-scheduler
  logstash-core/logstash-core.gemspec
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
Labels: status:needs-review

#14200 Remove /etc/s/s/logstash.service if previously installed by Logstash
  pkg/centos/before-install.sh
  pkg/debian/before-install.sh
  pkg/ubuntu/before-install.sh
Labels: status:approved

#14299 Timestamp#toString(): ensure a minimum of 3 decimal places
  logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb
  logstash-core/src/main/java/org/logstash/Timestamp.java
  logstash-core/src/test/java/org/logstash/TimestampTest.java
Labels: enhancement, status:approved

#14303 Release notes for 7.17.5
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#14302 Build: make sure lock is created in integration specs
  build.gradle
Labels: status:approved

#14298 Support ironbank docker build
  .gitignore
  docker/Makefile
  docker/ironbank/LICENSE
  docker/ironbank/README.md
  docker/ironbank/go/src/env2yaml/go.mod
  docker/ironbank/go/src/env2yaml/go.sum
  docker/ironbank/go/src/env2yaml/vendor/modules.txt
  docker/templates/Dockerfile.j2
  docker/templates/hardening_manifest.yaml
  rakelib/artifacts.rake
Labels: status:approved

#14296 devtools/label: Add initial script that can label issues/PRs
  devtools/label
Labels: status:approved, v8.4.0

#14307 bump version to 8.3.1
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: v8.3.1

#14155 Add `ca_trusted_fingerprint` to core features (monitoring/central-management)
  Gemfile.template
  config/logstash.yml
  docker/data/logstash/env2yaml/env2yaml.go
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings-legacy.asciidoc
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/lib/template.cfg.erb
  x-pack/spec/config_management/extension_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Labels: status:approved

#14312 allow any class in CBOR deserialization
  logstash-core/src/main/java/org/logstash/ObjectMappers.java
Labels: status:needs-review

#14304 Update jruby to 9.3.6.0
  rubyUtils.gradle
  versions.yml
Labels: status:needs-review

#14308 update releases list with new 7.17.5 and 8.3.0
  ci/logstash_releases.json
Labels: status:needs-review

#14311 Release Notes for 8.3.1
  docs/static/releasenotes.asciidoc
Labels: status:approved

#14082 [doc] Removes 'beta' from pipeline viewer doc
  docs/static/monitoring/pipeline-viewer.asciidoc
Labels: status:approved

#14316 Forward port of release notes for `8.3.1` `8.3.0.` `8.2.3` to `main`
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#14255 Implement DLQ age retention policy
  config/logstash.yml
  docker/data/logstash/env2yaml/env2yaml.go
  logstash-core/lib/logstash/environment.rb
  logstash-core/src/main/java/org/logstash/common/DeadLetterQueueFactory.java
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueTestUtils.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
  logstash-core/src/test/java/org/logstash/execution/AbstractPipelineExtTest.java
Labels: DLQ, status:approved
