Repository elastic/logstash, pull requests merged in 2022-10, with the labels that each got.

#14584 Collect all artifacts created and upload to GCP with release-manager
  ci/dra_upload.sh
Labels: DRA

#14532 [DOC] Add a short guide for using Logstash with K8s
  docsk8s/administering/ls-k8s-administering.asciidoc
  docsk8s/administering/ls-k8s-logging.asciidoc
  docsk8s/administering/ls-k8s-stack-monitoring.asciidoc
  docsk8s/administering/ls-k8s-upgrade.asciidoc
  docsk8s/images/gs-cert-files.png
  docsk8s/images/gs-logstash-node-metrics.png
  docsk8s/index.asciidoc
  docsk8s/ls-k8s-recipes.asciidoc
  docsk8s/quick-start/ls-k8s-external-resource.asciidoc
  docsk8s/quick-start/ls-k8s-quick-start.asciidoc
  docsk8s/quick-start/sample-configuration-files.asciidoc
  docsk8s/sample-files/logstash-k8s-qs.zip
  docsk8s/setting-up/ls-k8s-design-for-plugins.asciidoc
  docsk8s/setting-up/ls-k8s-persistent-storage.asciidoc
  docsk8s/setting-up/ls-k8s-secure.asciidoc
  docsk8s/setting-up/ls-k8s-setting-up.asciidoc
  docsk8s/setting-up/ls-k8s-sizing.asciidoc
  docsk8s/troubleshooting/ls-k8s-common-problems.asciidoc
  docsk8s/troubleshooting/ls-k8s-troubleshooting-methods.asciidoc
  docsk8s/troubleshooting/ls-k8s-troubleshooting.asciidoc
Labels: status:needs-review

#14587 Backport dra 8.5
  ci/dra.sh
  ci/dra_aarch64.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
Labels: backport, DRA

#14588 Backport dra 7.17
  ci/dra_aarch64.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
Labels: backport, DRA

#14593 Some ARM machines don't have openjdk11 so resort to the jdk11 alias
  .ci/java-versions.properties
Labels: DRA

#14596 Avoid to upload not created artifacts for Darwin AARCH64 in 7.17
  ci/dra_upload.sh
Labels: DRA

#14571 Extended Flow Metrics
  docs/static/monitoring/monitoring-apis.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/BaseFlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/ExtendedFlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/FlowCapture.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/FlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/FlowMetricRetentionPolicy.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/LazyInstantiatedFlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/SimpleFlowMetric.java
  logstash-core/src/main/java/org/logstash/util/SetOnceReference.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/ExtendedFlowMetricTest.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/NullableLongMetric.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/SimpleFlowMetricTest.java
  logstash-core/src/test/java/org/logstash/util/SetOnceReferenceTest.java
Labels: enhancement, status:approved

#14592 Extract the branch name passed to release-manager from version file
  ci/dra_upload.sh
Labels: DRA

#14485 Adds method and pass the invokation through Java's filter delegator
  docs/static/java-filter.asciidoc
  logstash-core/src/main/java/co/elastic/logstash/api/Filter.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/JavaFilterDelegatorExt.java
Labels: enhancement, status:changes-requested

#14600 Updates DRA scripts to build snapshot artifacts
  ci/dra_aarch64.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
Labels: DRA

#14619 Switch branch slector from major.minor to read the current branch name
  ci/dra_upload.sh
Labels: DRA

#14628 timestamp: respect locale's decimal-style when parsing
  logstash-core/src/main/java/org/logstash/Timestamp.java
  logstash-core/src/test/java/org/logstash/TimestampTest.java
Labels: status:approved

#14626 Re-added execution rights to dra_upload.sh
  ci/dra_upload.sh
Labels: status:approved, DRA

#14636 Fix/dra use another technique to extract branch name
  ci/dra_upload.sh
Labels: DRA

#13621 fix PipelineIR.getPostQueue by accounting for vertex copies
  logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java
  logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java
Labels: status:needs-review

#14639 dra_upload.sh: Leave artifacts under build/
  ci/dra_upload.sh
Labels: status:needs-review

#14645 Avoid to pass SNAPSHOT particle to the version passed to release-manager
  ci/dra_upload.sh
Labels: status:needs-review, DRA

#14646 Follow up PR of #14645, adds version qualifier to the plain version
  ci/dra_upload.sh
Labels: status:needs-review, DRA

#14644 DRA: Handle env variables better
  ci/dra_aarch64.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
Labels: status:approved

#14554 Collect queue growth events and bytes metrics when PQ is enabled.
  docs/static/monitoring/monitoring-apis.asciidoc
  logstash-core/spec/logstash/api/commands/stats_spec.rb
  logstash-core/spec/logstash/api/modules/node_stats_spec.rb
  logstash-core/spec/support/shared_contexts.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/FlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/LazyInstantiatedFlowMetric.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/MetricKeys.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/gauge/LazyDelegatingGauge.java
  qa/integration/specs/monitoring_api_spec.rb
  qa/integration/specs/reload_config_spec.rb
Labels: enhancement, status:changes-requested, v8.6.0

#14654 DRA: Improve shell scripts for debuggability
  ci/dra_aarch64.sh
  ci/dra_common.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
Labels: status:approved

#14667 Exclude jruby's bundler from artifacts
  rakelib/artifacts.rake
Labels: bundler, packaging, status:approved

#14685 DRA - fix dra_upload syntax, breaking builds
  ci/dra_upload.sh
Labels: status:needs-review

#14670 DRA - generalize docker image building
  ci/dra_common.sh
  ci/dra_docker.sh
  ci/dra_x86_64.sh
Labels: status:approved

#14691 bump core version
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#14703 Adds upload of missed docker docker-build-context.tar.gz artifacts
  ci/dra_docker.sh
Labels: status:needs-review, DRA

#14706 DRA - Fix docker image build
  ci/dra_docker.sh
  ci/dra_upload.sh
Labels: status:approved

#14692 update release file 7.17.8
  ci/logstash_releases.json
Labels: status:approved

#14606 [Doc] k8s troubleshooting
  docsk8s/troubleshooting/ls-k8s-common-problems.asciidoc
  docsk8s/troubleshooting/ls-k8s-troubleshooting-methods.asciidoc
Labels: status:approved
