Repository elastic/logstash, pull requests merged in 2023-10, with the labels that each got.

#15344 [buildkite] DRA staging + snapshot pipelines
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
  catalog-info.yaml
Labels: DRA

#15359 Bundle `logstash-integration-logstash` plugin.
  rakelib/plugins-metadata.json
Labels: new plugin

#15365 [DRA] Rename Buildkite metadata for DRA pipelines
  catalog-info.yaml
Labels: DRA

#15369 deps: downgrade jruby, keep updated default-gem dependencies (forward-port #15283)
  NOTICE.TXT
  lib/pluginmanager/util.rb
  logstash-core/logstash-core.gemspec
  rubyUtils.gradle
  spec/unit/plugin_manager/util_spec.rb
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/bigdecimal-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/cgi-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/date-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/ffi-binary-libfixposix-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/io-console-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/mini_mime-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-imap-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-pop-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-protocol-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-smtp-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/reline-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/time-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/timeout-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/uri-NOTICE.txt
  versions.yml
Labels: bug

#15366 [DRA] Remove wait step in buildkite
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/common.sh
Labels: DRA

#15393 [ci] Backport Buildkite DRA pipeline+scripts to 7.17
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/common.sh
  .buildkite/scripts/dra/docker-env-setup.sh
  .buildkite/scripts/dra/docker-env-teardown.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: v7.17.14

#15392 [ci] Backport Buildkite DRA pipeline+scripts to 8.10
  .buildkite/dra/build_docker.sh
  .buildkite/dra/build_packages.sh
  .buildkite/dra/common.sh
  .buildkite/dra/docker-env-setup.sh
  .buildkite/dra/docker-env-teardown.sh
  .buildkite/dra/generatesteps.py
  .buildkite/dra/publish.sh
  .buildkite/dra_pipeline.yml
Labels: v8.10.3

#15398 [ci] Build 7.17 DRA using Ubuntu 20.04
  .buildkite/scripts/dra/generatesteps.py
Labels: DRA

#15406 [ci] Fix backport bug for 8.10 with buildkite DRA
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/common.sh
  .buildkite/scripts/dra/docker-env-setup.sh
  .buildkite/scripts/dra/docker-env-teardown.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: status:approved, ci

#15402 [ci] Initial pull request jobs for buildkite
  .buildkite/pull-requests.json
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/common/container-agent.sh
  catalog-info.yaml
Labels: status:approved, ci

#15413 [ci] Add missing repository in Buildkite PR
  catalog-info.yaml
Labels: status:approved, ci

#15394 Update Guava dependency to 32.1.2
  logstash-core/build.gradle
Labels: status:approved, v8.12.0

#15422 Update core to 8.10.4
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#15423 Bump core to 7.17.15
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#15421 [ci] Improve PR step names for Buildkite
  .buildkite/pull_request_pipeline.yml
Labels: status:approved, ci

#15426 [ci] Don't trigger BK PR jobs on pushes
  catalog-info.yaml
Labels: status:needs-review, ci

#15380 Defines a pipeline to run specs tests on supported plugins
  .buildkite/supported_plugins_test_pipeline.yml
Labels: status:approved

#15430 [ci] Backport Buildkite PR pipeline to 8.11
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/common/container-agent.sh
Labels: backport, status:needs-review, v8.11.0

#15424 Update Logstash core versions in CI after release.
  ci/logstash_releases.json
Labels: status:approved

#15437 [ci] Commit PR based Java unit tests for Buildkite
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/pull-requests/sonar-env.sh
Labels: backport needed, status:approved, ci

#15438 [ci] Add PR it-tests (part 1+2) to Buildkite
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/common/container-agent.sh
Labels: backport needed, status:approved, ci

#15444 Migrate remaining PR jobs to Buildkite
  .buildkite/pull_request_pipeline.yml
Labels: backport needed, status:approved, ci

#15429 [docs] Small typo fixes in README
  README.md
Labels: developer docs, backport needed, status:approved

#15453 [ci] Enable Buildkite PR comments
  catalog-info.yaml
Labels: ci

#15459 [ci] Initial aarch64 Buildkite resource
  catalog-info.yaml
Labels: status:approved, ci

#15460 [ci] Initial aarch64 Buildkite pipeline
  .buildkite/aarch64_pipeline.yml
Labels: backport needed, status:approved, ci

#15474 Remove pinning of psych 5.1.0
  Gemfile.template
Labels: status:approved

#15477 Update JRuby, JDK and Jackson
  logstash-core/logstash-core.gemspec
  versions.yml
Labels: status:needs-review

#15466 [ci] aarch64 Buildkite pipeline part 1
  .buildkite/aarch64_pipeline.yml
  .buildkite/scripts/common/vm-agent.sh
Labels: status:approved, ci

#15486 Option to disable SonarQube with Java Tests
  ci/unit_tests.sh
Labels: tests

#15492 [ci] re-enable Java unit tests on aarch64 pipeline
  .buildkite/aarch64_pipeline.yml
Labels: enhancement

#15473 [ci] aarch64 Buildkite pipeline part 2
  .buildkite/aarch64_pipeline.yml
  .buildkite/scripts/common/vm-agent.sh
  ci/docker_acceptance_tests.sh
Labels: status:work-in-progress, ci

#15507 [ci] Slack notifications for aarch64 pipeline
  catalog-info.yaml
Labels: ci

#15514 Download of JDK from the Elastic catalog instead of Adoptium
  build.gradle
Labels: build, backport needed
