Repository elastic/logstash, pull requests merged in 2023-12, with the labels that each got.

#15650 [ci] Skip Logstash PR checks when docs change
  .buildkite/pull-requests.json
Labels: ci

#15649 Shutdown DLQ segments flusher only if it has been started
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
Labels: bug, DLQ

#15313 Doc: Update Logstash intro and security overview for serverless
  docs/index.asciidoc
  docs/static/security/es-security.asciidoc
Labels: docs, status:needs-review

#15667 Add new 8.12 branch to CI
  catalog-info.yaml
  ci/branches.json
Labels: status:approved, ci

#15670 Update JRuby to 9.4.5.0 (#15531)
  Gemfile.jruby-3.1.lock.release
  rubyUtils.gradle
  versions.yml
Labels: status:needs-review, JRuby 9.4, v8.11.3

#15518 Doc: Add docs for extending integrations with filter-elastic_integrations
  docs/index.asciidoc
  docs/static/ea-integrations.asciidoc
Labels: status:approved

#15671 Update JRuby core to 9.4.5.0 of rubyUtils.gralde
  rubyUtils.gradle
Labels: status:approved

#15666 Update catalog-info.yaml to include testing for 8.12 branch
  catalog-info.yaml
Labels: status:approved

#15688 Update logstash_releases.json to include 7.17.16 and 8.11.3
  ci/logstash_releases.json
Labels: status:needs-review

#15680 Separate scheduling of segments flushes from time
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
Labels: DLQ, status:needs-review

#15691 [ci] Add Java 21 option for multi JDK CI pipeline
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: status:approved, ci

#15668 [ci] Remove hardcoded branches from DRA schedule
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  .buildkite/trigger_pipeline.yml
  catalog-info.yaml
Labels: status:approved, ci

#15694 Remove temporary dependencies in logstash-core.gemspec
  Gemfile.jruby-3.1.lock.release
  logstash-core/logstash-core.gemspec
Labels: status:needs-review

#15700 Bug fix for trigger pipeline Buildkite pipeline
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  .buildkite/trigger_pipeline.yml
Labels: status:needs-review, ci

#15703 [ci] Allow schedule to trigger several pipelines
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  .buildkite/trigger_pipelines.yml
  catalog-info.yaml
Labels: status:needs-review, ci

#15705 Common scheduler pipeline for Buildkite
  catalog-info.yaml
Labels: ci

#15706 Replace Gradle's report.enabled setting to report's required property
  logstash-core/build.gradle
Labels: bug, gradle

#15049 Add log.format to the logstash.yml
  config/logstash.yml
Labels: status:needs-triage

#15708 [ci] Reusable unit + IT test steps for Buildkite
  .buildkite/pull_request_pipeline.yml
Labels: backport needed, status:approved, ci

#15702 Comment docker scan logic to address collected issues later with more experiments.
  .buildkite/scripts/snyk/report.sh
Labels: status:approved

#15711 [ci] Add testing phase to exhaustive tests suite
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci
