Repository elastic/logstash, pull requests merged in 2023-08, with the labels that each got.

#15231 doc: remove breaking change tags
  docs/static/breaking-changes-80.asciidoc
  docs/static/breaking-changes.asciidoc
Labels: docs, status:approved, Team:Docs, v8.10.0, v8.9.1

#15232 [8.9] doc: remove breaking change tags (#15231)
  docs/static/breaking-changes-80.asciidoc
  docs/static/breaking-changes.asciidoc
Labels: status:approved

#15224 Serverless test against restricted API key
  .buildkite/serverless_integration_pipeline.yml
  ci/serverless/README.md
  ci/serverless/common.sh
  ci/serverless/config/logstash.yml
  ci/serverless/cpm_tests.sh
  ci/serverless/kibana_api_tests.sh
  ci/serverless/monitoring_tests.sh
  ci/serverless/pipeline/001_es-output.conf
  ci/serverless/pipeline/002_es-filter.conf
  ci/serverless/pipeline/003_es-input.conf
  ci/serverless/pipeline/004_integration-filter.conf
Labels: status:approved

#15233 Fix DeadLetterQueueWriter unable to finalize segment error
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Labels: status:approved

#15230 Forward port of release notes from 8.9.0
  docs/static/releasenotes.asciidoc
Labels: status:approved

#15173 Pipeline to pipeline communication acked queue improvements.
  logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/AckedReadBatch.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueExceptionMessages.java
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueRuntimeException.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/ext/JRubyAbstractQueueWriteClientExt.java
  logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java
  logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
  logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
  logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java
  logstash-core/src/test/java/org/logstash/util/ExceptionMatcher.java
  logstash-core/src/test/java/org/logstash/util/SetOnceReferenceTest.java
Labels: status:approved

#15252 Fix serverless test for api protection
  .buildkite/serverless_integration_pipeline.yml
  ci/serverless/README.md
  ci/serverless/common.sh
  ci/serverless/cpm_tests.sh
  ci/serverless/dlq_rspec_tests.sh
  ci/serverless/elastic_integration_filter_tests.sh
  ci/serverless/es_output_tests.sh
  ci/serverless/metricbeat/metricbeat.yml
  ci/serverless/metricbeat_monitoring_tests.sh
  ci/serverless/monitoring_tests.sh
  qa/integration/specs/dlq_spec.rb
  qa/integration/specs/spec_helper.rb
Labels: status:approved

#15263 update release version
  ci/logstash_releases.json
Labels: status:needs-review

#15262 Remove unnecessary whitespace from logstash.yml
  config/logstash.yml
Labels: status:needs-triage

#15283 deps: downgrade jruby, keep updated default-gem dependencies
  Gemfile.jruby-3.1.lock.release
  NOTICE.TXT
  lib/pluginmanager/util.rb
  logstash-core/logstash-core.gemspec
  rubyUtils.gradle
  spec/unit/plugin_manager/util_spec.rb
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/cgi-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/date-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/ffi-binary-libfixposix-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/io-console-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-http-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/net-protocol-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/reline-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/time-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/timeout-NOTICE.txt
  tools/dependencies-report/src/main/resources/notices/uri-NOTICE.txt
  versions.yml
Labels: bug, P1, status:approved, Team:Logstash

#15277 disable xpack API and monitoring pipeline for serverless
  x-pack/lib/config_management/elasticsearch_source.rb
  x-pack/lib/license_checker/license_manager.rb
  x-pack/lib/license_checker/license_reader.rb
  x-pack/lib/license_checker/licensed.rb
  x-pack/lib/license_checker/x_pack_info.rb
  x-pack/lib/modules/module_license_checker.rb
  x-pack/lib/monitoring/internal_pipeline_source.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/license_checker/license_manager_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/modules/module_license_checker_spec.rb
  x-pack/spec/monitoring/internal_pipeline_source_spec.rb
  x-pack/spec/support/helpers.rb
Labels: status:approved

#15264 serverless test use minimum privileges per case
  ci/serverless/README.md
  ci/serverless/common.sh
  ci/serverless/config/logstash.yml
  ci/serverless/cpm_tests.sh
  ci/serverless/elastic_integration_filter_tests.sh
  ci/serverless/es_output_tests.sh
  ci/serverless/kibana_api_tests.sh
  ci/serverless/metricbeat_monitoring_tests.sh
  ci/serverless/pipeline/001_es-output.conf
  ci/serverless/pipeline/002_es-filter.conf
  ci/serverless/pipeline/003_es-input.conf
  ci/serverless/pipeline/004_integration-filter.conf
  ci/serverless/test_data/index_template.json
Labels: status:changes-requested
