Repository elastic/logstash, pull requests merged in 2023-11, with the labels that each got.

#15519 [ci] Initial jdk matrix Buildkite resource
  catalog-info.yaml
Labels: ci

#15520 [ci] Initial JDK matrix Buildkite pipeline
  .buildkite/jdk_matrix_pipeline.yml
Labels: backport needed, ci

#15348 geoip: extract database manager to stand-alone feature
  config/logstash.yml
  docs/index.asciidoc
  docs/static/geoip-database-management.asciidoc
  docs/static/geoip-database-management/configuring.asciidoc
  docs/static/geoip-database-management/index.asciidoc
  docs/static/geoip-database-management/metrics.asciidoc
  docs/static/settings/geoip-database-management-settings.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/util.rb
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/database_metric.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/filters/geoip/util.rb
  x-pack/lib/geoip_database_management/constants.rb
  x-pack/lib/geoip_database_management/data_path.rb
  x-pack/lib/geoip_database_management/db_info.rb
  x-pack/lib/geoip_database_management/downloader.rb
  x-pack/lib/geoip_database_management/extension.rb
  x-pack/lib/geoip_database_management/manager.rb
  x-pack/lib/geoip_database_management/metadata.rb
  x-pack/lib/geoip_database_management/metric.rb
  x-pack/lib/geoip_database_management/subscription.rb
  x-pack/lib/geoip_database_management/subscription_observer.rb
  x-pack/lib/geoip_database_management/util.rb
  x-pack/lib/x-pack/logstash_registry.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/geoip_database_management/downloader_spec.rb
  x-pack/spec/geoip_database_management/fixtures/normal_resp.json
  x-pack/spec/geoip_database_management/fixtures/sample.tgz
  x-pack/spec/geoip_database_management/manager_spec.rb
  x-pack/spec/geoip_database_management/metadata_spec.rb
  x-pack/spec/geoip_database_management/spec_helper.rb
  x-pack/spec/geoip_database_management/subscription_spec.rb
  x-pack/spec/support/helpers.rb
Labels: enhancement, status:needs-review

#15512 Update the Logstash to Logstash Native doc to reflect the multiple hosts usage.
  docs/static/ls-ls-config.asciidoc
  docs/static/ls-ls-native.asciidoc
Labels: docs

#15533 [ci] Split JDK matrix resources per OS
  catalog-info.yaml
Labels: ci

#15534 [ci] Split JDK matrix pipelines per OS
  .buildkite/jdk_matrix_pipeline.yml
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: backport needed, ci

#15546 build meta: bump 8.x snapshot to 8.12
  ci/logstash_releases.json
Labels: build, release

#15539 [ci] JDK matrix Buildkite pipelines (part 1)
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
Labels: status:approved, ci

#15535 Fixed functional test in case the LS_JAVA_HOME is configured
  qa/integration/specs/command_line_spec.rb
Labels: status:approved

#15544 [ci] Remove 8.10 scheduled builds for DRA
  catalog-info.yaml
Labels: status:needs-review, DRA

#15563 [ci] JDK matrix Buildkite pipelines (pt 2/Windows)
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
  .buildkite/scripts/jdk-matrix-tests/launch-command.ps1
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: status:approved, ci

#15551 Update 8.x CI to 8.11
  ci/logstash_releases.json
Labels: status:approved

#15579 [Buildkite] Add pipeline max timeout property
  catalog-info.yaml
Labels: status:needs-review, ci

#15584 [ci] Fix image name for Rocky Linux 8
  .buildkite/linux_jdk_matrix_pipeline.yml
Labels: backport needed, status:needs-review, ci, v8.11.2, v7.17.16

#15528 Doc: Add Elastic Agent collection
  docs/index.asciidoc
  docs/static/monitoring/images/integration-agent-add-standalone.png
  docs/static/monitoring/images/integration-agent-add.png
  docs/static/monitoring/images/integration-agent-confirm.png
  docs/static/monitoring/images/integration-assets-dashboards.png
  docs/static/monitoring/images/integration-dashboard-overview.png
  docs/static/monitoring/images/kibana-home.png
  docs/static/monitoring/monitoring-confirm.asciidoc
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
  docs/static/monitoring/monitoring-ea-intro.asciidoc
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-install.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/monitoring/monitoring-overview.asciidoc
  docs/static/monitoring/monitoring-prereq-create-user.asciidoc
  docs/static/monitoring/monitoring-prereq-define-cluster.asciidoc
  docs/static/monitoring/monitoring-prereq-disable-default.asciidoc
  docs/static/monitoring/monitoring-prereq-setup-es.asciidoc
  docs/static/tab-widgets/install-agent-widget.asciidoc
  docs/static/tab-widgets/install-agent.asciidoc
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.rb
  logstash-core/lib/logstash/config/grammar.rb
Labels: docs, status:needs-review

#15565 [Doc] add reference to ECK
  docs/index.asciidoc
  docs/static/running-logstash-kubernetes.asciidoc
  docs/static/setting-up-logstash.asciidoc
Labels: status:approved

#15581 [ci] Add 90min timeout for supported plugins test
  catalog-info.yaml
Labels: status:approved, ci

#15590 [ci] Add yaml language server to pipelines
  .buildkite/aarch64_pipeline.yml
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
  .buildkite/supported_plugins_test_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: backport needed, status:approved, ci

#15591 [ci] Add yaml language server to pipelines (#15590)
  .buildkite/aarch64_pipeline.yml
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: backport, ci

#15582 Update base image on ironbank to 8.8
  docker/templates/Dockerfile.j2
  docker/templates/hardening_manifest.yaml
Labels: status:approved

#15595 [ci] Support amazonlinux for JDK matrix pipeline
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
Labels: backport needed, status:approved, ci

#15592 [ci] Add yaml language server to pipelines (#15590)
  .buildkite/aarch64_pipeline.yml
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: backport, status:needs-review, ci

#15600 [ci] Use GCP prod image for JDK matrix jobs
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
Labels: status:needs-review, ci

#15593 [ci] Enable auto runs of JDK matrix pipelines
  catalog-info.yaml
Labels: status:approved, ci

#15564 Fix issue with Jackson 2.15: Can not write a field name, expecting a value
  logstash-core/src/main/java/org/logstash/ObjectMappers.java
  logstash-core/src/main/java/org/logstash/log/CustomLogEventSerializer.java
  logstash-core/src/main/java/org/logstash/log/RubyBasicObjectSerializer.java
  logstash-core/src/test/java/org/logstash/ObjectMappersTest.java
  logstash-core/src/test/java/org/logstash/log/CustomLogEventTests.java
  logstash-core/src/test/java/org/logstash/log/RubyBasicObjectSerializerTest.java
Labels: status:approved

#15599 swap dataformat-yaml with snakeyaml
  logstash-core/build.gradle
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/java/org/logstash/plugins/aliases/AliasDocumentReplace.java
  logstash-core/src/main/java/org/logstash/plugins/aliases/AliasPlugin.java
Labels: status:approved

#15601 [ci] Explicit maximum timeout for pipelines
  catalog-info.yaml
Labels: status:needs-review, ci

#15609 [ci] Fix slack alerts for Linux JDK matrix pipeline
  catalog-info.yaml
Labels: status:approved, ci

#15608 [ci] Initial Exhaustive tests Buildkite resource
  catalog-info.yaml
Labels: status:approved, ci

#15610 Use proper BK agent and simplify some operations in Snyk report pipeline.
  .buildkite/scripts/snyk/report.sh
  .buildkite/snyk_report_pipeline.yml
  catalog-info.yaml
Labels: enhancement, status:changes-requested, ci

#15619 Doc: Housekeeping changes to monitoring with agent docs
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-view.asciidoc
Labels: docs

#15621 Doc: Improvements to monitoring with agent (#15619) to 8.11
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-view.asciidoc
Labels: docs, backport

#15628 [ci] Switch to Adoptium JDK 17 for Jenkins CI
  .ci/java-versions.properties
Labels: ci

#15629 [ci] Switch to Adoptium distro for JDK 11
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: ci

#15635 [ci] Switch to Adoptium JDK 11 for Jenkins CI
  .ci/java-versions.properties
Labels: backport, ci

#15612 Add support to add and remove multiple keystore keys in a single operation
  docs/static/keystore.asciidoc
  lib/secretstore/cli.rb
  logstash-core/src/main/java/org/logstash/secret/cli/SecretStoreCli.java
  logstash-core/src/test/java/org/logstash/secret/cli/SecretStoreCliTest.java
Labels: status:needs-review

#15627 Add list of active branches for automation
  ci/branches.json
Labels: ci

#15641 [ci] Compatibility tests for Exhaustive suite
  .buildkite/exhaustive_tests_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: ci
