Repository elastic/logstash, pull requests merged in 2023-05, with the labels that each got.

#15034 [DOCS] Fix link to loadbalance in Filebeat ref
  docs/static/deploying.asciidoc
Labels: status:approved, Team:Docs

#14820 Plugin flow docs fixes
  docs/static/monitoring/monitoring-apis.asciidoc
Labels: docs, status:approved

#15045 Add missing Elasticsearch SSL settings and replace deprecated options (xpack.monitoring and xpack.management)
  Gemfile.template
  config/logstash.yml
  docker/data/logstash/env2yaml/env2yaml.go
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
  docs/static/settings/configuration-management-settings.asciidoc
  docs/static/settings/monitoring-settings-legacy.asciidoc
  logstash-core/lib/logstash/modules/logstash_config.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/helpers/elasticsearch_options.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/lib/template.cfg.erb
  x-pack/spec/config_management/extension_spec.rb
  x-pack/spec/helpers/elasticsearch_options_spec.rb
  x-pack/spec/monitoring/pipeline_register_hook_spec.rb
Labels: status:approved

#15059 use setLoadPaths instead of RUBYLIB
  rubyUtils.gradle
Labels: status:needs-review

#15058 [Docs] Add instructions to verify Docker install images
  docs/static/docker.asciidoc
Labels: docs, status:approved, Team:Docs, v8.8.0

#15064 [8.8] [Docs] Add instructions to verify Docker install images (#15058)
  docs/static/docker.asciidoc
Labels: status:needs-review

#15060 Bump 8.8.1
  Gemfile.jruby-2.6.lock.release
  versions.yml
Labels: status:approved

#15061 Update versions used in plugins CI
  ci/logstash_releases.json
Labels: status:approved

#15062 Forward port release notes for 8.8.0
  docs/static/releasenotes.asciidoc
Labels: status:approved
