Repository elastic/logstash, pull requests merged in 2023-07, with the labels that each got.

#15149 Update rubyUtils.gradle to use bundler 2.4.15
  rubyUtils.gradle
Labels: status:needs-review

#15090 [Doc] Add monitoring/management SSL regression note on release 8.8.0
  docs/static/releasenotes.asciidoc
Labels: status:approved

#15126 Bundle ESF forwarder
  rakelib/plugins-metadata.json
Labels: status:approved

#15158 Update puma to version 6.3
  logstash-core/lib/logstash/patches/puma.rb
  logstash-core/lib/logstash/webserver.rb
  logstash-core/logstash-core.gemspec
  logstash-core/spec/logstash/patches/puma_spec.rb
Labels: status:needs-review

#15033 Add initial PQ sizing doc
  docs/static/persistent-queues.asciidoc
Labels: docs, status:approved

#15117 Snyk scans Logstash container vulnerabilities.
  .buildkite/scripts/snyk/report.sh
  .buildkite/scripts/snyk/resolve_stack_version.sh
  catalog-info.yaml
Labels: status:approved

#15166 Add API SSL supported protocols setting
  config/logstash.yml
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/webserver.rb
  logstash-core/spec/logstash/settings/string_array_spec.rb
  qa/integration/specs/webserver_spec.rb
Labels: status:approved

#15174 Enable trailing whitespace formating
  .rubocop.yml
  lib/pluginmanager/command.rb
  lib/pluginmanager/update.rb
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/api/commands/base.rb
  logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb
  logstash-core/lib/logstash/compiler/lscl/helpers.rb
  logstash-core/lib/logstash/compiler/treetop_monkeypatches.rb
  logstash-core/lib/logstash/config/lir_serializer.rb
  logstash-core/lib/logstash/config/pipelines_info.rb
  logstash-core/lib/logstash/instrument/metric_store.rb
  logstash-core/lib/logstash/patches/stronger_openssl_defaults.rb
  logstash-core/lib/logstash/util/thread_dump.rb
  logstash-core/spec/conditionals_spec.rb
  logstash-core/spec/logstash/agent/converge_spec.rb
  logstash-core/spec/logstash/api/modules/plugins_spec.rb
  logstash-core/spec/logstash/codecs/base_spec.rb
  logstash-core/spec/logstash/compiler/compiler_spec.rb
  logstash-core/spec/logstash/config/config_ast_spec.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
  logstash-core/spec/logstash/settings/writable_directory_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/spec/logstash/util/java_version_spec.rb
  qa/acceptance/spec/lib/cli_operation_spec.rb
  qa/integration/framework/settings.rb
  qa/integration/services/monitoring_api.rb
  qa/integration/specs/cli/install_spec.rb
  qa/integration/specs/env_variables_condition_spec.rb
  qa/integration/specs/env_variables_config_spec.rb
  qa/integration/specs/es_output_how_spec.rb
  qa/integration/specs/monitoring_api_spec.rb
  qa/integration/specs/multiple_pipeline_spec.rb
  qa/integration/specs/reload_config_spec.rb
  qa/platform_config.rb
  qa/rspec/commands.rb
  qa/rspec/commands/redhat.rb
  qa/rspec/commands/system_helpers.rb
  qa/vagrant/helpers.rb
  rakelib/plugins_docs_dependencies.rake
  rakelib/test.rake
  spec/unit/plugin_manager/prepare_offline_pack_spec.rb
  tools/paquet/lib/paquet/gem.rb
  x-pack/lib/filters/geoip/database_metadata.rb
  x-pack/lib/filters/geoip/download_manager.rb
  x-pack/lib/monitoring/inputs/metrics.rb
  x-pack/qa/integration/management/multiple_pipelines_spec.rb
  x-pack/qa/integration/support/shared_examples.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/modules/arcsight/arcsight_module_config_spec.rb
  x-pack/spec/modules/azure/filters/azure_event_spec.rb
  x-pack/spec/monitoring/inputs/metrics/state_event/lir_serializer_spec.rb
Labels: status:approved

#15178 Fix Java 8 compatibility issues
  build.gradle
Labels: status:approved, v7.17.12

#15183 Fix instances of deprecated class methods
  .rubocop.yml
  lib/bootstrap/bundler.rb
  lib/bootstrap/environment.rb
  lib/pluginmanager/generate.rb
  lib/pluginmanager/prepare_offline_pack.rb
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/agent_spec.rb
  qa/integration/services/service.rb
  qa/integration/specs/deprecation_log_spec.rb
  qa/integration/specs/env_variables_config_spec.rb
  qa/integration/specs/fatal_error_spec.rb
  qa/integration/specs/kafka_input_spec.rb
  qa/integration/specs/mixed_codec_spec.rb
  qa/integration/specs/pipeline_log_spec.rb
  qa/integration/specs/plugin_name_log_spec.rb
  qa/integration/specs/settings_spec.rb
  qa/integration/specs/slowlog_spec.rb
  rakelib/artifacts.rake
  rakelib/vendor.rake
  x-pack/qa/integration/support/helpers.rb
Labels: status:approved

#15018 Script to run all plugins tests and try an install, rooting in local Logstash
  ci/test_supported_plugins.rb
  ci/test_supported_plugins.sh
Labels: status:approved

#15134 Upgrade dependencies, remove deprecated dependencies.
  Gemfile.jruby-2.5.lock.release
  Gemfile.template
Labels: status:needs-review

#15189 Fix deprecated ERB and BigDecimal instances
  .rubocop.yml
  lib/pluginmanager/proxy_support.rb
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb
  qa/integration/framework/fixture.rb
  tools/logstash-docgen/lib/logstash/docgen/asciidoc_format.rb
  tools/logstash-docgen/lib/logstash/docgen/index.rb
  x-pack/lib/monitoring/monitoring.rb
Labels: status:approved

#15197 Enable SpaceBefore cops
  .rubocop.yml
  lib/pluginmanager/gemfile.rb
  lib/pluginmanager/list.rb
  lib/pluginmanager/update.rb
  lib/pluginmanager/util.rb
  logstash-core/lib/logstash/api/commands/node.rb
  logstash-core/lib/logstash/api/commands/system/plugins_command.rb
  logstash-core/lib/logstash/compiler/treetop_monkeypatches.rb
  logstash-core/lib/logstash/config/config_ast.rb
  logstash-core/lib/logstash/filters/base.rb
  logstash-core/lib/logstash/instrument/periodic_poller/cgroup.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/modules/settings_merger.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/util.rb
  logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
  logstash-core/spec/logstash/agent/metrics_spec.rb
  logstash-core/spec/logstash/environment_spec.rb
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/spec/logstash/filter_delegator_spec.rb
  logstash-core/spec/logstash/filters/base_spec.rb
  logstash-core/spec/logstash/instrument/metric_type/counter_spec.rb
  logstash-core/spec/logstash/java_filter_delegator_spec.rb
  logstash-core/spec/logstash/java_integration_spec.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/json_spec.rb
  logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb
  logstash-core/spec/logstash/modules/kibana_client_spec.rb
  logstash-core/spec/logstash/modules/scaffold_spec.rb
  logstash-core/spec/logstash/modules/settings_merger_spec.rb
  logstash-core/spec/logstash/outputs/base_spec.rb
  logstash-core/spec/logstash/patches/puma_spec.rb
  logstash-core/spec/logstash/pipeline_action/create_spec.rb
  logstash-core/spec/logstash/plugins/ca_trusted_fingerprint_support_spec.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/spec/logstash/util/accessors_spec.rb
  logstash-core/spec/logstash/util/charset_spec.rb
  logstash-core/spec/logstash/util/cloud_setting_id_spec.rb
  logstash-core/spec/logstash/util/safe_uri_spec.rb
  logstash-core/spec/logstash/webserver_spec.rb
  qa/docker/spec/spec_helper.rb
  qa/integration/specs/01_logstash_bin_smoke_spec.rb
  qa/integration/specs/deprecation_log_spec.rb
  qa/integration/specs/mixed_codec_spec.rb
  qa/integration/specs/monitoring_api_spec.rb
  qa/integration/specs/pipeline_log_spec.rb
  qa/integration/specs/plugin_name_log_spec.rb
  qa/integration/specs/slowlog_spec.rb
  qa/platform_config.rb
  qa/rspec/commands.rb
  rakelib/artifacts.rake
  spec/unit/plugin_manager/gemfile_spec.rb
  x-pack/lib/license_checker/license_manager.rb
  x-pack/qa/integration/monitoring/monitoring_is_disabled_spec.rb
  x-pack/spec/config_management/elasticsearch_source_spec.rb
  x-pack/spec/filters/geoip/download_manager_spec.rb
  x-pack/spec/modules/arcsight/arcsight_module_config_spec.rb
Labels: status:approved

#15150 buildkite serverless test
  .buildkite/scripts/setup_java.sh
  .buildkite/serverless_integration_pipeline.yml
  .gitignore
  ci/serverless/common.sh
  ci/serverless/config/logstash.yml
  ci/serverless/cpm_tests.sh
  ci/serverless/dlq_rspec_tests.sh
  ci/serverless/elastic_integration_filter_tests.sh
  ci/serverless/es_filter_tests.sh
  ci/serverless/es_input_tests.sh
  ci/serverless/es_output_tests.sh
  ci/serverless/kibana_api_tests.sh
  ci/serverless/metricbeat/metricbeat.yml
  ci/serverless/metricbeat_monitoring_tests.sh
  ci/serverless/monitoring_tests.sh
  ci/serverless/pipeline/001_es-output.conf
  ci/serverless/pipeline/002_es-filter.conf
  ci/serverless/pipeline/003_es-input.conf
  ci/serverless/pipeline/004_integration-filter.conf
  ci/serverless/pipeline/005_uptime.conf
  ci/serverless/test_data/book.json
  ci/serverless/test_data/index_template.json
  ci/serverless/test_data/ingest_pipeline.json
  ci/serverless/test_data/stdin_stdout.json
  qa/integration/framework/fixture.rb
  qa/integration/services/elasticsearch_service.rb
  qa/integration/specs/dlq_spec.rb
  qa/integration/specs/spec_helper.rb
Labels: status:approved

#15201 Rubocop: Enable most SpaceInside cops
  .rubocop.yml
  lib/bootstrap/patches/jar_dependencies.rb
  lib/bootstrap/rspec.rb
  lib/pluginmanager/generate.rb
  lib/pluginmanager/pack.rb
  lib/pluginmanager/unpack.rb
  logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb
  logstash-core/lib/logstash/api/modules/node.rb
  logstash-core/lib/logstash/config/source_loader.rb
  logstash-core/lib/logstash/dependency_report.rb
  logstash-core/lib/logstash/elasticsearch_client.rb
  logstash-core/lib/logstash/modules/kibana_client.rb
  logstash-core/lib/logstash/plugins/registry.rb
  logstash-core/lib/logstash/util/thread_dump.rb
  logstash-core/spec/conditionals_spec.rb
  logstash-core/spec/logstash/api/commands/default_metadata_spec.rb
  logstash-core/spec/logstash/config/mixin_spec.rb
  logstash-core/spec/logstash/config/source/local_spec.rb
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/spec/logstash/instrument/metric_store_spec.rb
  logstash-core/spec/logstash/modules/cli_parser_spec.rb
  logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb
  logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
  logstash-core/spec/logstash/plugins/event_factory_support_spec.rb
  logstash-core/spec/logstash/settings/array_coercible_spec.rb
  logstash-core/spec/logstash/settings/bytes_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/spec/logstash/util/accessors_spec.rb
  logstash-core/spec/logstash/util_spec.rb
  qa/acceptance/spec/spec_helper.rb
  qa/integration/framework/settings.rb
  qa/integration/integration_tests.gemspec
  qa/integration/services/logstash_service.rb
  qa/integration/specs/fatal_error_spec.rb
  qa/integration/specs/monitoring_api_spec.rb
  rakelib/artifacts.rake
  rakelib/bootstrap.rake
  rakelib/test.rake
  spec/compliance/license_spec.rb
  spec/unit/plugin_manager/install_strategy_factory_spec.rb
  spec/unit/plugin_manager/update_spec.rb
  spec/unit/plugin_manager/util_spec.rb
  spec/unit/util/compress_spec.rb
  tools/logstash-docgen/lib/logstash/docgen/github_generator.rb
  tools/logstash-docgen/lib/logstash/docgen/parser.rb
  tools/logstash-docgen/lib/logstash/docgen/static_parser.rb
  tools/paquet/lib/paquet/utils.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/modules/arcsight/lib/arcsight_module_config_helper.rb
  x-pack/qa/integration/management/read_configuration_spec.rb
  x-pack/qa/integration/support/helpers.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
  x-pack/spec/filters/geoip/database_metadata_spec.rb
  x-pack/spec/filters/geoip/test_helper.rb
  x-pack/spec/license_checker/license_manager_spec.rb
  x-pack/spec/license_checker/license_reader_spec.rb
  x-pack/spec/monitoring/inputs/timer_task_logger_spec.rb
Labels: status:approved

#15202 Fix typo that caused subtitle not to show
  docs/static/persistent-queues.asciidoc
Labels: docs, status:approved

#15216 Update JDK to 11.0.20+8
  versions.yml
Labels: status:approved

#15215 Update JDK to 17.0.8+7
  versions.yml
Labels: status:approved

#15217 Version Bump to 8.9.1
  Gemfile.jruby-2.6.lock.release
  versions.yml
Labels: status:approved

#15218 Version Bump to 7.17.13
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#15219 Update releases.json with latest released versions
  ci/logstash_releases.json
Labels: status:needs-review

#15221 8.9 Release notes updated.
  docs/static/releasenotes.asciidoc
Labels: status:approved
