Repository elastic/logstash, pull requests merged in 2023-02, with the labels that each got.

#14866 bump to 7.17.10
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#14865 update jruby to 9.3.10.0
  versions.yml
Labels: JRuby 9K, status:approved

#14864 set rpm_digest to sha256 instead of default md5
  rakelib/artifacts.rake
Labels: status:approved

#14874 Bump to 8.8.0
  versions.yml
Labels: status:approved

#14875 Copy gem lock file from latest (8.6.1) to 8.7 branch.
  Gemfile.jruby-2.6.lock.release
Labels: status:needs-review

#14879 Bump to 8.6.3
  Gemfile.jruby-2.6.lock.release
  versions.yml
Labels: status:needs-review

#14881 bump snakeyaml to 1.33 in logstash-core
  logstash-core/benchmarks/build.gradle
  logstash-core/build.gradle
  rubyUtils.gradle
  tools/benchmark-cli/build.gradle
  tools/dependencies-report/build.gradle
  tools/ingest-converter/build.gradle
Labels: status:approved

#14886 add license information for snakeyaml
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/org.yaml!snakeyaml-NOTICE.txt
Labels: status:approved

#14890 Workaround for #14873
  rubyUtils.gradle
Labels: status:approved

#14878 Fix DLQ age retention policy to be applied also in case head segment is untouched
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
Labels: bug, DLQ, status:approved

#14899 Skip dependency `Gemfile.lock` during the artifact creation.
  rakelib/artifacts.rake
Labels: packaging, status:needs-review

#14900 Fix inversion of pluginId and pluginType parameteres in DLQ entry creation
  logstash-core/src/main/java/org/logstash/common/AbstractDeadLetterQueueWriterExt.java
  logstash-core/src/test/java/org/logstash/common/AbstractDeadLetterQueueWriterExtTest.java
Labels: bug, DLQ, status:approved

#14912 [Forwardport] `8.6.2` release notes to `8.7` (#14896)
  docs/static/releasenotes.asciidoc
Labels: backport, status:approved

#14914 [Forwardport] `8.6.2` release notes to `main`.
  docs/static/releasenotes.asciidoc
Labels: backport, status:approved

#14894 Unpin bundler to allow 2.4
  build.gradle
  lib/bootstrap/bundler.rb
  spec/unit/bootstrap/bundler_spec.rb
Labels: status:needs-review
