Repository elastic/logstash, pull requests merged in 2023-09, with the labels that each got.

#15302 [Docs] Update build from source instructions in README.md
  README.md
Labels: developer docs

#15292 Bump 7.17.14
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#15294 Bump 8.9.3
  Gemfile.jruby-2.6.lock.release
  versions.yml
Labels: status:needs-review

#15306 buildkite serverless test against main
  catalog-info.yaml
  qa/integration/specs/dlq_spec.rb
Labels: test failure

#15309 Update .ruby-version to jruby-9.2.20.1
  .ruby-version
Labels: status:approved

#15295 Update CI releases after 8.9.2
  ci/logstash_releases.json
Labels: status:needs-review

#15311 Forward port 8.9.2 release notes to 8.10
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#15310 Forward port 8.9.2 release notes to main
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#15312 [CI] Add initial buildkite pipeline for DRA
  .buildkite/dra_pipeline.yml
  catalog-info.yaml
Labels: ci

#15293 Update CI releases after 7.17.13
  ci/logstash_releases.json
Labels: status:needs-review

#15301 Fix NPE when getting native thread id
  logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java
Labels: status:needs-review

#15279 Sonar integration with Java Tests code coverage
  build.gradle
  ci/docker_run.sh
  ci/docker_unit_tests.sh
  ci/unit_tests.sh
  logstash-core/build.gradle
Labels: enhancement, status:changes-requested

#15343 [ci, buildkite] Fix backstage link to logstash ...
  catalog-info.yaml
Labels: DRA

#15210 Expanded the description how to size the memory of the JVM
  docs/static/config-details.asciidoc
Labels: docs, status:needs-review

#15337 [ci] Commit DRA -SNAPSHOT buildkite pipeline
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/common.sh
  .buildkite/scripts/dra/docker-env-setup.sh
  .buildkite/scripts/dra/docker-env-teardown.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: ci

#15352 [DRA,buildkite] Use AWS aarch64 instance type
  .buildkite/scripts/dra/generatesteps.py
Labels: ci

#15345 Clarify Env Variable usage for list-type URI params
  docs/static/env-vars.asciidoc
Labels: docs

#15356 [DRA, buildkite] Use GCP vms for package build step
  .buildkite/scripts/dra/generatesteps.py
Labels: ci
