Repository elastic/logstash, pull requests merged in 2024-09, with the labels that each got.

#16386 Generate Dataset code with meaningful fields names
  logstash-core/src/main/java/org/logstash/config/ir/compiler/ClassFields.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/FieldDefinition.java
Labels: enhancement, status:approved

#16322 Implements safe evaluation of conditional expressions, logging the error without killing the pipeline
  docs/static/event-data.asciidoc
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/ConditionalEvaluationError.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/EventCondition.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/SyntaxFactory.java
  logstash-core/src/main/java/org/logstash/config/ir/compiler/Utils.java
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/test/java/org/logstash/config/ir/compiler/DatasetCompilerTest.java
  logstash-core/src/test/resources/org/logstash/config/ir/cache/pipeline_reuse_baseline.conf
Labels: bug, status:approved

#16420 Update z_rubycheck.rake to no longer inject Xmx1g
  rakelib/z_rubycheck.rake
Labels: status:work-in-progress

#16424 bump core to 8.15.2
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:needs-triage

#16429 Exclude inner event field from ConditionalEvaluationError serialization
  logstash-core/src/main/java/org/logstash/config/ir/compiler/ConditionalEvaluationError.java
Labels: bug, status:needs-triage

#16432 use gnu tar compatible minitar to generate tar artifact
  Gemfile.template
  rakelib/artifacts.rake
Labels: status:needs-review

#16428 bump to 9.0.0 and adapt CI accordingly
  ci/branches.json
  ci/logstash_releases.json
  versions.yml
Labels: status:needs-review

#16436 account for the 8.x branch in DRA publishing task
  .buildkite/scripts/dra/publish.sh
Labels: status:needs-review

#16439 update ci release 7.17.24
  ci/logstash_releases.json
Labels: status:approved

#16421 [CI] benchmark dashboard and pipeline for testing against multiple versions
  .buildkite/benchmark_versions_pipeline.yml
  .buildkite/scripts/benchmark/README.md
  .buildkite/scripts/benchmark/all.sh
  .buildkite/scripts/benchmark/config/uuid
  .buildkite/scripts/benchmark/main.sh
  .buildkite/scripts/benchmark/save-objects/README.md
  .buildkite/scripts/benchmark/save-objects/benchmark_objects.ndjson
  .buildkite/scripts/benchmark/setup/alias
  .buildkite/scripts/benchmark/setup/benchmark_summary_v2
  .buildkite/scripts/benchmark/util.sh
  catalog-info.yaml
Labels: status:needs-triage

#16446 Make health report test runner script executable.
  .buildkite/scripts/health-report-tests/main.sh
Labels: status:approved

#16443 Drop JDK 11 support
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
  config/jvm.options
  docs/static/jvm.asciidoc
  docs/static/running-logstash-windows.asciidoc
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/src/main/java/org/logstash/util/JavaVersion.java
  tools/jvm-options-parser/src/main/java/org/logstash/launchers/JavaVersion.java
  tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
Labels: enhancement, status:approved

#16447 [CI] fix benchmark marathon
  .buildkite/benchmark_marathon_pipeline.yml
  .buildkite/scripts/benchmark/all.sh
  .buildkite/scripts/benchmark/core.sh
  .buildkite/scripts/benchmark/main.sh
  .buildkite/scripts/benchmark/marathon.sh
  .buildkite/scripts/benchmark/save-objects/CHANGELOG.md
  .buildkite/scripts/benchmark/save-objects/benchmark_objects.ndjson
  catalog-info.yaml
Labels: status:approved

#16455 Known issue for 8.15.1 related to env vars references
  docs/static/releasenotes.asciidoc
Labels: status:approved

#16465 [CI] fix wrong queue type in benchmark marathon
  .buildkite/scripts/benchmark/marathon.sh
Labels: status:approved

#16473 Bump 8.15.3
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#16474 Updated CI releases inventory after 8.15.2
  ci/logstash_releases.json
Labels: status:approved
