Repository elastic/logstash, pull requests merged in 2024-07, with the labels that each got.

#16271 Add retries to aarch64 CI pipeline
  .buildkite/aarch64_pipeline.yml
Labels: enhancement, backport needed, status:approved, ci

#16263 Add Ubuntu 24.04 to CI
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:needs-review

#16274 move j2 template to erb in 7.17
  Gemfile.template
  docker/Makefile
  docker/bin/pytest
  docker/requirements.txt
  docker/templates/Dockerfile.erb
  docker/templates/hardening_manifest.yaml.erb
  docker/tox.ini
Labels: status:needs-review

#16281 bump version to 8.16.0
  versions.yml
Labels: status:approved

#16265 add flow-informed tuning guidance
  docs/static/performance-checklist.asciidoc
Labels: docs, status:approved

#16288 Bump 8.14.3
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:work-in-progress

#16286 Forwardport Release notes for 8.14.2 to main (#16266)
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#16285 Forwardport Release notes for 8.14.2 to 8.15 (#16266)
  docs/static/releasenotes.asciidoc
Labels: status:needs-review

#16287 bump ci releases for 8.14.2
  ci/logstash_releases.json
Labels: status:work-in-progress

#16293 Remove CentOS 7 from CI
  .buildkite/linux_jdk_matrix_pipeline.yml
Labels: backport needed, status:approved, ci

#16299 Add Ubuntu 24.04 to CI
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: backport needed, status:approved, ci

#16308 [CI] fix benchmark to pull snapshot version
  .buildkite/scripts/benchmark/main.sh
Labels: status:approved

#16311 Revert 8.14.3 lock
  Gemfile.jruby-3.1.lock.release
Labels: status:needs-triage, v8.14.3

#16313 Json normalization performance
  logstash-core/lib/logstash/json.rb
  logstash-core/lib/logstash/util/unicode_normalizer.rb
  spec/compliance/license_spec.rb
Labels: performance regression, status:approved

#16300 Remove Debian 10 from CI
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: backport needed, status:approved, ci

#16277 Doc: Update headers for plugins (LSR)
  docs/include/filter.asciidoc
  docs/include/input.asciidoc
  docs/include/output.asciidoc
  docs/include/plugin_header-core.asciidoc
  docs/include/plugin_header-integration.asciidoc
  docs/include/plugin_header.asciidoc
Labels: docs, status:needs-triage

#16305 Bump 8.14.4
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:needs-triage

#16306 Update logstash_releases.json after 8.14.3
  ci/logstash_releases.json
Labels: status:approved

#16329 Backport PR #16300 to 7.17: Remove Debian 10 from CI (#16300)
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: backport, status:needs-triage, ci

#16328 Backport PR #16300 to 8.14: Remove Debian 10 from CI (#16300)
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: backport, status:needs-triage, ci

#16331 regenerate webserver test certificates
  qa/integration/fixtures/webserver_certs/generated/intermediate-ca.crt
  qa/integration/fixtures/webserver_certs/generated/intermediate-ca.key
  qa/integration/fixtures/webserver_certs/generated/root.crt
  qa/integration/fixtures/webserver_certs/generated/root.key
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.chain.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.jks
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.key
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.p12
  qa/integration/fixtures/webserver_certs/generated/server_from_root.chain.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_root.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_root.jks
  qa/integration/fixtures/webserver_certs/generated/server_from_root.key
  qa/integration/fixtures/webserver_certs/generated/server_from_root.p12
Labels: status:approved

#16323 make pipeline resilient to stack overflow during compilation
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: status:approved

#16335 Doc: Reposition worker-utilization in doc
  docs/static/monitoring/monitoring-apis.asciidoc
Labels: status:approved

#16339 settings: add support for observing settings after post-process hooks
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
Labels: bug, status:approved

#16343 add retries to snyk buildkite job
  .buildkite/snyk_report_pipeline.yml
Labels: status:needs-review, buildkite

#16363 Fix 8.13.1 release notes
  docs/static/releasenotes.asciidoc
Labels: status:approved

#16347 Update logstash_releases.json
  ci/logstash_releases.json
Labels: status:work-in-progress
