Repository elastic/logstash, pull requests merged in 2024-10, with the labels that each got.

#16485 Change SubstitutionVariables.replace_placeholders `refine` argument to optional
  logstash-core/lib/logstash/util/substitution_variables.rb
Labels: status:approved

#15679 [Spacetime] Reimplement config Setting classe in java
  config/log4j2.properties
  logstash-core/lib/logstash/settings.rb
  logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
  logstash-core/src/main/java/org/logstash/settings/Boolean.java
  logstash-core/src/main/java/org/logstash/settings/Coercible.java
  logstash-core/src/main/java/org/logstash/settings/DeprecatedAlias.java
  logstash-core/src/main/java/org/logstash/settings/NullableSetting.java
  logstash-core/src/main/java/org/logstash/settings/Setting.java
  logstash-core/src/main/java/org/logstash/settings/SettingDelegator.java
  logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java
  logstash-core/src/test/java/org/logstash/settings/BooleanTest.java
  qa/integration/specs/monitoring_api_spec.rb
Labels: enhancement, status:approved, spacetime

#16489 Use jruby-9.4.8.0 in exhaustive CIs.
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:needs-triage, ci

#16423 DLQ-ing events that trigger an conditional evaluation error.
  docs/static/dead-letter-queues.asciidoc
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: enhancement, DLQ, status:needs-triage

#16496 Fix jdk21 warnings
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
  logstash-core/src/main/java/org/logstash/settings/Coercible.java
  logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java
Labels: status:needs-triage

#16499 Don't use an older JRuby with oraclelinux-7
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci

#16497 Pin CI container images to v0.4 for 7.17 branch
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci

#16316 [ci] Skip slack for retries JDK matrix jobs
  catalog-info.yaml
Labels: status:approved, ci

#16466 Failure injector plugin implementation.
  qa/support/logstash-integration-failure_injector/README.md
  qa/support/logstash-integration-failure_injector/lib/logstash/filters/failure_injector.rb
  qa/support/logstash-integration-failure_injector/lib/logstash/outputs/failure_injector.rb
  qa/support/logstash-integration-failure_injector/lib/logstash/utils/failure_injector_util.rb
  qa/support/logstash-integration-failure_injector/logstash-integration-failure_injector-0.0.1.gem
  qa/support/logstash-integration-failure_injector/logstash-integration-failure_injector.gemspec
  qa/support/logstash-integration-failure_injector/spec/unit/failure_injector_spec.rb
Labels: status:approved

#16484 fix snapshot branch detection for snyk
  .buildkite/scripts/snyk/report.sh
  .buildkite/scripts/snyk/resolve_stack_version.sh
Labels: status:approved

#16506 Avoid to access Java DeprecatedAlias value other than Ruby's one
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/settings_spec.rb
Labels: status:approved

#16510 install jdk 11 in agent for snyk 7.17 scanning
  .buildkite/scripts/snyk/report.sh
Labels: status:needs-review

#16467 Health report integration tests bootstrapper and initial tests implementation
  .buildkite/scripts/health-report-tests/README.md
  .buildkite/scripts/health-report-tests/__init__.py
  .buildkite/scripts/health-report-tests/bootstrap.py
  .buildkite/scripts/health-report-tests/config/pipelines.yml
  .buildkite/scripts/health-report-tests/config_validator.py
  .buildkite/scripts/health-report-tests/logstash_health_report.py
  .buildkite/scripts/health-report-tests/main.py
  .buildkite/scripts/health-report-tests/main.sh
  .buildkite/scripts/health-report-tests/requirements.txt
  .buildkite/scripts/health-report-tests/scenario_executor.py
  .buildkite/scripts/health-report-tests/tests/abnormal-termination.yaml
  .buildkite/scripts/health-report-tests/tests/normal-termination.yaml
  .buildkite/scripts/health-report-tests/tests/slow-start.yaml
  .buildkite/scripts/health-report-tests/util.py
Labels: status:approved

#16507 add deprecation log for `--event_api.tags.illegal`
  logstash-core/lib/logstash/patches/clamp.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/runner_spec.rb
Labels: status:approved

#16518 docs: health report API, and diagnosis links (feature-targeted)
  docs/static/monitoring/monitoring-apis.asciidoc
  docs/static/troubleshoot/health-pipeline-status.asciidoc
  docs/static/troubleshoot/troubleshooting.asciidoc
Labels: docs, status:needs-review

#16519 merge 8.x into feature branch...
  .buildkite/health_report_tests_pipeline.yml
  .buildkite/scripts/health-report-tests/main.sh
  catalog-info.yaml
  docs/static/dead-letter-queues.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/patches/clamp.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: status:needs-review

#16521 Fix QA failure introduced by Health API changes and update rspec dependency of the QA package.
  qa/Gemfile
  qa/docker/spec/spec_helper.rb
Labels: tests, status:approved, ci

#16525 [test] Fix xpack test to check for http_address stats only if the webserver is enabled
  x-pack/spec/monitoring/inputs/metrics/stats_event_factory_spec.rb
Labels: enhancement, status:approved

#16533 Health api minor followups
  .buildkite/health_report_tests_pipeline.yml
  .buildkite/scripts/health-report-tests/bootstrap.py
  .buildkite/scripts/health-report-tests/main.sh
  .buildkite/scripts/health-report-tests/util.py
  qa/docker/shared_examples/container.rb
Labels: status:work-in-progress

#16535 health: add `logstash.forceApiStatus: green` escape hatch
  logstash-core/src/main/java/org/logstash/health/HealthObserver.java
  logstash-core/src/test/java/org/logstash/health/HealthObserverTest.java
Labels: status:approved

#16532 Flow worker utilization probe
  docs/static/troubleshoot/health-pipeline-flow-worker-utilization.asciidoc
  docs/static/troubleshoot/troubleshooting.asciidoc
  logstash-core/lib/logstash/agent.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/health/PipelineIndicator.java
  logstash-core/src/main/java/org/logstash/health/Probe.java
  logstash-core/src/test/java/org/logstash/health/PipelineIndicatorTest.java
Labels: enhancement, status:needs-review

#16545 refactor deprecation log event_api.tags.illegal
  logstash-core/lib/logstash/patches/clamp.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/runner_spec.rb
Labels: status:needs-triage

#16544 docs: add health details for flow/worker_utilization
  docs/static/monitoring/monitoring-apis.asciidoc
Labels: docs, status:approved

#16548 add modules deprecation log for netflow, fb_apache and azure
  logstash-core/lib/logstash/config/modules_common.rb
  modules/netflow/configuration/logstash/netflow.conf.erb
  x-pack/modules/azure/configuration/logstash/azure.conf.erb
Labels: status:approved

#16554 Doc: Update 8.15.0 release notes to future proof link
  docs/static/releasenotes.asciidoc
Labels: docs, status:needs-triage

#16498 Log deprecation warn if memory buffer type not defined
  config/logstash.yml
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
Labels: status:approved

#16550 [Health API] Add 1-min, 5-min backpressure and multipipeline test cases.
  .buildkite/scripts/health-report-tests/bootstrap.py
  .buildkite/scripts/health-report-tests/config_validator.py
  .buildkite/scripts/health-report-tests/main.py
  .buildkite/scripts/health-report-tests/scenario_executor.py
  .buildkite/scripts/health-report-tests/tests/abnormal-termination.yaml
  .buildkite/scripts/health-report-tests/tests/backpressure-1m.yaml
  .buildkite/scripts/health-report-tests/tests/backpressure-5m.yaml
  .buildkite/scripts/health-report-tests/tests/multipipeline.yaml
  .buildkite/scripts/health-report-tests/tests/normal-termination.yaml
  .buildkite/scripts/health-report-tests/tests/slow-start.yaml
Labels: status:needs-triage

#16551 Deprecate for removal ArcSight module
  logstash-core/lib/logstash/config/modules_common.rb
  x-pack/modules/arcsight/configuration/logstash/arcsight.conf.erb
Labels: status:approved

#16560 Update branches.json to point to 8.16 branch
  ci/branches.json
Labels: status:approved

#16461 Remove event_api.tags.illegal for v9
  docker/data/logstash/env2yaml/env2yaml.go
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/src/main/java/org/logstash/Event.java
  logstash-core/src/test/java/org/logstash/EventTest.java
  qa/integration/specs/reserved_tags_field_spec.rb
Labels: status:approved

#16553 Marked ArcSight Module as deprecated in documentation.
  docs/static/arcsight-module.asciidoc
Labels: docs, status:approved

#16565 ensure minitar 1.x is used instead of 0.x
  Gemfile.template
  logstash-core/logstash-core.gemspec
Labels: status:approved

#16561 Add lockfile from 8.15 branch
  Gemfile.jruby-3.1.lock.release
Labels: status:approved

#16482 Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
Labels: bug, status:needs-triage

#16564 Adds a JMH benchmark to test BufferedTokenizerExt class
  logstash-core/benchmarks/build.gradle
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/BufferedTokenizerExtBenchmark.java
Labels: enhancement, status:needs-triage

#16573 Bump 8.15.4
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:work-in-progress

#16538 add http.* deprecation log
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
  logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
  logstash-core/src/main/java/org/logstash/settings/DeprecatedAlias.java
  logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java
Labels: status:approved

#16464 default to jdk21 on all ci/build tasks
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/setup_java.sh
  .buildkite/windows_jdk_matrix_pipeline.yml
  .ci/java-versions.properties
Labels: status:needs-review

#16581 Updated CI releases inventory after 8.15.3
  ci/logstash_releases.json
Labels: status:changes-requested

#16578 Enable log.format.json.fix_duplicate_message_fields by default
  config/logstash.yml
  docs/static/running-logstash-command-line.asciidoc
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
Labels: status:approved

#16589 Updated CI releases inventory after 7.17.25
  ci/logstash_releases.json
Labels: status:approved

#16577 Backport #16482 to 7.17: Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
Labels: backport, status:approved, v7.17.26

#16593 Update the golang references for the Ironbank distro
  docker/templates/Dockerfile.erb
  docker/templates/hardening_manifest.yaml.erb
Labels: status:approved

#16592 Bump version to 8.17.0
  versions.yml
Labels: status:work-in-progress

#16597 make max inflight warning global to all pipelines
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/pipeline_resource_usage_validator.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/pipeline_resource_usage_validator_spec.rb
Labels: status:approved

#16614 [CI] Change agent for JDK availability check and add schedule also for 8.x
  .buildkite/jdk_availability_check_pipeline.yml
  catalog-info.yaml
Labels: ci, buildkite

#16558 set `allow_superuser` to false as default
  .buildkite/pull_request_pipeline.yml
  docs/static/settings-file.asciidoc
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/spec/logstash/runner_spec.rb
Labels: status:needs-triage

#16603 Doc: Reset breaking changes and release notes for 9.0
  docs/static/breaking-changes-70.asciidoc
  docs/static/breaking-changes-80.asciidoc
  docs/static/breaking-changes-90.asciidoc
  docs/static/breaking-changes.asciidoc
  docs/static/redirects.asciidoc
  docs/static/releasenotes.asciidoc
Labels: docs, status:work-in-progress
