Repository elastic/logstash, pull requests merged in 2024-12, with the labels that each got.

#16719 ensure jackson overrides are available to static initializers
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/util/jackson.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/spec/logstash/util/jackson_spec.rb
  logstash-core/src/main/java/org/logstash/ObjectMappers.java
  logstash-core/src/main/java/org/logstash/jackson/StreamReadConstraintsUtil.java
  logstash-core/src/test/java/org/logstash/jackson/StreamReadConstraintsUtilTest.java
  logstash-core/src/test/java/org/logstash/log/LogstashConfigurationFactoryTest.java
  logstash-core/src/test/java/org/logstash/log/PluginDeprecationLoggerTest.java
  logstash-core/src/test/resources/log4j2-log-stream-read-constraints.xml
Labels: status:needs-review

#16765 Add `x-elastic-product-origin` header to Kibana requests
  logstash-core/lib/logstash/modules/kibana_client.rb
  logstash-core/spec/logstash/modules/kibana_client_spec.rb
Labels: enhancement, status:needs-review

#16766 Update serverless tests to include product origin header
  ci/serverless/common.sh
  ci/serverless/cpm_tests.sh
  ci/serverless/elastic_integration_filter_tests.sh
  ci/serverless/es_output_tests.sh
  ci/serverless/kibana_api_tests.sh
  ci/serverless/metricbeat_monitoring_tests.sh
  ci/serverless/monitoring_tests.sh
Labels: developer support, status:needs-review

#16798 Doc: Update security docs to replace obsolete cacert setting
  docs/static/security/es-security.asciidoc
Labels: docs

#16811 Fix docs dependencies link in 8.16.2 release notes
  docs/static/releasenotes.asciidoc
Labels: docs

#16786 Avoid lock when ecs_compatibility is explicitly specified
  logstash-core/lib/logstash/plugins/ecs_compatibility_support.rb
Labels: bug

#16831 Doc: Add json_lines known issue to release notes
  docs/static/releasenotes.asciidoc
Labels: docs
