Repository elastic/logstash, pull requests merged in 2024-02, with the labels that each got.

#15895 Add Debian 12 to CI
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
Labels: status:needs-review, ci

#15901 Add retries to acceptance/docker steps in BK
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci

#15905 Backport PR #15900 to 7.17: Fix service startup with acceptance tests #15905
  qa/acceptance/spec/shared_examples/installed.rb
  qa/acceptance/spec/shared_examples/installed_with_jdk.rb
  qa/rspec/commands.rb
  qa/rspec/commands/base.rb
Labels: backport, status:needs-review, ci

#15909 Version bump to 8.12.2
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#15906 Version bump 7.17.19
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:needs-review

#15911 Update CI release file after releases.
  ci/logstash_releases.json
Labels: status:approved

#15915 Fix the lastes 8.12 version, to the actually latest released
  ci/logstash_releases.json
Labels: status:approved

#15918 Update docs-preview link
  .github/workflows/add-docs-preview-link.yml
Labels: status:approved

#15921 introduce go.mod for env2yaml
  docker/Makefile
  docker/data/golang/Dockerfile
  docker/data/logstash/env2yaml/go.mod
  docker/data/logstash/env2yaml/go.sum
Labels: status:approved

#15925 Set Netty's maxOrder options to previous default
  tools/jvm-options-parser/build.gradle
  tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
  tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Labels: bug, status:approved

#15842 Updates JDK bundled in Logstash
  versions.yml
Labels: status:approved

#15142 Remove jinja2 in favor of erb templates
  docker/Makefile
  docker/bin/pytest
  docker/requirements.txt
  docker/templates/Dockerfile.erb
  docker/templates/hardening_manifest.yaml.erb
  docker/tox.ini
Labels: status:needs-review

#15929 add openssl to ubi image
  docker/Makefile
  docker/templates/Dockerfile.erb
  rakelib/artifacts.rake
Labels: status:approved

#15926 Clean up left over scripts after CI migration
  ci/docker_integration_tests.sh
  ci/docker_license_check.sh
  ci/docker_prune.sh
  ci/docker_run.sh
  ci/docker_unit_tests.sh
  ci/dra_common.sh
  ci/dra_docker.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
  qa/Vagrantfile
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  x-pack/ci/docker_integration_tests.sh
  x-pack/ci/docker_unit_tests.sh
Labels: status:approved, ci

#15924 ci: provide metadata about releases that are in-flight
  ci/logstash_releases.json
Labels: status:approved, ci

#15936 Clean up left over scripts after CI migration (#15926)
  ci/docker_integration_tests.sh
  ci/docker_license_check.sh
  ci/docker_prune.sh
  ci/docker_run.sh
  ci/docker_unit_tests.sh
  ci/dra_common.sh
  ci/dra_docker.sh
  ci/dra_upload.sh
  ci/dra_x86_64.sh
  qa/Vagrantfile
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  x-pack/ci/docker_integration_tests.sh
  x-pack/ci/docker_unit_tests.sh
Labels: backport, status:needs-review, ci

#15938 add 8.13 branch for release
  ci/branches.json
Labels: status:approved

#15935 bump version to 8.14.0
  versions.yml
Labels: status:approved

#15769 Package `elastic_integration` plugin.
  lib/pluginmanager/remove.rb
  rakelib/artifacts.rake
  rakelib/default_plugins.rb
  rakelib/plugin.rake
  rakelib/plugins-metadata.json
Labels: status:approved

#15946 Fix packaging service check failures
  qa/rspec/commands/system_helpers.rb
Labels: test failure, status:approved

#15907 Follow up to #15900 -- fix remaining acceptance tests
  qa/acceptance/spec/lib/artifact_composition_spec.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/generate.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/install.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/list.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb
  qa/acceptance/spec/shared_examples/cli/logstash/version.rb
  qa/acceptance/spec/shared_examples/running.rb
  qa/acceptance/spec/shared_examples/updated.rb
Labels: status:approved, ci

#15954 [CI] [Sonar] Explicitly specified test sources for sonar
  sonar-project.properties
Labels: enhancement, status:approved

#15957 Added :jvm-options-parser subproject to the javaTests task
  build.gradle
  tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Labels: status:approved

#15961 bump jruby to 9.4.6.0 and remove ffi workaround
  rubyUtils.gradle
  versions.yml
Labels: status:approved, JRuby 9.4

#15960 Fix failing DLQ test due to time scheduling
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
Labels: bug, DLQ, status:approved

#15966 Bump to 8.12.3
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:needs-review

#15964 Add shutdown step of DLQ flusher scheduled service
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
Labels: enhancement, DLQ, status:needs-review
