Repository elastic/logstash, pull requests merged in 2024-06, with the labels that each got.

#16180 Bundle integration-snmp and remove input-snmp and input-snmptrap from default plugins/docs
  rakelib/plugins-metadata.json
Labels: status:approved

#16179 Update log4j rollover to configure time retention
  config/log4j2.properties
  docs/static/logging.asciidoc
Labels: enhancement, docs, logging improvements, status:approved

#16201 Revert pr #16050
  logstash-core/lib/logstash/config/source/multi_local.rb
  logstash-core/spec/logstash/config/source/multi_local_spec.rb
Labels: status:work-in-progress

#16185 Update logstash_releases.json to account for 7.17.22
  ci/logstash_releases.json
Labels: status:approved

#16208 Logstash monitoring doc improvements.
  docs/static/monitoring/images/monitoring-ui.png
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-internal-legacy.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/monitoring/monitoring-prereq-disable-default.asciidoc
  docs/static/monitoring/monitoring-prereq-setup-es.asciidoc
Labels: docs, status:approved

#16195 Introduce filesystem signalling from DLQ read to writer to update byte size metric accordingly when the reader uses `clean_consumed`
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
Labels: bug, status:approved

#16194 p2p: adds opt-in pipeline bus with less synchronization
  logstash-core/build.gradle
  logstash-core/lib/logstash/agent.rb
  logstash-core/spec/logstash/plugins/builtin/pipeline_input_output_spec.rb
  logstash-core/src/main/java/org/logstash/plugins/pipeline/AbstractPipelineBus.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/AddressState.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBusV1.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBusV2.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineInput.java
  logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineOutput.java
  logstash-core/src/test/java/org/logstash/plugins/pipeline/PipelineBusTest.java
Labels: status:approved

#16189 Carry fwd pr #16116: add wolfi to exhaustive tests
  .buildkite/scripts/exhaustive-tests/generate-steps.py
  ci/docker_acceptance_tests.sh
  docker/Makefile
  docker/templates/Dockerfile.erb
  qa/docker/shared_examples/container.rb
  qa/docker/spec/spec_helper.rb
  qa/docker/spec/wolfi/container_spec.rb
  qa/docker/spec/wolfi/image_spec.rb
  rakelib/artifacts.rake
Labels: status:approved

#16222 Geoip database management cache invalidation
  x-pack/lib/filters/geoip/database_manager.rb
  x-pack/spec/filters/geoip/database_manager_spec.rb
Labels: status:needs-review

#16224 remove version pinning from rexml
  Gemfile.template
Labels: status:needs-review

#16220 Allow bot triggered PRs to run CI
  .buildkite/pull-requests.json
Labels: status:approved, ci, buildkite

#16245 [Test]Avoid mocking the value returned in global SETTINGS constant
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: enhancement, status:needs-review

#16247 Update ironbank UBI version
  docker/templates/Dockerfile.j2
  docker/templates/hardening_manifest.yaml
Labels: status:approved

#16204 Avoid to log file not found errors when DLQ segments are removed concurrently between writer and reader.
  logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueReader.java
Labels: bug, status:needs-review

#16213 json: remove unnecessary dup/freeze in serialization
  logstash-core/lib/logstash/json.rb
Labels: status:approved

#16191 [CI] Benchmark pipeline
  .buildkite/benchmark_pipeline.yml
  .buildkite/scripts/benchmark/main.sh
  .buildkite/scripts/benchmark/util.sh
Labels: status:approved

#16250 Pin fileutils version to 1.7+
  Gemfile.template
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/fileutils-NOTICE.txt
Labels: bug, status:approved

#16259 Backport 16250 8.14
  Gemfile.template
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/fileutils-NOTICE.txt
Labels: status:approved

#16205 Adding quotes in pqcheck.bat to support spaces in path
  bin/pqcheck.bat
Labels: bug, status:needs-review

#16252 produce wolfi docker image in ci
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/common.sh
Labels: status:needs-review

#16255 Add `RubyEvent#dup` support and unit test case to keep `Json#dump(Event)` safe.
  logstash-core/spec/logstash/event_spec.rb
  logstash-core/spec/logstash/json_spec.rb
  logstash-core/src/main/java/org/logstash/ext/JrubyEventExtLibrary.java
Labels: bug, status:approved

#16264 Ensure pipeline metrics are cleared on the shutdown
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/spec/logstash/java_pipeline_spec.rb
Labels: status:approved

#16268 Doc: Add ecs and datastream requirement for intg filter
  docs/static/ea-integrations.asciidoc
Labels: status:approved
