Repository elastic/logstash, pull requests merged in 2024-05, with the labels that each got.

#16121 bump core to 8.13.4
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:needs-review

#16123 update ci release
  ci/logstash_releases.json
Labels: status:approved

#16130 force ruby-maven-libs constraint to >= 3.9.6.1
  Gemfile.template
Labels: status:needs-review

#16138 Update junit 4 13
  logstash-core/build.gradle
  logstash-core/src/test/java/org/logstash/FieldReferenceTest.java
  logstash-core/src/test/java/org/logstash/ValuefierTest.java
  logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
  logstash-core/src/test/java/org/logstash/common/ConfigVariableExpanderTest.java
  logstash-core/src/test/java/org/logstash/config/ir/PipelineConfigTest.java
  logstash-core/src/test/java/org/logstash/config/ir/PipelineIRTest.java
  logstash-core/src/test/java/org/logstash/config/ir/graph/BooleanEdgeTest.java
  logstash-core/src/test/java/org/logstash/config/ir/graph/EdgeTest.java
  logstash-core/src/test/java/org/logstash/config/ir/graph/GraphTest.java
  logstash-core/src/test/java/org/logstash/config/ir/graph/IfVertexTest.java
  logstash-core/src/test/java/org/logstash/config/ir/graph/PluginVertexTest.java
  logstash-core/src/test/java/org/logstash/execution/ObservedExecutionTest.java
  logstash-core/src/test/java/org/logstash/ext/JrubyEventExtLibraryTest.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/ExtendedFlowMetricTest.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/SimpleFlowMetricTest.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/timer/TimerMetricTest.java
  logstash-core/src/test/java/org/logstash/secret/store/SecretStoreFactoryTest.java
  logstash-core/src/test/java/org/logstash/secret/store/backend/JavaKeyStoreTest.java
  logstash-core/src/test/java/org/logstash/util/CloudSettingAuthTest.java
  logstash-core/src/test/java/org/logstash/util/CloudSettingIdTest.java
  logstash-core/src/test/java/org/logstash/util/ExceptionMatcher.java
  logstash-core/src/test/java/org/logstash/util/SetOnceReferenceTest.java
  qa/integration/build.gradle
  tools/benchmark-cli/build.gradle
  tools/dependencies-report/build.gradle
  tools/dependencies-report/src/test/java/org/logstash/dependencies/ReportGeneratorTest.java
  tools/dependencies-report/src/test/resources/expectedNoticeOutput.txt
  tools/dependencies-report/src/test/resources/expectedOutput.txt
  tools/dependencies-report/src/test/resources/javaLicenses1.csv
  tools/ingest-converter/build.gradle
  tools/jvm-options-parser/build.gradle
  x-pack/build.gradle
Labels: tests, status:approved

#16140 remove unused root Dockerfiles
  Dockerfile
  Dockerfile.base
  ci/docker_update_base_image.sh
Labels: status:needs-review

#16136 update multiple dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  logstash-core/benchmarks/build.gradle
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueRWBenchmark.java
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/QueueWriteBenchmark.java
  logstash-core/build.gradle
  logstash-core/logstash-core.gemspec
  tools/benchmark-cli/build.gradle
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/util/LsBenchCompressUtil.java
  tools/benchmark-cli/src/main/java/org/logstash/benchmark/cli/util/LsBenchDownloader.java
  tools/dependencies-report/build.gradle
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/rack-session-NOTICE.txt
  tools/ingest-converter/build.gradle
  tools/logstash-docgen/logstash-docgen.gemspec
  tools/paquet/paquet.gemspec
  versions.yml
Labels: status:approved

#16152 upgrade java_input_example to 1.0.3
  logstash-core/src/test/java/org/logstash/plugins/PluginValidatorTest.java
  logstash-core/src/test/resources/org/logstash/plugins/logstash-input-java_input_example-0.0.1.jar
  logstash-core/src/test/resources/org/logstash/plugins/logstash-input-java_input_example-1.0.3.jar
Labels: status:approved

#16058 feat(syntax): allow comments in hashes and before EOF
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.rb
  logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop
  logstash-core/lib/logstash/config/grammar.rb
  logstash-core/lib/logstash/config/grammar.treetop
  logstash-core/spec/logstash/config/config_ast_spec.rb
Labels: status:approved

#16141 [health] bootstrap HealthObserver from agent to API
  logstash-core/lib/logstash/agent.rb
  logstash-core/lib/logstash/api/commands/default_metadata.rb
  logstash-core/spec/logstash/webserver_spec.rb
  logstash-core/src/main/java/org/logstash/health/HealthObserver.java
  logstash-core/src/main/java/org/logstash/health/Status.java
  logstash-core/src/test/java/org/logstash/health/StatusTest.java
Labels: enhancement, status:approved

#16146 Bump 8.13.5
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#16147 Update releases inventory after 8.13.4
  ci/logstash_releases.json
Labels: status:approved

#16156 Remove Gradle deprecations warning related to usage of source and target Java versions
  build.gradle
  tools/jvm-options-parser/build.gradle
Labels: status:approved

#16083 Adds section to describe intended usage of `pipeline.buffer.type`
  docs/static/config-details.asciidoc
  docs/static/settings-file.asciidoc
Labels: status:approved

#16159 Replace stack traces with logger in DSL.
  logstash-core/src/main/java/org/logstash/config/ir/DSL.java
Labels: bug, status:needs-review

#16055 Update bundled JDK to 21
  versions.yml
Labels: status:approved

#12356 [DOC] Remove reference to puppet LS module
  docs/static/config-management.asciidoc
Labels: status:needs-review

#16072 Handle non-unicode payload in Logstash.
  logstash-core/lib/logstash/json.rb
  logstash-core/lib/logstash/util/unicode_normalizer.rb
  logstash-core/lib/logstash/util/unicode_trimmer.rb
  logstash-core/spec/logstash/json_spec.rb
  versions.yml
Labels: status:needs-review, >bug

#16137 Update plugins-metadata.json with integration-snmp: set skiplist to false
  rakelib/plugins-metadata.json
Labels: docs, status:approved

#16169 Regenerate dependencies report and add strscan.
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/strscan-NOTICE.txt
Labels: status:approved

#16168 Handle non-unicode payload in Logstash. (#16072)
  logstash-core/lib/logstash/json.rb
  logstash-core/lib/logstash/util/unicode_normalizer.rb
  logstash-core/lib/logstash/util/unicode_trimmer.rb
  logstash-core/spec/logstash/json_spec.rb
  versions.yml
Labels: status:approved

#16176 PQ: avoid blocking writer when precisely full
  docs/static/persistent-queues.asciidoc
  logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java
  logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java
Labels: bug, persistent queues, status:approved

#16188 Upgrade nokogiri to 1.16.5
  Gemfile.jruby-3.1.lock.release
Labels: status:needs-review

#16190 Add initial buildkite pipeline for Benchmark
  .buildkite/benchmark_pipeline.yml
  .buildkite/scripts/benchmark/config/filebeat.yml
  .buildkite/scripts/benchmark/config/logstash.yml
  .buildkite/scripts/benchmark/config/pipelines.yml
  .buildkite/scripts/benchmark/main.sh
  .buildkite/scripts/benchmark/util.sh
  catalog-info.yaml
Labels: status:needs-review

#16174 Add incomplete integration plugins to metadata.json as skip
  rakelib/plugins-metadata.json
Labels: status:approved
