Repository elastic/logstash, pull requests merged in 2024-01, with the labels that each got.

#15728 [ci] No Slack alerts for pipeline scheduling job
  catalog-info.yaml
Labels: status:approved, ci

#15729 Don't block triggered JDK matrix Buildkite jobs
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: status:needs-review, ci

#15733 Skip input step when triggering JDK matrix jobs
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/windows_jdk_matrix_pipeline.yml
Labels: status:needs-review, ci

#15707 Update to gradle 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, status:approved, gradle

#15722 Re-enable json filter and netflow codec plugins
  .buildkite/supported_plugins_test_pipeline.yml
  ci/test_plugins.rb
Labels: status:approved, buildkite

#15737 Fix logstash-keystore multiple keys operations with command flags
  logstash-core/src/main/java/org/logstash/secret/cli/SecretStoreCli.java
  logstash-core/src/test/java/org/logstash/secret/cli/SecretStoreCliTest.java
Labels: status:approved, keystore, v8.12.0

#15723 Add filter elastic_integration to be tested in test_plugins script
  ci/test_plugins.rb
Labels: enhancement, status:needs-review

#15741 JUnit result annotation for Buildkite PR jobs
  .buildkite/pull_request_pipeline.yml
Labels: status:needs-review, ci

#15743 Fixes a typo in plugin's organization name
  ci/test_plugins.rb
Labels: bug, status:needs-review

#15692 Add elastic_integration plugin to the plugin meta list.
  rakelib/plugins-metadata.json
Labels: enhancement, status:work-in-progress

#15758 Pin `childprocess` gem to major version `4`
  qa/integration/integration_tests.gemspec
Labels: bug, status:approved

#15720 Add system properties to configure Jackson's stream read constraints
  config/jvm.options
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/util/jackson.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/spec/logstash/util/jackson_spec.rb
Labels: status:approved

#15738 Run BK exhaustive pipeline when code is pushed
  .buildkite/exhaustive_tests_pipeline.yml
  .buildkite/scripts/common/check-files-changed.sh
  catalog-info.yaml
Labels: status:approved, ci

#15772 Backport PR #15738 to 7.17: Run BK exhaustive pipeline when code is pushed
  .buildkite/exhaustive_tests_pipeline.yml
  .buildkite/scripts/common/check-files-changed.sh
Labels: backport, status:needs-review, ci, v7.17.17

#15773 Bump Puma to newer version
  logstash-core/logstash-core.gemspec
Labels: status:needs-review

#15774 Update Puma on 7.17
  Gemfile.jruby-2.5.lock.release
  logstash-core/logstash-core.gemspec
Labels: status:approved

#15782 Bump 8.11.5
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#15783 Update releases inventory after 8.11.4
  ci/logstash_releases.json
Labels: status:work-in-progress

#15791 Don't trigger exhaustive tests with backports
  catalog-info.yaml
Labels: status:approved, ci

#15636 Doc: Add monitoring for serverless
  docs/static/monitoring/monitoring-ea-intro.asciidoc
  docs/static/monitoring/monitoring-ea-serverless.asciidoc
Labels: docs, status:approved

#15748 Add Docker acceptance to exhaustive BK pipeline
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci

#15779 [Doc] kerberos debug instructions
  docs/static/troubleshoot/ts-kafka.asciidoc
Labels: status:approved

#15781 Enable packaging tests in exhaustive pipeline
  .buildkite/scripts/common/vm-agent-multi-jdk.sh
  .buildkite/scripts/exhaustive-tests/generate-steps.py
  .ci/java-versions.properties
Labels: status:needs-review, ci

#15814 bump version to 8.12.1
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:needs-review

#15807 Backport PR #15781 to 7.17: Enable packaging tests in exhaustive pipeline #15806
  .buildkite/scripts/common/vm-agent-multi-jdk.sh
  .buildkite/scripts/exhaustive-tests/generate-steps.py
  .ci/java-versions.properties
Labels: backport, status:needs-review, ci, v7.17.17

#15810 [CI] Send Java and ruby tests to sonarqube simultaneously
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/pull-requests/sonar-env.sh
  Gemfile.template
  ci/docker_unit_tests.sh
  ci/unit_tests.sh
  logstash-core/lib/logstash/modules/logstash_config.rb
  sonar-project.properties
  spec/spec_helper.rb
Labels: enhancement, status:approved, ci, v8.12.0, v7.17.17, v8.11.5

#15709 Remove Nassim Kammah from list of Ironbank maintainers
  docker/templates/hardening_manifest.yaml
Labels: status:approved

#15820 Annotate successful DRA builds with summary URL
  .buildkite/scripts/dra/publish.sh
Labels: status:approved, ci

#15826 Fix acceptance/packaging upgrade test near a release
  qa/acceptance/helpers.rb
Labels: bug, status:approved, ci

#15839 Backport PR #15827 to 7.17: Fix IT tests after version bumps #15838
  build.gradle
  buildSrc/src/main/groovy/org/logstash/gradle/tooling/SnapshotArtifactURLs.groovy
Labels: backport, status:needs-review, ci, v7.17.17

#15841 Bump 7.17.18
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: release

#15843 Mute DLQ test on Windows
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
Labels: tests, status:needs-review, ci

#15840 Updates bundled JDK
  versions.yml
Labels: status:needs-review

#15835 Describe how to troubleshoot connectivity problems in Azure Blob Storage at HTTP level
  docs/static/troubleshoot/ts-azure.asciidoc
  docs/static/troubleshoot/ts-plugins.asciidoc
Labels: enhancement, docs, status:approved

#15851 Retries for serverless-integration-testing pipeline
  .buildkite/serverless_integration_pipeline.yml
Labels: status:approved, ci

#15747 Doc: Update extending integrations docs to point to plugin
  docs/static/ea-integrations.asciidoc
Labels: docs, status:approved

#15847 [docs] Simplify and improve Logstash monitoring docs.
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
  docs/static/monitoring/monitoring-ea-serverless.asciidoc
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/monitoring/monitoring-prereq-disable-default.asciidoc
Labels: docs, status:approved

#15855 Remove Ubuntu 18.04 from CI jobs
  .buildkite/linux_jdk_matrix_pipeline.yml
  .buildkite/scripts/common/vm-images.json
Labels: status:needs-review, ci

#15857 Re-enabled collectd codec in test_plugins script
  ci/test_plugins.rb
Labels: status:approved

#15862 Revert "[docs] Simplify and imrove Logstash monitoring docs. (#15847)"
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
  docs/static/monitoring/monitoring-ea-serverless.asciidoc
  docs/static/monitoring/monitoring-ea.asciidoc
  docs/static/monitoring/monitoring-mb.asciidoc
  docs/static/monitoring/monitoring-prereq-disable-default.asciidoc
Labels: status:approved

#15850 Scheduled runs of exhaustive and aarch64 pipelines
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  catalog-info.yaml
Labels: status:approved, ci

#15858 Fix typo in catalog-info with exhaustive schema
  catalog-info.yaml
Labels: status:approved, ci

#15864 Update stack versions for CI.
  ci/logstash_releases.json
Labels: status:approved

#15867 add base64 notice and update generated NOTICE.txt
  NOTICE.TXT
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/base64-NOTICE.txt
Labels: status:approved

#15869 [ci] Skip slack alerts if retried tasks succeeded
  catalog-info.yaml
Labels: ci

#15873 Fix typo with aarch64 pipeline name to trigger
  catalog-info.yaml
Labels: status:approved, ci

#15874 Add BK retries to exhaustive/compat steps
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: status:approved, ci

#15877 Add retries to JDK matrix pipeline steps
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
Labels: status:approved, ci
