Repository elastic/logstash, pull requests merged in 2024-08, with the labels that each got.

#16365 [Bugfix] Resolve the array and char (single | double quote) escaped values of ${ENV}
  logstash-core/lib/logstash/util/substitution_variables.rb
  qa/docker/shared_examples/xpack.rb
Labels: bug, status:approved

#16374 Doc: Add SNMP integration to breaking changes
  docs/static/breaking-changes.asciidoc
Labels: docs, status:approved, v8.15.0

#16370 deprecate java less-than 17
  logstash-core/lib/logstash/runner.rb
  logstash-core/locales/en.yml
  logstash-core/src/main/java/org/logstash/util/JavaVersion.java
Labels: status:needs-review

#16375 Exclude substitution refinement on pipelines.yml
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  qa/integration/specs/multiple_pipeline_spec.rb
Labels: bug, status:approved

#16390 Removing 8.14 from ci/branches.json as we have 8.15.
  ci/branches.json
Labels: status:needs-triage

#16394 Update bundled JDK
  versions.yml
Labels: status:needs-triage

#16397 Merge `main` into `feature/health-report-api`
  .buildkite/pull-requests.json
  .buildkite/snyk_report_pipeline.yml
  ci/branches.json
  ci/logstash_releases.json
  docs/static/breaking-changes.asciidoc
  docs/static/monitoring/monitoring-apis.asciidoc
  docs/static/releasenotes.asciidoc
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/lib/logstash/java_pipeline.rb
  logstash-core/lib/logstash/runner.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  logstash-core/locales/en.yml
  logstash-core/spec/logstash/java_pipeline_spec.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/src/main/java/org/logstash/util/JavaVersion.java
  qa/docker/shared_examples/xpack.rb
  qa/integration/fixtures/webserver_certs/generated/intermediate-ca.crt
  qa/integration/fixtures/webserver_certs/generated/intermediate-ca.key
  qa/integration/fixtures/webserver_certs/generated/root.crt
  qa/integration/fixtures/webserver_certs/generated/root.key
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.chain.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.jks
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.key
  qa/integration/fixtures/webserver_certs/generated/server_from_intermediate.p12
  qa/integration/fixtures/webserver_certs/generated/server_from_root.chain.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_root.crt
  qa/integration/fixtures/webserver_certs/generated/server_from_root.jks
  qa/integration/fixtures/webserver_certs/generated/server_from_root.key
  qa/integration/fixtures/webserver_certs/generated/server_from_root.p12
  qa/integration/specs/multiple_pipeline_spec.rb
  x-pack/qa/integration/support/helpers.rb
Labels: backport, easyreview, status:needs-review
