Repository elastic/logstash, pull requests merged in 2024-04, with the labels that each got.

#16047 Bump 8.13.2
  Gemfile.jruby-3.1.lock.release
  versions.yml
Labels: status:approved

#15719 JDK 21 move
  build.gradle
  logstash-core/lib/logstash/instrument/periodic_poller/jvm.rb
  logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java
  logstash-core/src/main/java/org/logstash/config/ir/expression/RegexValueExpression.java
  logstash-core/src/main/java/org/logstash/config/ir/graph/Edge.java
  logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClientBase.java
  logstash-core/src/main/java/org/logstash/instrument/monitors/HotThreadsMonitor.java
  logstash-core/src/main/java/org/logstash/plugins/inputs/Stdin.java
  logstash-core/src/main/java/org/logstash/util/UtilExt.java
  logstash-core/src/test/java/org/logstash/ext/JrubyMemoryReadClientExtTest.java
  logstash-core/src/test/java/org/logstash/log/TestingDeprecationPlugin.java
  logstash-core/src/test/java/org/logstash/plugins/AliasRegistryTest.java
  logstash-core/src/test/java/org/logstash/secret/store/SecretStoreFactoryTest.java
Labels: status:approved, java 21 support

#16048 Update releases inventory after 8.13.1
  ci/logstash_releases.json
Labels: status:approved

#16053 Update Dockerfile to select appropriate architecture on build box
  docker/templates/Dockerfile.erb
Labels: status:approved

#16062 Fix the git branch check.
  .buildkite/scripts/snyk/report.sh
Labels: status:needs-review

#16070 bump version to 7.17.21
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#16077 remove 8.12 from CI
  ci/branches.json
Labels: status:needs-review

#16050 Fix the exception behavior when `config.string` contains ${VAR} in the comments.
  logstash-core/lib/logstash/config/source/multi_local.rb
  logstash-core/lib/logstash/util/substitution_variables.rb
  logstash-core/spec/logstash/config/source/multi_local_spec.rb
Labels: bug, status:approved

#16079 Split LS_JAVA_OPTS content when contains multiple options
  tools/jvm-options-parser/src/main/java/org/logstash/launchers/JvmOptionsParser.java
  tools/jvm-options-parser/src/test/java/org/logstash/launchers/JvmOptionsParserTest.java
Labels: bug, status:approved

#16076 Use `dpkg --print-architecture` in Dockerfile to ascertain architecture
  docker/templates/Dockerfile.erb
Labels: status:approved

#16086 add 8.14 branch for CI
  ci/branches.json
Labels: status:approved

#16088 bump version to 8.15.0
  versions.yml
Labels: status:approved
