Repository elastic/logstash, pull requests merged in 2024-03, with the labels that each got.

#15425 Set Imap plugin as a non-default plugin.
  rakelib/plugins-metadata.json
Labels: status:approved

#15980 Add arm64 support for env2yaml
  docker/Makefile
  docker/templates/Dockerfile.erb
Labels: status:approved

#15888 Split java/ruby unit test steps on Windows
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
Labels: status:approved, ci, Team:Logstash

#15986 geoip: avoid crash cleaning non-existing managed dbs
  x-pack/lib/geoip_database_management/manager.rb
  x-pack/spec/geoip_database_management/manager_spec.rb
Labels: bug, P2, status:approved

#15998 Remove curl installation step, as `curl-minimal` is already provided …
  docker/templates/Dockerfile.erb
Labels: status:needs-review

#16000 Doc Test: Remove extra `+` to force page to rebuild
  docs/static/monitoring/monitoring-ea-dashboards.asciidoc
Labels: docs, status:approved

#15987 remove repetitive words
  docs/static/dead-letter-queues.asciidoc
  docs/static/security/basic-auth.asciidoc
  logstash-core/lib/logstash/instrument/metric_store.rb
  logstash-core/spec/logstash/state_resolver_spec.rb
  logstash-core/src/main/java/org/logstash/config/ir/ConfigCompiler.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClient.java
  tools/logstash-docgen/README.md
Labels: status:needs-triage

#15894 upgrade ruby-maven-libs to 3.8.9
  Gemfile.template
  logstash-core/logstash-core.gemspec
  rakelib/artifacts.rake
  rubyUtils.gradle
  tools/dependencies-report/src/main/resources/licenseMapping.csv
  tools/dependencies-report/src/main/resources/notices/ruby-maven-libs-NOTICE.txt
Labels: status:needs-review

#16012 Bump ES output to include unicode-vs-compression fix
  Gemfile.jruby-2.5.lock.release
Labels: bug, status:needs-review, v7.17.19

#16023 Bump 7.17.20
  Gemfile.jruby-2.5.lock.release
  versions.yml
Labels: status:approved

#16024 Update releases inventory after 7.17.19
  ci/logstash_releases.json
Labels: status:approved

#16021 Doc: Remove beta tag from integrations filter doc
  docs/static/ea-integrations.asciidoc
Labels: docs, status:approved, v8.13.0

#16028 Create critical_vulnerability_scan.yml
  .github/workflows/critical_vulnerability_scan.yml
Labels: status:approved

#16026 Save name came through ENV vars to let Logstash decide using value from either keystore or ENV.
  docker/data/logstash/env2yaml/env2yaml.go
Labels: bug, status:approved

#16022 Modernize ironbank Dockerfile
  docker/templates/Dockerfile.erb
  docker/templates/hardening_manifest.yaml.erb
Labels: status:approved

#16039 Fix github checkout for critical_vulnerability_scan action
  .github/workflows/critical_vulnerability_scan.yml
Labels: status:approved

#16038 Fix integration tests caused by #16026.
  qa/docker/shared_examples/xpack.rb
Labels: status:needs-review
