Repository elastic/logstash, pull requests merged in 2025-07, with the labels that each got.

#17229 Implement BufferedTokenizer to return an iterable that can verify size limit for every token emitted
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/BufferedTokenizerBenchmark.java
  logstash-core/benchmarks/src/main/java/org/logstash/benchmark/BufferedTokenizerExtBenchmark.java
  logstash-core/spec/logstash/util/buftok_spec.rb
  logstash-core/src/main/java/org/logstash/RubyUtil.java
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizer.java
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerWithDelimiterTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerWithSizeLimitTest.java
Labels: enhancement, backport-8.x

#17740 Update mergify with new 9.1 branch
  .mergify.yml
Labels: backport-skip

#17768 Restore cgi pin
  Gemfile.jruby-3.1.lock.release
  Gemfile.template
Labels: backport-skip

#17798 Run tests with jruby 9.4.13.0
  .ruby-version
Labels: backport-9.1

#17828 [CI] Remove UBI docker acceptance test
  .buildkite/scripts/exhaustive-tests/generate-steps.py
Labels: backport-active-9

#17827 [CI] fix benchmark docker name
  .buildkite/scripts/benchmark/util.sh
Labels: backport-active-9, backport-active-8

#17857 [docs] Use centrally maintained version variables
  docs/docset.yml
  docs/reference/docker.md
  docs/reference/first-event.md
  docs/reference/installing-logstash.md
  docs/reference/running-logstash-command-line.md
  docs/reference/working-with-plugins.md
Labels: docs, Team:Docs, backport-9.0, backport-9.1

#17862 [docs] Whitespace edit for testing the doc build
  docs/reference/index.md
Labels: docs, Team:Docs
