Repository elastic/logstash, pull requests merged in 2025-03, with the labels that each got.

#17208 [docs] Add missing `mapped_page`
  docs/release-notes/index.md
Labels: docs, Team:Docs, backport-skip

#17213 [DOCS] Fix doc link
  docs/release-notes/breaking-changes.md
Labels: docs, Team:Docs, backport-skip

#17203 Pluginmanager clean after mutate
  lib/pluginmanager/command.rb
  lib/pluginmanager/gemfile.rb
  lib/pluginmanager/install.rb
  lib/pluginmanager/remove.rb
  lib/pluginmanager/update.rb
  qa/integration/fixtures/update_spec.yml
  qa/integration/services/logstash_service.rb
  qa/integration/specs/cli/install_spec.rb
  qa/integration/specs/cli/pluginmanager_spec_helper.rb
  qa/integration/specs/cli/remove_spec.rb
  qa/integration/specs/cli/update_spec.rb
Labels: backport-9.0, backport-8.x

#16656 Improve warning for insufficient file resources for PQ max_bytes
  logstash-core/lib/logstash/persisted_queue_config_validator.rb
  logstash-core/spec/logstash/persisted_queue_config_validator_spec.rb
Labels: enhancement, backport-9.0, backport-8.x

#17168 mergify: add backport rules for 8.18 and 9.0
  .mergify.yml
Labels: backport-8.17

#17228 [test] ls2ls spec adds heartbeat to keep alive
  qa/integration/fixtures/logstash_to_logstash_spec.yml
Labels: backport-8.x

#17225 Doc: Running LS in ECK
  docs/reference/running-logstash-kubernetes.md
Labels: backport-skip

#17232 gradle task migrate to the new artifacts-api
  build.gradle
Labels: backport-8.x

#17167 tests: ls2ls delay checking until events have been processed
  qa/integration/services/logstash_service.rb
  qa/integration/specs/logstash_to_logstash_spec.rb
Labels: tests, backport-9.0, backport-8.x, backport-8.18

#17217 mergify: support for some backport aliases
  .mergify.yml
Labels: backport-skip

#17253 Update logstash_releases.json
  ci/logstash_releases.json
Labels: backport-skip

#17246 Additional cleanify changes to ls2ls integ tests
  qa/integration/fixtures/logstash_to_logstash_spec.yml
  qa/integration/fixtures/persistent_queues/logstash.yml
  qa/integration/specs/logstash_to_logstash_spec.rb
Labels: backport-8.x

#17210 Fix pqcheck and pqrepair on Windows
  bin/pqcheck.bat
  bin/pqrepair.bat
Labels: backport-8.17, backport-9.0, backport-8.16, backport-8.x, backport-8.18

#17258 Temporarily disable mergify conflict process.
  .mergify.yml
Labels: backport-8.x

#17267 Pluginmanager install preserve
  lib/pluginmanager/install.rb
  qa/integration/specs/cli/install_spec.rb
  qa/integration/specs/cli/pluginmanager_spec_helper.rb
Labels: backport-8.x

#17224 benchmark uses the new artifacts-api
  .buildkite/scripts/benchmark/core.sh
Labels: backport-8.x

#17274 Health report integration test migrate to the new artifacts-api
  .buildkite/scripts/health-report-tests/bootstrap.py
Labels: backport-8.x

#17288 [docs] Fix external links
  docs/extend/codec-new-plugin.md
  docs/extend/filter-new-plugin.md
  docs/extend/input-new-plugin.md
  docs/extend/output-new-plugin.md
  docs/reference/event-dependent-configuration.md
  docs/reference/getting-started-with-logstash.md
  docs/reference/logging.md
  docs/reference/plugins-filters-aggregate.md
  docs/reference/plugins-filters-date.md
  docs/reference/plugins-filters-jdbc_static.md
  docs/reference/plugins-inputs-cloudwatch.md
  docs/reference/plugins-inputs-couchdb_changes.md
  docs/reference/plugins-inputs-jms.md
  docs/reference/plugins-inputs-kafka.md
  docs/reference/plugins-inputs-kinesis.md
  docs/reference/plugins-inputs-rabbitmq.md
  docs/reference/plugins-inputs-relp.md
  docs/reference/plugins-inputs-s3.md
  docs/reference/plugins-inputs-sqs.md
  docs/reference/plugins-inputs-tcp.md
  docs/reference/plugins-integrations-snmp.md
  docs/reference/plugins-outputs-cloudwatch.md
  docs/reference/plugins-outputs-csv.md
  docs/reference/plugins-outputs-elasticsearch.md
  docs/reference/plugins-outputs-kafka.md
  docs/reference/plugins-outputs-riemann.md
  docs/reference/plugins-outputs-s3.md
  docs/reference/plugins-outputs-sqs.md
  docs/reference/plugins-outputs-webhdfs.md
  docs/reference/processing.md
  docs/reference/tuning-logstash.md
Labels: docs, Team:Docs, backport-skip

#17290 Remove automatic `backport-8.x` label creation
  .mergify.yml
Labels: backport-skip

#17223 Shareable function for partitioning integration tests
  ci/get-test-half.sh
  ci/integration_tests.sh
Labels: backport-active-all

#17305 Ensure env2yaml dep is properly expressed in observabilitySRE task
  docker/Makefile
Labels: backport-skip

#17161 Upgrade elasticsearch-ruby client.
  Gemfile.template
  logstash-core/logstash-core.gemspec
  logstash-core/spec/logstash/webserver_spec.rb
  qa/integration/specs/dlq_spec.rb
  x-pack/qa/integration/management/multiple_pipelines_spec.rb
  x-pack/qa/integration/monitoring/es_documents_structure_validation_spec.rb
  x-pack/qa/integration/support/helpers.rb
  x-pack/qa/integration/support/shared_examples.rb
Labels: backport-8.17, backport-9.0, backport-8.x, backport-8.18

#17310 Surface failures from nested rake/shell tasks
  rakelib/artifacts.rake
  rubyUtils.gradle
Labels: backport-active-all

#17298 Add a smoke test for observability SRE container
  .buildkite/pull_request_pipeline.yml
  x-pack/distributions/internal/observabilitySRE/plugin-allow-list.txt
Labels: backport-skip

#17319 Require shellwords in artifact rake task
  rakelib/artifacts.rake
Labels: backport-9.0

#17292 [Doc] OpenAPI spec
  docs/static/spec/openapi/logstash-api.yaml
Labels: docs

#17324 Doc: Update intro to match TOC order in API docs
  docs/static/spec/openapi/logstash-api.yaml
Labels: docs

#17326 Internal collection doc update to reflect enabling legacy collection.
  docs/reference/monitoring-internal-collection-legacy.md
Labels: backport-9.0

#17331 Add Deprecation tag to arcsight module
  docs/static/arcsight-module.asciidoc
Labels: backport-8.17, backport-8.16, backport-8.18

#17325 Doc: Refine new MD docs (WIP)
  docs/reference/ecs-ls.md
  docs/reference/getting-started-with-logstash.md
  docs/reference/index.md
Labels: docs, backport-9.0

#17311 add ci shared qualified-version script
  .buildkite/scripts/common/qualified-version.sh
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/common.sh
  .buildkite/scripts/dra/publish.sh
Labels: backport-8.x, backport-8.18, backport-active-9

#17346 Use org.logstash.common.Util to hashing by default to SHA256
  logstash-core/build.gradle
  logstash-core/src/main/java/org/logstash/common/Util.java
  logstash-core/src/main/java/org/logstash/config/ir/PipelineConfig.java
  logstash-core/src/main/java/org/logstash/plugins/AliasRegistry.java
  logstash-core/src/main/java/org/logstash/util/EscapeHandler.java
  tools/benchmark-cli/build.gradle
Labels: enhancement, backport-8.x

#17353 Added test to verify the int overflow happen
  logstash-core/build.gradle
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
Labels: bug, backport-active-9, backport-active-8

#17338 Remove OpenJDK 17 from jdk test matrix
  .buildkite/linux_jdk_matrix_pipeline.yml
Labels: backport-active-9, backport-active-8

#17219 tests: make integration split quantity configurable
  .buildkite/aarch64_pipeline.yml
  .buildkite/pull_request_pipeline.yml
  .buildkite/scripts/jdk-matrix-tests/generate-steps.py
  ci/get-test-half.sh
  ci/integration_tests.sh
  ci/partition-files.lib.sh
Labels: ci, backport-active-9, backport-active-8

#17361 Doc: Fix upgrade TOC structure
  docs/reference/docker.md
  docs/reference/toc.yml
  docs/reference/upgrading-logstash.md
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: docs, backport-9.0

#17372 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/advanced-pipeline.md
  docs/reference/dashboard-monitoring-with-elastic-agent.md
  docs/reference/dead-letter-queues.md
  docs/reference/deploying-scaling-logstash.md
  docs/reference/first-event.md
  docs/reference/images/basic_logstash_pipeline.png
  docs/reference/images/centralized_config.png
  docs/reference/images/dead_letter_queue.png
  docs/reference/images/deploy1.png
  docs/reference/images/deploy2.png
  docs/reference/images/deploy3.png
  docs/reference/images/deploy4.png
  docs/reference/images/integration-assets-dashboards.png
  docs/reference/images/integration-dashboard-overview.png
  docs/reference/images/kibana-filebeat-data.png
  docs/reference/images/kibana-home.png
  docs/reference/images/monitoring-ui.png
  docs/reference/images/nodestats.png
  docs/reference/images/overviewstats.png
  docs/reference/images/pipeline-input-detail.png
  docs/reference/images/pipeline-tree.png
  docs/reference/images/pipeline_correct_load.png
  docs/reference/images/pipeline_overload.png
  docs/reference/index.md
  docs/reference/logstash-centralized-pipeline-management.md
  docs/reference/logstash-monitoring-ui.md
  docs/reference/logstash-pipeline-viewer.md
  docs/reference/monitoring-internal-collection-legacy.md
  docs/reference/monitoring-with-elastic-agent.md
  docs/reference/serverless-monitoring-with-elastic-agent.md
  docs/reference/tuning-logstash.md
Labels: docs, Team:Docs, backport-9.0

#17381 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: Team:Docs, backport-9.0

#17391 [Doc] Fix Elasticsearch output SSL settings
  docs/reference/secure-connection.md
Labels: backport-active-9

#17407 Pin rubocop-ast development gem due to new dep on prism
  Gemfile.template
Labels: backport-active-all

#17403 Doc: Upgrade content improvements
  docs/reference/toc.yml
  docs/reference/upgrading-logstash-9-0.md
  docs/reference/upgrading-logstash.md
  docs/release-notes/breaking-changes.md
Labels: docs, backport-9.0

#17440 [docs] Remove reliance on temporary redirects
  docs/reference/dashboard-monitoring-with-elastic-agent.md
  docs/reference/monitoring-with-elastic-agent.md
  docs/reference/upgrading-logstash.md
Labels: docs, Team:Docs

#17442 Do not pipe Git output into a pager.
  .buildkite/scripts/common/check-files-changed.sh
Labels: backport-skip

#17387 Update tls-encryption.asciidoc
  docs/static/security/tls-encryption.asciidoc
Labels: backport-active-8

#17421 github-actions: enable dependabot
  .github/dependabot.yml
Labels: backport-skip
