Repository elastic/logstash, pull requests merged in 2025-01, with the labels that each got.

#16832 Apply Jackson stream read constraints defaults at runtime
  logstash-core/src/main/java/org/logstash/jackson/StreamReadConstraintsUtil.java
  logstash-core/src/test/java/org/logstash/jackson/StreamReadConstraintsUtilTest.java
Labels: bug

#16840 Doc: Message Logstash module deprecations and removal
  docs/index.asciidoc
  docs/static/arcsight-module.asciidoc
  docs/static/azure-module.asciidoc
  docs/static/deploying.asciidoc
  docs/static/modules.asciidoc
  docs/static/netflow-module.asciidoc
  docs/static/redirects.asciidoc
  docs/static/running-logstash-command-line.asciidoc
  docs/static/settings-file.asciidoc
  docs/static/shared-module-options.asciidoc
Labels: docs

#16833 Ensure plugin config marked `:deprecated` logs to deprecation logger
  logstash-core/lib/logstash/config/mixin.rb
  logstash-core/spec/logstash/config/mixin_spec.rb
Labels: bug, status:needs-review

#16810 Forward port 8.15.5 and 8.16.2 release notes to 8.17
  docs/static/releasenotes.asciidoc
Labels: docs

#16881 Avoid flow metrics initialization if pipeline `metric.collect` is disabled.
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
Labels: bug

#16546 Logstash API spec - first pass
  docs/static/spec/openapi/logstash-api.yaml
  docs/static/spec/openapi/redocly.yaml
Labels: docs, status:work-in-progress

#16689 Doc: Environment variables cannot be in config.string comments.
  docs/static/env-vars.asciidoc
  docs/static/pipeline-configuration.asciidoc
Labels: docs, status:changes-requested

#16742 Add beats and es-agent SSL breaking changes to 9.0 breaking change doc.
  docs/static/breaking-changes-90.asciidoc
Labels: Team:Docs

#16907 Use --qualifier in release manager
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: ci

#16913 Backport 16907 to 8.x: Use --qualifier in release manager (#16907)
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: backport

#16926 Doc: Remove extra symbol to fix formatting error
  docs/static/ls-to-cloud.asciidoc
Labels: docs

#16941 Backport 16907 to 8.17: Use --qualifier in release manager (#16907)
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: backport

#16942 Backport 16907 to 8.16: Use --qualifier in release manager (#16907)
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/build_docker.sh
  .buildkite/scripts/dra/build_packages.sh
  .buildkite/scripts/dra/generatesteps.py
  .buildkite/scripts/dra/publish.sh
Labels: backport

#16576 Reimplement LogStash::String setting in Java
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/util/settings_helper.rb
  logstash-core/spec/logstash/api/commands/default_metadata_spec.rb
  logstash-core/spec/logstash/queue_factory_spec.rb
  logstash-core/spec/logstash/settings/nullable_spec.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
  logstash-core/spec/logstash/settings/string_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
  logstash-core/src/main/java/org/logstash/settings/SettingNullableString.java
  logstash-core/src/main/java/org/logstash/settings/SettingString.java
  logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java
  logstash-core/src/test/java/org/logstash/settings/BooleanTest.java
  logstash-core/src/test/java/org/logstash/settings/SettingStringTest.java
  spec/spec_helper.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/geoip_database_management/extension.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/config_management/extension_spec.rb
Labels: enhancement, status:work-in-progress

#16959 [Backport 8.x] Reimplement LogStash::String setting in Java (#16576)
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/modules/logstash_config.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/lib/logstash/util/settings_helper.rb
  logstash-core/spec/logstash/api/commands/default_metadata_spec.rb
  logstash-core/spec/logstash/queue_factory_spec.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/spec/logstash/settings/nullable_spec.rb
  logstash-core/spec/logstash/settings/setting_with_deprecated_alias_spec.rb
  logstash-core/spec/logstash/settings/string_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/src/main/java/org/logstash/settings/BaseSetting.java
  logstash-core/src/main/java/org/logstash/settings/SettingNullableString.java
  logstash-core/src/main/java/org/logstash/settings/SettingString.java
  logstash-core/src/main/java/org/logstash/settings/SettingWithDeprecatedAlias.java
  logstash-core/src/test/java/org/logstash/settings/BooleanTest.java
  logstash-core/src/test/java/org/logstash/settings/SettingStringTest.java
  spec/spec_helper.rb
  x-pack/lib/config_management/extension.rb
  x-pack/lib/geoip_database_management/extension.rb
  x-pack/lib/monitoring/monitoring.rb
  x-pack/spec/config_management/extension_spec.rb
Labels: backport

#16929 ci(buildkite): exclude files/folders that are not tested in Buildkite
  .buildkite/pull-requests.json
Labels: ci

#16899 plugin manager: add `--level=[major|minor|patch]` (default: `minor`)
  docs/static/plugin-manager.asciidoc
  lib/bootstrap/bundler.rb
  lib/pluginmanager/update.rb
  spec/unit/bootstrap/bundler_spec.rb
  spec/unit/plugin_manager/update_spec.rb
Labels: plugin manager

#16979 Adding elastic_integration upgrade guidelines.
  docs/static/upgrading.asciidoc
Labels: docs

#16995 Use centralized version qualifier
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
Labels: enhancement, ci

#17006 Revert "Use centralized version qualifier"
  .buildkite/dra_pipeline.yml
  .buildkite/scripts/dra/generatesteps.py
Labels: ci
