Repository elastic/logstash, pull requests merged in 2025-02, with the labels that each got.

#17011 Update JDK
  versions.yml
Labels: v7.17.28

#16968 Fix BufferedTokenizer to properly resume after a buffer full condition respecting the encoding of the input string
  logstash-core/src/main/java/org/logstash/common/BufferedTokenizerExt.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithDelimiterTest.java
  logstash-core/src/test/java/org/logstash/common/BufferedTokenizerExtWithSizeLimitTest.java
Labels: bug, status:needs-review

#17032 Don't honor VERSION_QUALIFIER if set but empty
  logstash-core-plugin-api/logstash-core-plugin-api.gemspec
  logstash-core/logstash-core.gemspec
  qa/docker/spec/spec_helper.rb
  rakelib/artifacts.rake
Labels: bug, build

#17056 docs: forward-port 8.16.4 release notes to 8.17
  docs/static/releasenotes.asciidoc
Labels: docs

#17063 Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  .buildkite/scripts/snyk/resolve_stack_version.sh
  ci/branches.json
Labels: enhancement, ci

#17076 Backport PR #17063 to 8.16: Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
Labels: backport, ci

#17074 Backport PR #17063 to 8.18: Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
Labels: backport, ci

#17073 Backport PR #17063 to 8.x: Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
Labels: backport, ci

#17075 Backport PR #17063 to 8.17: Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
Labels: backport, ci

#17072 Backport PR #17063 to 9.0: Use centralized source of truth for active branches
  .buildkite/scripts/common/trigger-pipeline-generate-steps.sh
  .buildkite/scripts/snyk/resolve_stack_version.sh
  ci/branches.json
Labels: backport, ci

#17081 Allow capturing heap dumps in DRA BK jobs
  .buildkite/scripts/dra/generatesteps.py
Labels: enhancement, ci

#17082 qa: use clean expansion of LS tarball per fixture instance
  build.gradle
  qa/integration/framework/settings.rb
  qa/integration/services/logstash_service.rb
  qa/integration/specs/logstash_to_logstash_spec.rb
Labels: tests

#17114 spec: improve ls2ls spec
  qa/integration/fixtures/logstash_to_logstash_spec.yml
  qa/integration/specs/logstash_to_logstash_spec.rb
Labels: tests

#17030 plugins: improve `remove` command to support multiple plugins
  lib/pluginmanager/bundler/logstash_uninstall.rb
  lib/pluginmanager/remove.rb
  qa/integration/fixtures/plugins/generate-gems.sh
  qa/integration/fixtures/plugins/logstash-filter-four_depends_on_one_and_three.gemspec
  qa/integration/fixtures/plugins/logstash-filter-one_no_dependencies.gemspec
  qa/integration/fixtures/plugins/logstash-filter-three_no_dependencies.gemspec
  qa/integration/fixtures/plugins/logstash-filter-two_depends_on_one.gemspec
  qa/integration/fixtures/plugins/logstash-filter-zero_no_dependencies.gemspec
  qa/integration/services/logstash_service.rb
  qa/integration/specs/cli/remove_spec.rb
  rakelib/plugin.rake
Labels: enhancement

#17131 Backport PR #171226 to 8.x: Fix acceptance test assertions for updated plugin remove
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb
Labels: backport, v8.19.0

#17132 Backport PR #171222 to 8.x: Fix acceptance test assertions for updated plugin remove
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb
  qa/acceptance/spec/shared_examples/cli/logstash-plugin/uninstall.rb
Labels: backport, v8.19.0

#17158 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: Team:Docs

#17124 plugin manager: add --no-expand flag for list command
  lib/pluginmanager/list.rb
  lib/pluginmanager/util.rb
  qa/integration/fixtures/list_spec.yml
  qa/integration/specs/cli/list_spec.rb
Labels: enhancement, plugin manager

#17171 qa: don't bypass plugin manger tests on linux
  build.gradle
  qa/integration/build.gradle
  qa/integration/fixtures/plugins/.gitignore
  qa/integration/specs/cli/install_spec.rb
  qa/integration/specs/cli/remove_spec.rb
Labels: tests

#17141 Update Dockerfile.erb to set eux on RUN command with semicolons
  docker/templates/Dockerfile.erb
Labels: backport-8.17, backport-9.0, backport-8.16, backport-8.x, backport-8.18

#17189 add missing Makefile tasks to build oss and wolfi images from build context tarballs
  docker/Makefile
Labels: backport-8.x

#17185 Fix empty node stats pipelines
  logstash-core/lib/logstash/api/commands/stats.rb
  qa/integration/services/monitoring_api.rb
  x-pack/qa/integration/monitoring/direct_shipping_spec.rb
Labels: backport-8.17, backport-9.0, backport-8.x, backport-8.18
