Repository elastic/logstash, pull requests merged in 2025-09, with the labels that each got.

#18083 upgrade golang to 1.25
  docker/templates/Dockerfile.erb
  docker/templates/IronbankDockerfile.erb
Labels: backport-active-9

#18082 Fix gauge type correctly where requesting pipeline metrics in condition.
  logstash-core/lib/logstash/config/pipelines_info.rb
Labels: >bug, backport-9.0, backport-8.x, backport-8.18, backport-8.19, backport-9.1

#18092 Doc: Provide accurate post-geoip lookup example
  docs/reference/lookup-enrichment.md
Labels: backport-9.0, backport-9.1

#18101 Doc: Refine geoip filter example for 8.19
  docs/static/transforming-data.asciidoc
Labels: docs, backport-8.18, backport-8.19

#18091 Preserve mtime explicitly when creating tar artifacts
  rakelib/artifacts.rake
Labels: backport-active-all

#18102 github-actions: support backport labels after being merged
  .github/workflows/backport-active.yml
Labels: automation, backport-skip

#17849 pq: activate stringref extension for more-compact PQ representation
  logstash-core/src/main/java/org/logstash/ObjectMappers.java
  logstash-core/src/test/java/org/logstash/EventTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueReaderTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterAgeRetentionTest.java
  logstash-core/src/test/java/org/logstash/common/io/DeadLetterQueueWriterTest.java
  logstash-core/src/test/resources/org/logstash/stringref-disabled.annotated-cbor.txt
  logstash-core/src/test/resources/org/logstash/stringref-enabled.annotated-cbor.txt
Labels: persistent queues

#17988 compat: add test for deserializing stringref enabled and disabled
  logstash-core/src/test/java/org/logstash/EventTest.java
  logstash-core/src/test/resources/org/logstash/stringref-disabled.annotated-cbor.txt
  logstash-core/src/test/resources/org/logstash/stringref-enabled.annotated-cbor.txt
Labels: tests, persistent queues, backport-skip

#18080 Update JRuby version to 9.4.14.0
  Gemfile.template
  versions.yml
Labels: JRuby 9K, backport-9.1

#18124 test: explicitly load ascii fixture as ascii, do line-oriented parsing
  logstash-core/src/test/java/org/logstash/EventTest.java
  logstash-core/src/test/resources/org/logstash/stringref-disabled.annotated-cbor.asc
  logstash-core/src/test/resources/org/logstash/stringref-enabled.annotated-cbor.asc
Labels: backport-9.0, backport-8.19, backport-9.1

#18129 Doc: Update Java version requirements for 8.18
  docs/static/jvm.asciidoc
Labels: docs, backport-skip

#18150 Fix race condition with version bump action
  .github/workflows/version_bumps.yml
Labels: backport-active-all

#18034 Doc: Add Logstash-to-serverless page
  docs/reference/connecting-to-serverless.md
  docs/reference/toc.yml
Labels: docs, backport-active-9

#18166 Doc: Refine serverless and hosted content
  docs/reference/connecting-to-cloud.md
  docs/reference/connecting-to-serverless.md
Labels: docs, backport-active-9

#17964 Move Port and PortRange Ruby settings to Java
  logstash-core/lib/logstash/environment.rb
  logstash-core/lib/logstash/settings.rb
  logstash-core/spec/logstash/runner_spec.rb
  logstash-core/spec/logstash/settings/port_range_spec.rb
  logstash-core/spec/logstash/settings_spec.rb
  logstash-core/src/main/java/org/logstash/settings/PortRangeSetting.java
  logstash-core/src/main/java/org/logstash/settings/PortSetting.java
  logstash-core/src/main/java/org/logstash/settings/Range.java
  logstash-core/src/test/java/org/logstash/settings/PortRangeSettingTest.java
  logstash-core/src/test/java/org/logstash/settings/RangeTest.java
Labels: enhancement

#18169 Adds a required type tag to the open API spec of Logstash APIs.
  docs/static/spec/openapi/logstash-api.yaml
Labels: docs, backport-skip

#18180 PQ settings refactor: propagate builder upward
  logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb
  logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb
  logstash-core/spec/logstash/util/wrapped_acked_queue_spec.rb
  logstash-core/src/main/java/org/logstash/ackedqueue/QueueFactoryExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/Settings.java
  logstash-core/src/main/java/org/logstash/ackedqueue/SettingsImpl.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java
  logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java
Labels: backport-skip

#18203 Cover the warn password policy usage of ValidatedPassword setting
  logstash-core/spec/logstash/settings_spec.rb
Labels: bug

#17945 Replace buildkite jdk version check w/GH action
  .buildkite/jdk_availability_check_pipeline.yml
  .ci/updatecli/bump-java-version.yml
  .github/workflows/bump-java-version.yml
  build.gradle
  catalog-info.yaml
  ci/check_jdk_version_availability.sh
Labels: backport-active-all

#18160 Measure current batch byte size and event count
  logstash-core/lib/logstash/api/commands/stats.rb
  logstash-core/spec/logstash/api/modules/node_stats_spec.rb
  logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java
  logstash-core/src/main/java/org/logstash/execution/QueueReadClientBatchMetrics.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/MetricExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/MetricKeys.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/NamespacedMetricExt.java
  logstash-core/src/main/java/org/logstash/instrument/metrics/gauge/LazyDelegatingGauge.java
  logstash-core/src/test/java/org/logstash/instrument/metrics/MockNamespacedMetric.java
  qa/integration/specs/monitoring_api_spec.rb
Labels: enhancement

#18017 Documentation for batch's event metrics (current and average)
  docs/reference/logstash-settings-file.md
  docs/reference/tuning-logstash.md
  docs/static/spec/openapi/logstash-api.yaml
Labels: docs
