Repository elastic/logstash, pull requests merged in 2025-06, with the labels that each got.

#17700 Docs: Ensure docs are built for version branches
  .github/workflows/docs-build.yml
Labels: backport-9.0

#17653 Doc: Update cloud terminology
  docs/docset.yml
  docs/reference/advanced-pipeline.md
  docs/reference/connecting-to-cloud.md
  docs/reference/index.md
Labels: docs, backport-active-9

#17738 Add lockfile for newly created 9.1 branch
  Gemfile.jruby-3.1.lock.release
Labels: backport-skip

#17743 Upgrade OSS and Full docker image to Ubuntu 24.04
  docker/README.md
  docker/templates/Dockerfile.erb
  docs/static/docker.asciidoc
  qa/docker/spec/full/container_spec.rb
  qa/docker/spec/oss/container_spec.rb
Labels: backport-8.17, backport-8.18

#17688 Doc: Add clarification about API key format for Logstash
  docs/reference/connecting-to-cloud.md
  docs/reference/images/logstash_api_key_format.png
  docs/reference/index.md
  docs/reference/secure-connection.md
Labels: docs, backport-active-9
